### ISSUE TITLE
Esc sollte auch nicht-sichtbare, aber ausgewählte Objekte/Knoten abwählen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#105]
Wenn man alles angewählt hat sollte doch mit ESC alles abgewählt werden oder?
Beim Gebäude oder Gebäudelevel bzw. Raum funktioniert das nicht mehr.

**Comment by ghorwin** [comment]
Das hat noch nie funktioniert - es werden nur "sichtbare" Objekte manipuliert.
Das kann man aber leicht einbauen.
