### ISSUE TITLE
Network supports simple thermal boundary conditions

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#113]
Es lassen sich einfache thermische Randbedingungen für die Rohre und HeatExchanger festlegen:
-Temperatur
-Wärmestrom

**Comment by Labauke** [comment]
Es bleibt noch offen ob es eine allgemeine HeatExchange Schnittstelle im NandradSolver gibt, die dann für alle Modelle den Wärmestrom bereitstellt

**Comment by KnutKnudson** [comment]
Eine allgemeine HeatExchange Schnittstelle macht nur in EInzelfällen Sinn, zum Beispiel, wenn generell ein Wärmestrom von außen vorgegeben wird. In diesem Fall würde ich davon ausgehen, dass zu wenig Detailwissen über die Wärmeaustauschmechanismen der Netzwerkkomponente vorliegt. HIer ist lediglich die EInbindung ins Netzwerk und eventuell die Abbildung thermischer Trägheitseffekte im Fluid interessant. Dieser Spezialfall hat ein eigenes Mdoell bekommen.
Für die anderen Anwendungen variieren Wärmeaustauschmechniamen sehr stark, so zum Beispiel bei der stationären oder dynamischen Rohrvariante. Sobald faktisch Detailwissen über die Wärmeabgabe vorliegt, ist kaum noch eine tragfähige Verallgemeinerung zu treffen.

Von daher gibt es jetzt folgende Kategorisierung:
Adiabates Modell -> Adiabates stationäres oder dynamisches Rohr
Modell mit Wärmeabgabe ->  Alllgemeines Modell mit vorgegebenem Wärmestrom, Spezialmodelle mit vorgegegebener Außentemperatur (Stationäres Rohr mit Wärmeaustausch, dynmaisches Rohr mit Wärmeaustausch)

Erweiterungen offen
