### ISSUE TITLE
NetworkElements can exchange heat with FMUs

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#115]
interfaces for the heat exchange are defined

**Comment by KnutKnudson** [comment]
Hier fällt die Problematik der KLU-Serialisierung mit hinein. Diese muss noch gelöst werden (und setzt ein paar Designänderungen voraus).

**Comment by ghorwin** [comment]
Wir beschränken uns zunächst auf iterationsfreie FMI Co-Simulation -> keine Serialisierung notwendig.
Wärmeaustauschschnittstellen über generische InputReferenz-Unterstützung bei FMUs funktioniert soweit.
