### ISSUE TITLE
Network outputs use displayName

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#117]
Folgendes Problem: Bei großen Netzwerken mit hunderten Elementen wird die Ausgabe mit Networkelement(id=257) schnell unübersichtlich.
Der Nutzer möchte in der Oberfläche Namen für bestimmte Elemente vergeben, z.B. einem Gebäude (Einfamilienhaus) "EFH35". Das möchte er logischerweise bei den Ausgaben wiederfinden.

Vorschlag: Es gibt die Option displayName zu verwenden, um Eindeutigkeit zu wahren wird die id noch angehängt.

Die Ausgabe lautet dann
<m_displayname>_id<m_id>.<Quantity>

also zB.
EFH35_id123.FluidMassFlow

wenn m_displayName.empty kann man den Unterstrich auch weglassen zB.
id123.FluidMassFlow

Das "NetworkElement" in den bisherigen Ausgaben ist eigentlich überflüssig.

**Comment by ghorwin** [comment]
Guter Vorschlag, ließe sich auch verallgemeinern. Jetzt müssen wir für alle Möglichkeiten Regeln für die Erstellung der Variablennamen (Spaltenüberschriften) aufstellen.


* Displayname gegeben oder nicht
* Displayname enthält [] oder sonstwie unerlaubte Zeichen
* Displaynamen sind nicht eindeutig

Es gibt noch eine Anforderung: 

Für die Verwendung im integrierten Auswertungsmodul (Gebäude/Netzwerk) muss man die benötigten Ergebnisgrößen korrekt erkennen. Bei der bisherigen Benennung nach Referenztyp+ObjektID+Variablenname war das eindeutig möglich. Wenn nun teilweise eine andere, nutzerspezifische Benennung verwendet wird, muss man entweder:

a) Nutzerspezifische Ausgabenamen/Displaynamen auf die benötigten Ergebnisgrößen "mappen"
b) Ausgabedaten duplizieren, d.h. Ergebnisse "nutzerfreundlich" und "auswertungsfreundlich" benannt rausschreiben

Wir könnte die ganze Fehlerbehandlung auch dem Nutzer überhelfen und ein Ausgabeflag einführen: "UseDisplayNameForVariables" - dann wird bei jedem Objekt mit Displaynamen eben nur dieser benötigt (auch ohne ID/Typ etc.) und der Anwender ist selbst dafür verantwortlich, eindeutige und gültige Displaynamen zu vergeben.

**Comment by Labauke** [comment]
Ja den Vorschlag mit Ausgabeflag und der Verantwortung des Nutzers für die Bennenung befürworte ich auch. Allerdings sollte für den Fall dass der displayName leer ist und das Flag "UseDisplayNameForVariables" gesetzt ist, die ID als Ausgabeaname benutzt werden.

Das mit dem internen Auswertungsmodul wusste ich noch nicht, klingt aber gut.  Das Rausschreiben einer Mapping-Datei wäre natürlich performance mäßig unkritischer, kann auch einfach eine zusätzliche Zeile in der Ausgabedatei sein.

**Comment by ghorwin** [comment]
Beispiele: 

RefType = `NetworkElement`
Quantity = `FluidMassFlux`

gives

Column header = `NetworkElement(id=101).FluidMassFlux [kg/s]`

**Comment by ghorwin** [comment]
Das Problem bei der Verwendung der Anzeigenamen ist, dass die Ausgabedateien keine Kenntnis der eigentlichen Parametrisierungselement haben. Man müsste also den DisplayNamen in die QuantityDescription integrieren.

**Comment by ghorwin** [comment]
Alternative decided:
NandradSolver writes `outputVariables.mapping` in `var` subdirectory of project directory with content:

```
NetworkElement[15]  <tab>  <displayName>
```

PostProc erhält die Funktionalität, diese Datei einzulesen und spezifisch für einzelne Ergebnisdatein anzuwenden (d.h. QuantityName String-Ersetzung durchzuführen).

Alternativ kann mit einem Python-Script diese Änderung in der TSV-Datei durchgeführt werden.

**Comment by ghorwin** [comment]
Erstellung der Mapping-Datei:

- die DisplayName Attribute sind meist nur im Konstruktor eines ModellObjekts verfügbar. Das Modellobjekt selbst weiß, welche Ergebnisgrößen generiert werden. Damit sind dort alle Informationen zusammen, um die Mapping-Information zu generieren.
- Beim Erstellen einer QuantityDescription wird der DisplayName als Eigenschaft gesetzt (so vorhanden)
- Der OutputHandler kann aus der gesammelten Liste der veröffentlichten Ergebnisgrößen die Mapping-Datei erstellen.
