### ISSUE TITLE
Implement HeatPump model

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#118]
- the model needs a time-series (given as tsv) of heat demand from the building
- die Parameter jeweils 6 Koeffizienten für die biquadratischen Polynome Pel = f(Tcond, Tevap) und COP = f(Tcond, Tevap)
-->  f = a1 + a2 * Tevap + a3 * Tcond + a4 * Tevap * Tcond + a5 * Tevap ** 2 + a6 * Tcond ** 2

**Comment by ghorwin** [comment]
Optionen für Datenablage des "Heat demands":
- externe tsv-Datei als Datenquelle referenzieren (dabei Platzhalter `${ProjectDirectory}` etc unterstützen)
- Zeitreihedaten in der Oberfläche importieren und in einem `<LinearSplineParameter>`  ablegen; dies hat den Vorteil, dass man auch die Interpretation der Daten (interpolation/Stufen) mit definieren kann

**Comment by Labauke** [comment]
Ich wäre trotzdem für die erste Option, wie auch in Delphin.
Man kann dann die tsv-Dateien jederzeit extern neu generieren und sie werden vor Simulationsstart gelesen und geprüft

**Comment by Labauke** [comment]
see #225
