### ISSUE TITLE
Allow time-series boundary conditions for temperature and heat flux

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#119]
LinearSpline as a parameter of HydraulicNetworkElement

**Comment by Labauke** [comment]
Muss im NandradSolver noch eingebaut werden

**Comment by KnutKnudson** [comment]
Ist mittlerweile drin, aber sollte getestet werden. Es wird derzeit von Modell zu Modell entschieden, ob eine Wärmestrom- oder Temperaturunterstützung angeboten wird.

**Comment by Labauke** [comment]
Regression Tests sind eingebaut
