### ISSUE TITLE
HydraulicComponents werden Teil der Database

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#120]
Ich bin jetzt doch dafür die in die DB zu packen. 
Modelle wie zB. die Wärmepumpe hat viele komplexe Parameter, die will man nicht für jedes Projekt neu eingeben, auch Pumpen etc. 
Man kann zum Teil dann direkt Modelle von Herstellern hinterlegen.

--> Datenstruktur ändern
--> DB Dialog erstellen

**Comment by ghorwin** [comment]
`VICUS::NetworkComponent` erstellt. Die Klasse erbt von NANDRAD::HydraulicCompent, hat allerdings einen multi-language-String als displayName.
Serialisierung muss noch gemacht werden.
