### ISSUE TITLE
DB Handling für Pipes 

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#121]
Die VICUS::NetworkPipes sind im Moment Teil jedes einzelnen VICUS::Networks.

Die NetworkPipes der DB sind im Moment nicht damit verknüpft.

Wunschvorstellung:
Jedem Network kann eine Auswahl aus Pipes der DB (Referenzen auf die DB) zugewiesen werden. Das ist notwendig, da der Auslegungsalgorithmus ja automatisch darauf zugreift und dabei nur eine bestimmte Auswahl verwenden soll (nur PE-Rohre zB.).

Alternative, vielleicht einfacher:
Die Pipes bekommen eine zusätzliche Eigenschaft "Group" oder "Type". ZB. Type=PE.
Dem Netzwerk kann man dann sagen verwende nur pipes dieses Types. 
->Das ist vermutlich die bessere Lösung

**Comment by Labauke** [comment]
@ghorwin ich bräuchte hierzu nochmal deine Meinung bevor ich irgendetwas einbaue...

**Comment by ghorwin** [comment]
Aktuell bekommt/hält ein Netzwerk eine Auswahl an verfügbaren Pipes via Liste von PipeIDs. Es sollte einen Dialog in der Oberfläche geben, die es erlaubt die für ein Netzwerk zur Verfügung stehenden Rohre auszuwählen. Bei der Auswahl können gerne auch Gruppen zum Einsatz kommen (i.e. "Select by material" oder so).

**Comment by ghorwin** [comment]
Vielleicht ins PropertyWidget integrieren? "PropertyMode -> Networks -> Pipe sets" und dort eine Tabelle/Liste mit ausgewählten Pipes anlegen. + und - Buttons implementieren, bei + wird der SVDBNetworkPipes-Dialog im select() Modus aufgerufen.
