### ISSUE TITLE
Alt+Click starts rubber band selection mode

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#126]
Alt+LMB Click starts rubber band, operation depends on selection, operation continues as long as alt+left mouse button is held down. Operation is applied when rubber band operation is finished.

- From top-to-bottom: selection on
- From bottom-to-top: selection off
- From left-to-right: only include object fully contained in selection (fuzzy?)
- From right-to-left: include object contained or intersected by rubber band

Coloring: 

- top-to-buttom green (= on)
- bottom-to-top red (=off)

**Comment by ghorwin** [comment]
Pick point on near plane-> store point, for mouse drag get new near plane point -> draw transparent rect/boundary line

Selection is changed when mouse button is released.

**Comment by hirseboy** [comment]
Hey Andreas, können wir uns diesbezüglich mal unterhalten. QPainter auf QOpenGLWindow sollte per se gehen, aber ist doch etwas kompliziert und habe ich bisher nicht wirklich hinbekommen. Alternativ kann man natürlich auf direkt mit OpenGL 2D zeichnen, aber das ist wiederum auch nicht so einfach.
LG

**Comment by hirseboy** [comment]
Okay, alles klar! Ich versuche es!

**Comment by hirseboy** [comment]
Closed by 804cf460. Review awaiting.
