### ISSUE TITLE
draw network edges and nodes in AddGeometry mode

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#127]
Kann auch zu einem anderen Milestone geschoben werden

**Comment by Labauke** [comment]
Hier das Konzept
[Konzept Netzwerk zeichnen.md](https://github.com/ghorwin/SIM-VICUS/files/8878267/Konzept.Netzwerk.zeichnen.md)

**Comment by Labauke** [comment]
# Konzept Netzwerk zeichnen

Es gibt 2 Zeichenmodi: 

- Rohre / Edges

- Verbraucher (Gebäude) / Nodes



 ## Rohre zeichnen

### 1. Polygonzug zeichnen

Es wird ein `Polygonzug` (`polygon traverse`) gezeichnet, fast identisch mit dem jetzigen Zeichnen eines Polygons.

Dabei soll auch das entsprechende Polygon vertexes TableWidget verwendet werden. Die einzelnen Punkte (vertexes) werden im TableWidget gezeigt und können auch gelöscht werden. 

Die Prüfung unterscheidet sich vom Polygon: Ein `Polygonzug` ist valide sobald 2 Vertexes existieren. Weitere Prüfungen gibt es nicht. Der `Polygonzug` kann sich selbst  kreuzen.

### 2. Pipelines erzeugen

Mit dem Bestätigen (Klicken auf "Complete polygon traverse")  wird ein Widget entsprechend dem jetzigen "Surface / Zone properties" widget gezeigt. Das `PipelinePropertiesWidget`. Dort kann man auswählen zu welchem Netzwerk der `polygon traverse` hinzugefügt werden soll und welche PipeProperties verwendet werden sollen.

<img src="C:\Users\Hauke\AppData\Roaming\Typora\typora-user-images\image-20220610111812859.png" alt="image-20220610111812859" style="zoom:50%;" />

 Mit einem Klick auf "create pipeline" werden für die Linien des Polygonzugs VICUS::Edges erzeugt und für die Punkte des Polygonzugs VICUS::Nodes, welche den Typ MT_Mixer haben.



## Gebäude / Verbraucher zeichnen

### 1. Vertexes zeichnen

Es werden nur einzelne vertexes gezeichnet, die nicht verbunden sind. Dabei wird auch wieder das Polygon vertexes TableWidget gezeigt. 

Eine Prüfung gibt es nicht.

### 2. Nodes erzeugen

Mit dem Bestätigen ("Klicken auf Complete Nodes") wird ein Widget entsprechend dem obigen gezeigt. Das `NodePropertiesWidget`

<img src="C:\Users\Hauke\AppData\Roaming\Typora\typora-user-images\image-20220610125607820.png" alt="image-20220610125607820" style="zoom:50%;" />

Es können die Eigenschaften der Nodes (Type, nominal power) angegeben werden und anschließend mit "Create Nodes" werden die VICUS::Nodes erzeugt.

**Comment by ghorwin** [comment]
Im Prinzip ziemlich geradlinig umzusetzen... 

- Vorschlag: zunächst ein neues "NewGeometryObject" für Rohrzeichnen erstellen
- dann Widget für Eingabe der Rohreigenschaften programmieren
- zum Schluss alles zusammenbauen (das ist der schwierige Teil, weil man hier die ViewStates berücksichtigen muss) 

---> zusammen mal die aktuelle Implementierung durchsehen!
