### ISSUE TITLE
Add regression tests for simple flow networks with thermal exchange

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#133]
- One small regression test for each heat exchange/pipe model implemented.
- Regression tests for mixer/splitter to check correct temperature mixing; two parallel pipes connected to very different ambient temperatures -> should give different pipe outflow temperatures that need to be mixed correctly

Case 1:
 
- 2 Rohre mit unterschiedlichem Durchmesser -> Strömungsgeschwindigkeiten ->  Übergangskoeffizienten
- Austausch der Rohre mit konstanter Umgebungstemperatur
- Abklingen der Temperaturen bis steady-state

Case 2:

- Wärmetauscher mit vordefinierter Wärmeabgabe 
- Rohr mit Wärmeübergabe an Erdreich
- Rechnen bis stationärem Zustand

(Pumpe in Case 1 und 2 ideal, d.h. Effizient = 100%)

Case 3: Wärmeabgabe im Rohr und im System

- Test Plausibilität Wärmeabgabe und Druckverlust durch unterschiiedlich parametrierte Rohre im stationären Zustand
- 2 parallele Rohre mit unterschiedlicher Dimension (Rohr 2 hat doppelte Länge und doppelten Durchmesser)
- 2 Pumpen mit angespasster Druckdifferenz (Pumpe 1 liefert die vierfache Druckdifferenz)
- Konstante Außentemperatur
- Konstanter Leistungsverlust im Netzwerk, provisorisch abgebildet durch Wärmetauscher mit Wärmeverlust und geringem Druckverlustbeiwert
- Erwartungshaltung: doppelter Massestrom und doppelter Wärmeverlust durch Rohr 2, identische Fluidaustrittstemperaturen für beide Rohrstränge (letzteres ist nur mit stationärem Modell prüfbar). Die Summe der Rohrwärmeverluste muss der aufgenommenen Wärmemenge (Wärmestrom) im Wärmetauscher entsprechen und somit die thermische Bilanz im Netzwerk erhalten.

Case 4: Mischen

- 2 parallele Kreise, Rohre mit unterschiedlichen Masseströmen, siehe Case 3 (Rohr 2 hat doppelt so viel Massestrom wie Rohr 1)
- unterschiedliche Umgebungstemperaturen für beide Rohre
- beim Mixer-Knoten muss die Mischtemperatur richtig berechnet werden
- Erwartung: Das Rohr mit der geringeren Umgebungstemperatur gibt diesselbe Wärme ab, welche das Rohr mit der wärmeren Umgebungstemperatur aufnimmt. Die Temperaturspreizung zwischen Fluidtemperatur und Außentemperatur im Rohr ist beim größeren Rohr (Rohr 2) doppelt so hoch wie beim keineren (Rohr 1), allerdings mit umgekehrtem Vorzeichen. Mit Kenntnis der stationären Lösung lässt sich außerdem nachweisen, dass die Mischtemperatur im Auslassknoten genau 1/3 Außentemperatur Rohr 1 + 2/3 Außentemperatur Rohr 2 betragen muss.

**Comment by Labauke** [comment]
Ich würde parallel dazu Validierungsbeispiele für thermische instationäre Rohre in Modelica machen. Wenn wir noch eine SimulationX Lizenz bekommen, würde ich das gerne benutzen, mit OpenModelica komme ich irgendwie nicht weiter...

**Comment by ghorwin** [comment]
Vorschlag: erstmal bauen wir Testfälle, in denen wir selbst unsere implementierten Gleichungen prüfen können. Dann kann man ein Modell-Modell-Vergleich machen, wobei es natürlich verfahrensbedingt und modellbedingt Unterschiede geben wird.
