### ISSUE TITLE
Consistent error messages in NANDRAD

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#139]
Aktuell werden Fehlerausgaben schon recht detailliert ausgegeben, bspw.:

```
Parameter 'PumpEfficiency' is missing/undefined.
Missing/invalid parameters for component 'Pump 0815 (constant pressure)' [1] of type ConstantPressurePump.
Error intializing network component with id #1.
Error initializing hydraulic network with id #1.
Critical error, simulation aborted.
```

Bei der Schreibweise der Fehlermeldungen sind wir in NANDRAD noch etwas inkonsistent. Folgende Optionen sind häufig vertreten:

- Error in ... with id 105.
- Error in ... with id #105.
- Error in ... (id #105).
- Error in ... (id=105).
- Error in ... 'displayName' [105].

Wir sollten vielleicht in einem Style-Guide festlegen, welche allgemein zu verwenden wären.

**Comment by Arombolosh** [comment]
Also ich wäre bei sowas für einen folgenden Text mit zwingenden Angaben von:

- Zeile in der xml-Datei
- ID und Name des Objects
- der falsche oder fehlende Parameter

Beispiel bei einer Pumpe:

`
<Models>
  <Model type="PumpBlub" name="Pumpe" id=10>
    <Parameter name="Eff..." ....>100</Parameter>
  </Model>
</Models>
`


Das Objekt in Zeile XX mit dem Namen YY (Typgruppe) hat einen fehlerhaften/fehlenden Parameter XYXYX .

Das würde ich bisher am wichtigsten sehen denn unsere Projekte waren schon recht groß und da ist es wichtig wo man sich befindet.

**Comment by ghorwin** [comment]
Zeile in XML Projekt ist in der Regel nicht möglich, da der XML-Parser sonst bei jedem eingelesen Parameter die Ursprungszeile ablegen müsste. Das geht aber nicht und außerdem gibt es bisweilen abgeleitete Parameter, die auch geprüft werden.

Mir ging es eher darum, wie genau die Angabe von Objekt und ID gemacht wird. Letztlich gibt es 3 Attribute:

- Objekttyp/Klasse
- ID
- DisplayName (wenn verfügbar, kann "" sein)
-

**Comment by ghorwin** [comment]
Festlegung:

Bei Ausgabe ungültiger/fehlender IDs: 
```Invalid/unknown construction type with id #%1```

Bei Ausgabe von Prüfproblemen in Objekten mit Displaynamen:
```Missing parameter %1 in definition of network component '%2' (#%3)```

Grundregeln:

- DisplayName in ' ', da diese Lehrzeichen enthalten können (gilt auch für Dateinamen oder andere Zeichenketten, welche Leerzeichen enthalten können)
- - KeywordNamen werden nicht in ' ' geschrieben (enthalten niemals Leerzeichen)
- ids erhalten ein # vorangestellt und werden, wenn als Zusatzinformation gegeben, in runde Klammern geschrieben
- id wird klein geschrieben
