### ISSUE TITLE
Wärmeaustausch zwischen Rohren und Zonen

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#143]
Modellierung:

Je Netzwerk wird bei entsprechender HeatExchange-Definition je Zone eine Wärmeaustauschstrom berechnet.

Ein Strömungselement kann Wärme mit einer Zone austauschen, wenn ein entsprechender HeatExchange-Typ definiert ist. Aktuell gibt es nur `HeatExchangeWithZoneTemperature`, welches folgendes Modell beschreibt:

- Berechne Wärmeaustausch basierend auf Temeperaturdifferenz zwischen *Medientemperatur* und *Raumlufttemperatur*
- Verwende Rohr-Übergangswiderstände/Transferkoeffizienten
- entspricht der Berechnung von Verlustwärme durch (ungedämmte/schlecht gedämmte) Heizrohre in Zonen

> AN: eigentlich müsste man den HeatExchangeType diesbezüglich nochmal konkretisieren, also z.B. `ExchangePipeInZone`, wobei 'Exchange' für "Temperaturdifferenz-ist-Triebkraft" steht, und `Pipe` sagt aus, wie der effektive U-Wert berechnet wird, und `InZone` sagt, dass der Gegenpart des Wärmeaustauschs die Zone ist.

Ein Strömungselement mit definiertem Wärmeaustausch mit der Zone führt zu:

- ThermalNetworkStatesModel veröffentlicht InputReferenz auf Zonentemperatur
- ThermalNetworkStatesModel aktualisiert Zonentemperaturen in allen betroffenen Strömungselementen
- Strömungselemente berechnen je nach HeatExchangeModel den Wärmestrom von/zur Zone
- ThermalNetworkBalanceModel sammelt alle Wärmeströme zu Zonen ein, summiert diese je Zone auf und veröffentlicht die Wärmeströme in einer vektorwertigen Ergebnisgröße 'ZoneHeatGains', refType "Network", id = network id, vector-id = zone-id.

Auf Gebäudeseite:

- RoomBalanceModel veröffentlicht optionale Inputreferenzen auf `Network.ZoneHeatGains[myZoneID]` für *alle* Netzwerke
- alle zurückgelieferten gültigen Adressen landen in einem Vektor
- bei der Berechnung der Divergenzen werden alle diese Ströme aufsummiert und der Divergenz zugeschlagen
- RoomBalanceModel erhält zusätzliche Ausgabegröße `NetworkHeatGains` oder so, welche die Summe aller Wärmeströme aus allen Netzwerken und allen Strömungselementen mit Austausch zu dieser Zone beinhaltet.

**Comment by Arombolosh** [comment]
Das wäre jetzt von außen betrachtet ein reiner Heizkörper (über eine Rohrabbildung)?

**Comment by ghorwin** [comment]
Ja, deswegen auch mein Vorschlag, den ExchangeType `ExchangePipeInZone` zu nennen. Wir werden sicher noch etliche andere Wärmeübergabemodelle (Heizkörpermodelle verschiedener Modellkomplexitäten, ...) haben. Jeder hätte einen eigenen HeatExchange-Modelltyp.
