### ISSUE TITLE
Elemente in NANDRAD auf gleiche ID Testen 

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#147]
Ist mir bei den HydraulicNetworkElements aufgefallen. Es gibt bisher keinen Test darauf, ob zwei Elemente die gleiche ID haben. 
Vielleicht sollte es hierfür eine allgemeine Funktion für alle Element in Nandrad beim XML Lesen geben?

**Comment by ghorwin** [comment]
Richtig, betrifft alle Datenelemente, auch die im Gebäude. 

Siehe Project.cpp:110 und folgend.

Hier müsste man jetzt die Netzwerk-Datenstrukturen testen. Allerdings ist zu beachten, dass Components und PipeProperties nur in einem Netzwerk eindeutig sein müssen, aber Elemente global eindeutig sein müssen.

Die Function checkForUniqueNames() kann daher zwar (in einer Schleife über alle Netzwerke) für Components und PipeProperties verwendet werden, aber für die Netzwerkelemente müsste man nochmal was extra schreiben.

**Comment by Labauke** [comment]
Danke @KnutKnudson
