### ISSUE TITLE
Parameter für Anteil der Pumpenverluste die an das Fluid abgegeben werden

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#149]
Problem: 
Bei großen Pumpen sitzt der Motor oft außerhalb des Gehäuses, die Verluste werden also nicht vollständig an das Fluid abgegeben.

Vorschlag:
Wir führen einen Parameter "FractionOfPumpDissipationToFluid" ein, um den Anteil der Pumpenverlust, welche als Wärme an das Fluid abgegeben werden definieren zu können.

**Comment by ghorwin** [comment]
Kann man so machen. Optionaler Parameter, wenn gegeben, wird gerechnet:
```c++
void TNPumpWithPerformanceLoss::setInflowTemperature(double Tinflow) {
	m_inflowTemperature = Tinflow;

	// mechanical power of pump is pressure head times volumetric flow
	// Pa * m3/s = N/m2 * m3/s = N*m/s

	// calculate pump performance
	m_mechanicalPower = m_massFlux/m_fluidDensity * m_pressureHead;

	// efficiency is defined as portion of total electrical power used for mechanical
	// Pelectrical * m_pumpEfficiency = Pmechanical
	m_electricalPower = m_mechanicalPower/m_pumpEfficiency;
	// energy balance of pump: mechanical power + heating power = electrical power
	double heatingPower = m_electricalPower - m_mechanicalPower; // positive value
	// compute fraction of heat that is supplied to the fluid
	m_heatLoss = - m_fractionOfPumpDissipationToFluid * heatingPower; // negative, because we heat up the fluid
	// store heat flux to the environment as optional output
	m_heatLossToEnvironment = heatingPower + m_heatLoss; // mind: m_heatLoss is negative
}
``` 

@Hauke: bitte mal die Gleichungen oben prüfen

**Comment by Arombolosh** [comment]
m_pumpEff ist immer <= 1 daher muss P_ele immer >= P_mech sein

so die Wärmeverluste können dem Fluid über folgenden Wert zugeordnet werden

Fraction of Motor Inefficiencies to Fluid Stream (so heißt das ding in E+)
Das würde ich auch als variablenNamen so sehen
0 <= FractionOfMotorInefficienciesToFluidStream <= 1
Default 1

später könnte man noch sagen wo die Wärme hin geht wenn kein Wärmeeintrag ins Fluid besteht (z.B. in die Zone wo die Pumpe steht). Ist aber erst wichtig wenn wir in der Oberflächen alles haben und IFC importieren können :)
