### ISSUE TITLE
getOpenFileName unter Windows verbessern

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#151]
Gibt es einen Grund, dass "QFileDialog::DontUseNativeDialog" bei getOpenFileName verwendet wird?

Zumindest unter Windows bekommt man ein nerviges Fenster ohne Adresszeile...

**Comment by ghorwin** [comment]
Ohne das führt das auf verschiedenen Rechnern zum Hängen/Absturz des Systems. Ist eine Inkompatibilität mit der Windows-API (funktioniert bei einigen Win10 Versionen, bei anderen nicht). Die einschlägigen Einträge in Foren beschreiben das Problem, aber nicht genau bei welcher Windows Version (welchen Updates) das Problem auftritt. 

Vorerst haben wir wohl keine Chance, als das so zu lassen.

**Comment by ghorwin** [comment]
Wrap argument in #ifdef and have a central configuration file for both QtExt and SV
