### ISSUE TITLE
Extend NANDRAD::LinearSplineParameter to allow tsv-data read from file as well

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#154]
Suggestion:

Either have
```xml
<LinearSplineParameter name="ThermalLoad" interpolationMethod="linear">
   <X unit="h">0    6    8   10   17   18  19  20</X>
   <Y unit="W">0  0.5  0.8  1.0  0.7  0.6 0.5   0</Y>
</LinearSplineParameter>
```

or

```xml
<LinearSplineParameter name="ThermalLoad" interpolationMethod="linear">
   <TSVFile>${Project Directory}/SomeTSVData.tsv?2</TSVFile>
</LinearSplineParameter>
```

Notation as in PostProc: `SomeTSVData.tsv?2` means read file `SomeTSVData.tsv` and take second data column.

Rules are:

- if `<TSVFile>` is given, there must not be X or Y xml elements specified as well
- in `LinearSplineParameter::checkAndInitialize()` first check if path is given, then read it (including all relevant checks), copy data to x and y vectors and then do the usual initialization
- path placeholders present in the TSVFile path must be replaced before `LinearSplineParameter::checkAndInitialize()` is called.

**Comment by Labauke** [comment]
@ghorwin vielleicht nochmal drüber schauen, es gibt vermutlich eine fertige Funktion für tinyxml.cpp Z1449 ff.
