### ISSUE TITLE
IBK::LinearSpline - should they get TSVFile data input as well?

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#160]
The NANDRAD::LinearSplineElement can be parametrized by either in-place definition of X and Y values, or by referencing an externally defined TSV-file (see also #154).

Should this be added to IBK::LinearSpline as well?

**Comment by Labauke** [comment]
Ich kann nicht viel dazu sagen, da ich die LinearSpline bisher nicht benutze.  Aber da die Größen die wir aus einem tsv-file lesen meistens eine Einheit haben werden, kann man wahrschinlich auch einfach LinearSplineParameter benutzen oder?

**Comment by ghorwin** [comment]
Entschieden: ja, sinnvolle Erweiterung
