### ISSUE TITLE
Fußbodenheizungsmodell/Flächenkollektor

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#161]
Interessante Fragestellungen sind:
- hydraulischer Widerstand der einzelnen Felder
- Wärmespeicherung in Fluid und aktivierten Schichten (1D discretisiertes Modell, oder Bulk-Volumen-Ansatz)
- Wärmeübergabe Fluid -> umgebendes Material -> Rand
- Äquivalenzmodellierung Einzelrohre - Fläche
- Parametrierung: wie kommt man bei der Modellierung von "Beheizter Fläche" zu "äquivalenter Rohrlänge" ?

**Comment by KnutKnudson** [comment]
Es gibt einen wesentlichen inhaltlichen Diskussionspunkt: was passiert, wenn ein Fußbodenwandelement aufgrund angrenzender Trennwände (beispielsweise im Untergeschoss) durch Präprozessing in zwei ConstructionInstances geteilt wird? 
Man kann doch nicht davon ausgehen, dass die Verlegung der Fußbodenheizstränge einer solchen 'künstlichen' Unterteilung folgt. 
Es gibt Ansätze, Rohrstränge oder Heizkörpergleichungen auf größere oder kleinere Geometrien zu dimensionieren (STichwort Ähnlichkeit). Eventuell sollte man über solche Ansätze diskutieren.
