### ISSUE TITLE
Datamodell Refinements

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#165]
1. Wenn man eine eine "HeatFluxSpline" für einen vorgegebenen Strom angibt, tendieren die Anwender dazu, einen positiven Strom als Wärmegewinn für das Element zu interpretieren. Bei den skalaren Heizlasten haben wir das durch die Bennennung "HeatLoss" verdeutlicht - das geht jetzt aber bei HeatFluxSpline nicht mehr. Auch ist die Bezeichnung "HeatFluxSpline" für zeitlich veränderliche Temperaturen etwas irreführend. Vielleicht wäre "HeatExchangeSpline" neutraler? Oder habt Ihr andere Ideen dazu?

2. Trennung der HeatExchangeType Parametrierung von den dazugehörigen Parametern: natürlich ist die Angabe des HeatExchangeType bei einer Componente verallgemeinerbar für mehrere Elemente. Dennoch muss bei fast allen HeatExchange-Modellen ein elementspezifischer Parameter gegeben sein. Wenn man z.B. das gleiche Rohr einmal mit Wärmeaustausch und einmal adiabat verbaut, braucht man zwei Componentendefinitionen, obwohl auch die Elemente unterschiedlich konfiguriert sind. Eine Alternative wäre:

```xml
<HydraulicNetworkElement id="1003" ...>
  <HeatExchange model="HeatFluxConstant">
    <IBK:Parameter name="HeatLoss" unit="W">-50</IBK:Parameter>
  </HeatExchange>
</HydraulicNetworkElement>
```

Beim Lesen der Projektdatei hat man dann auch gleich den Bezug zum jeweiligen Austauschmodell und den erforderlichen Größen.

**Comment by Labauke** [comment]
die Eigenschaft des HydraulicElements heißt doch bereits "m_heatFluxSpline" bzw. in xml "HeatFluxSpline".

Ja, man könnte den HeatExchangeType auch zur Eigenschaft des HydraulicElements machen, alllerdings hängt die Parametrisierung der Komponente zum Teil vom HeatExchangeType ab (Bei Adiabat braucht man keinen Übergangskoeffizienten, bei TemperatureConstant schon).

Man könnte die HeatExchangeTypes aber umbenennen für mehr Klahrheit. 
 `HT_TemperatureConstant` --> `HT_AmbientTemperatureConstant` 
`HT_TemperatureDataFile` --> `HT_AmbientTemperatureSpline` 
`HT_HeatFluxDataFile` -> `HT_HeatLossSpline`

**Comment by ghorwin** [comment]
Genau, man müsste dann alle Parameter für den Wärmeaustausch ins Element verschieben. Je nach Größe des Netzwerkes würde da ggfs. einen Redundanz der Daten und damit größere Projektdatei verursachen. Eine Umbenennung der Enum-Typen ist wahrscheinlich nicht notwendig, eher noch, dass man das gesamte HeatExchange Zeugs in einer eigenen Klasse verpackt, und dort auch alle Fehlerprüfungen kapselt. Und dann gibt's in jedem Element nur die Variante: HeatExchange angegeben oder nicht (dann adiabat).

Die Kapselung aller Wärmeaustaucheigenschaften/Parameter in eine einzige Klasse, welche als (optionaler) Member im Element gehalten wird, hat natürlich hinsichtlich der Quelltextübersicht Vorteile, bringt performancemäßig keinen Unterschied, und führt bei größeren Netzwerken zu größeren Projektdateien.

**Comment by Labauke** [comment]
Sorry, ich wollte sagen die Eigenschaft des HydraulicElements heißt doch bereits `m_heatExchangeSpline` bzw. `HeatExchangeSpline`, also das muss man nicht umbenennen

**Comment by KnutKnudson** [comment]
Zu 1.) schließe ich mich an, die EIgenschaft heißt meines Wissens nach bereits 'HeatExchangeSpline' (und kann sowohl eine Temperatur als auch einen Wärmestrom enthalten) - in den Testfällen sind die Dateien mit 'HeatFlux' bennannt. Dieses könnte man gegegebenenfalls klarer formulieren, so dass die Richtung des Wärmestromes eindeutig ist.

Zu 2.) bin ich ebenfalls für eine Verschiebung aller Parameter für den Wärmeaustausch in das individuelle HydraulicNetworkElement. Es ist davon auszugehen, dass der Wärmeaustausch (Umgebungstemperatur, Wärmeübergangskoeffizient, vorgegebener Wärmeverlust) ausschließlich vom Verlegungsort des Elementes abhängen. Selbst der Wärmeübergangskoeffizient kann nicht als Materialeigenschaft des Rohres/Wärmetauschers/Komponente gedeutet werden, sondern ist eine exklusive Eigenschaft der Umgebung. Von daher ist in meinen Augen die Parametrisierung der Komponente (HydraulicNetworkComponent) von der Parametrisierung des Wärmeaustausches zu trennen.

**Comment by ghorwin** [comment]
Entschieden: Refaktoring

- neue Klasse `HydraulicNetworkHeatExchange` erstellen
- enum `ModelType`  (vormals `HydraulicNetworkComponent::HeatExchangeType`)
- alle Parameter betreffend HeatExchange aus Component und Element in neue Klasse verschieben
- checkParameters()-Funktion implementieren
- Member-Variable vom Typ `HydraulicNetworkHeatExchange` in Element einfügen (und entsprechend checkParameters() aufrufen)
- Initialisierung der Module (Datentransfer) anpassen
- Testprojekte anpassen
