### ISSUE TITLE
lost focus while building a room

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#172]
Wenn beim Erstellen einer Zone zu erst der erste Punkt angekligt wird, dann die Object properties verändert werden (building, building level...) geht der Fokus in das Einstellungsfeld. Wenn ich dann die Achsen fixieren möchte oder die Länge der component eingeben möchte, muss ich vorher wieder in das Zeichengitter klicken.
Kann der Klick vermieden werden?

**Comment by ghorwin** [comment]
Die Shortcuts werden hierarchisch durchgereicht - es würde wahrscheinlich reichen, wenn man die relevanten Tastendrücke x,y,z und die Zahlentasten "0123456789,.-" weiter oben in der Programmhierarchie fängt und dort dann Richtung GeometrieView umleitet. 

--> Feature Request

**Comment by ghorwin** [comment]
Das Ganze ist komplizierter:
- wenn man im GeometryView (der beinhaltet die Szene und das PropertyWidget) die Tastendrücke abfängt, dann bekommt man - sofern der Fokus im PropertyWidget liegt, immer KeyEvents, die bereits "accepted" sind. Das ist sinnvoll, wenn man dort gerade in einem LineEdit tippt. Aber auch wenn der Focus auf einem Button ist, führt das Drücken der Taste x zum "accepted" keyrelease event
