### ISSUE TITLE
Wand wird nicht mehr dargestellt

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#174]
[TF08_Room.zip](https://github.com/ghorwin/SIM-VICUS/files/6123170/TF08_Room.zip)
![ScreenshotTF08Room](https://user-images.githubusercontent.com/75358827/110792853-33189b80-8274-11eb-9dd5-b1ee791885df.png)

Nach Drehen und Verschieben wird die linke Außenwand (Wall2) nicht mehr angezeigt. Wenn die Wand angewählt wird ist die markierte Wand zu sehen. Woran kann das liegen?

**Comment by ghorwin** [comment]
PlaneGeometry hat einen Fehler bei der Triangulierung -> Dirk's Aufgabe :-)

**Comment by ghorwin** [comment]
Rounding error problem, fixed in dc631f7567da5b408c445c20bd673d4d4811dea5
