### ISSUE TITLE
umgekehrte z-Achse

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#175]
![grafik](https://user-images.githubusercontent.com/75358827/110927751-51d76a80-8326-11eb-9654-d2909d46d744.png)

Ist das gewollt so, dass wenn ich eine Geometrie abklicke, dass sich dann die z-Achse umkehrt aber im Koordinatensystem noch positiv ist?
Wenn ich das Programm schließe und wieder öffne und eine Fläche anwähle ist die z-Achse wieder positv.

**Comment by ghorwin** [comment]
Ja, das lokale Koordinatensystem ist eben Abhängig von der Ausrichtung/Drehung der angeklickten Ebene. Das global Koordinatensystem ist immer gleich (links unten).
