### ISSUE TITLE
Höhendefinition in Geometrieerstellung

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#182]
Wenn eine Raumhöhe nicht über snap sondern über Werteingabe erfolgt, ist bei mir der Raum unterhalb der Gitterebene bei einem positiven Wert und oberhalb mit einem negativen Wert. Nach dem lokalen Koordinatensystem ist das auch richtig, es scheint mir nur ein bissschen unintuitiv wenn das globale Koordinatensystem nach oben positiv ist und meine Raumhöhe ja auch positiv ist.
Und nutzerfreundlicher fände ich es auch, wenn ich die Werteingabe der Höhe beispielsweise mit doppeltem Enterbestätigen fixieren könnte (also nach bestätigen des Wertes die Auswahl automatisch auf `create zone` springt) und das nicht über einen Mausklick sein muss. Im Moment ändert sich die Eingabe sofort, wenn ich mit dem Courser wieder in das Ansichtsfeld komme.

**Comment by ghorwin** [comment]
Wäre zu diskutieren... Problematisch ist das Ganze dann, wenn man eine schiefe Zone erstellt. Es hindert einen prinzipiell niemand daran, seitlich an eine existierende Hausfassade eine auskragende Konstruktion anzubauen, und da wäre die "Raumhöhe" dann eher als links/rechts Abmessung zu interpretieren. Einzig sinnvoll in allen Fälle wäre die Verwendung des lokalen Koordinatensystems als Bezug. 

Grundsätzlich sollte beim Zeichnen auf einer horizontalen Fläche aber für die Extrusion "position = oben" gelten. Man könnte hier einfach eine Spezialbehandlung einbauen, also wenn Normalenvektor 0,0,1 oder 0,0,-1 ist.

**Comment by ghorwin** [comment]
Vorschlag für das Verhalten:

Raumhöhe ist zunächst fix und wird aus BuildingLevel bezogen. Die Zeichenrichtung des Grundpolygons definiert normalerweise die Extrusionsrichtung. Spezialregel gilt bei horizontalen Flächen, hier ist die Extrusionsrichtung immer positiv global z.

Nach Absetzen des Bodenpolygons wird sofort die Zone mit der vorgewählten nominalen Höhe gezeichnet. Bewegen der Maus hat zunächst keinen Einfluss auf die Höhe. 

Die Höhe kann im Eingabefeld angepasst werden. Auch danach hat die Mausbewegung keinen Einfluss.

Das interaktive Anpassen der Höhe sollte durch einen Extra-Knopf ausgewählt werden. Die Szene springt dann in den "Pick Extrusion" Modus, bei dem das lokale Koordinatensystem gezeigt wird (ausgerichtet entsprechend der neuen Grundfläche, d.h. lokale z-Achse zeigt positive Extrusionsrichtung) und die lokale z-Achse ist gesperrt. Man kann zu Punkten snappen und mit Klick bestätigen. Dann wird der Modus wieder ausgeschaltet und die gewählte Zonenhöhe in das LineEdit übertragen, als hätte man es manuell eingetippt.

**Comment by Arombolosh** [comment]
Als ich würde Andreas letzten Post unterstüzen.
Kann mir dabei auch folgendes vorstellen.
`Es gibt eine Checkbox für "interactive Height" so dass die Zone immer mit der vordefinierten Höhe erstellt wird.`
Die Extrusionsrichtung könnten wir aus dem Objekt ermitteln auf dem Gezeichnet wird.
Bei der Gitterebene wäre das dann immer (0/0/1)
Bei einer Fläche immer die Richtung in die der Normalenvektor der Fläche zeigt. Damit kann man einfach und schnell an eine Zone auch seitliche eine anschließen. Damit wäre die Wahl der Richtung komplett vom Tisch.
