### ISSUE TITLE
Einfaches Ventil mit P-Regler für verschiedene Sollwerte

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#183]
Sowohl für Nahwärmenetze als auch Heizungsnetze wichtig.
Es müssen verschiedene Sollwerte möglich sein (vor allem bei Heizungsnetzen auch als LinearSpline bzw. Schedule):
- Solltemperatur
- Solltemperaturdifferenz 
- Massenstrom
- Druckdifferenz

**Comment by ghorwin** [comment]
Soll das eine generische Reglerkomponente sein, also:

Input =konfigurierbare Sensorgröße aus Modelkompenente X
Output = Regelgröße (analog, 0... MaxWert)

Parameter:
- Sollwert (Überschreitung)
- Sollwert (Unterschreitung, optional, nur für Hysterese)
- kP-Parameter
- max. Regelgröße (MaxWert als Absolutbetrag)

Man müsste für die unterschiedlichen Parametrierungen mal die Gleichungen aufschreiben.

**Comment by Labauke** [comment]
Das wäre sicher sinnvoll. Ist die Frage ob Regler nicht nur Teil von Netzwerken sind sondern auch so im Gebäude gebraucht werden?

Die Gleichungen kann ich gerne mal aufschreiben. 
Das mit der Hysterese verstehe ich nicht. Ein P-Regler hat eigentlich keine Hysterese...
