### ISSUE TITLE
PressureDifference als Ausgabe bei Netzwerken

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#188]
Wäre sehr hilfreich! Bisher gibt es nur InletNodePressure und OutletNodePressure.

Habe es selbst versucht allerdings wird es etwas komplizierter, da bei den hydraulische Ausgaben bisher keine abgeleiteten Größen existieren. Es wird direkt auf Referenzen der Solvergrößen zugegriffen.

**Comment by Labauke** [comment]
`PressureDifference` soll natürlich definiert sein als InletNodePressure - OutletNodePressure.
Optional zusätzlich noch `PressureLoss` = abs(InletNodePressure - OutletNodePressure)

**Comment by ghorwin** [comment]
Hier müsste man abwägen:
- die Ausgaben bringen Bequemlichkeit bei der Analyse
- jedes Netzwerkelement muss den dafür benötigen Speicher (2 double) vorhalten, ob die Ergebnisse gebraucht werden oder nicht
- die Liste der verfügbaren Ergebnisgrößen und möglichen Abhängigkeiten (für die Abhängigkeitsmatrix) wird länger, was die Initialisierungszeit verlängert (Skalierungsproblem) - da ja OutputFile-Objekte diese neuen Variablen referenzieren, muss man diese Ergebnisgrößen also allgemein veröffentlichen - je länger die Listen/Matrizen, umso länger sind jedwede Suchoperationen


Wenn man Inlet-/Outletpressures ausgiebt, kann man Druckverlust bzw. Druck-Unterschied nach der Simulation einfach (über ein Skript) berechnen. Könnten man das nicht so regeln und einfach ein geeignetes Python-Skript schreiben?

- TSV einlesen
- Spalten XXX.InletPressure und XXX.OutletPressure suchen (XXX muss gleich sein), dann diff berechnen und neue Spalten in neue TSV schreiben

(ca. 1 h Arbeit)

**Comment by Labauke** [comment]
Da würde ich vorsichtig widersprechen :)
Klar kann man ein Skript schreiben, im Moment kan ich das auch machen.
Aber der Druckverlust ist wirklich eine der grundlegensten Ausgaben die es gibt, das wird sich jeder Ingenieur anschauen wollen. Ist auf jeden Fall wichtiger als der Druck an einer einzelnen Stelle. Langfristig würde ich den auf jeden Fall ausgeben.

Wir geben doch auch Reynoldszahl und Viskosität aus...

**Comment by ghorwin** [comment]
Ok, gutes Argument. Ist also entschieden: Druckverlust wird ausgegeben (InletPressure - OutletPressure), aber die Absolutegröße dazu kann doch das PostProc bereits ausgeben (Manipulator "abs" einbauen).

**Comment by KnutKnudson** [comment]
Eine Frage von meiner Seite: ist der Druckverlust etwas, das alle Strömungselemente ausgeben (also auch Pumpen)? Worauf ich hinauswill ist, ob langfristig modellspezifische Individualausgaben für hydraulische Eigenschaften sinnvoll sind?

Am 18.03.2021 12:48 schrieb Andreas Nicolai ***@***.***>:

Ok, gutes Argument. Ist also entschieden: Druckverlust wird ausgegeben (InletPressure - OutletPressure), aber die Absolutegröße dazu kann doch das PostProc bereits ausgeben (Manipulator "abs" einbauen).

-

**Comment by Labauke** [comment]
Da er als Druckdifferenz definiert ist und nicht als Verlust, würde ich ihn für alle Elemente ausgeben.
Weitere spezielle Ausgaben für hydraulische Elemente fallen mir im Moment nicht ein.

**Comment by ghorwin** [comment]
Nach Hinzufügen der `PressureDifference` Ausgabe, bitte den Testfall `ThermoHydraulicNetworkSerialPipes.nandrad` entsprechend um InletPressure, OutletPressure und PressureDifference erweitern (dies ist gleichzeitig der "Ausgaben"-Testfall).
