### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#189]
Kann man irgendwie visuell machen ob schon eine Boundary Condition angegeben wurde?
![grafik](https://user-images.githubusercontent.com/75358827/111650456-991d9980-8805-11eb-8e1c-871118ce1892.png)
Auf Seite A habe ich schon eine Bedingung eingefügt und bei B nicht. sieht exakt gleich aus. Da es notwendig ist, mindestens eine Randbedingung hinzuzufügen damit die Component einen Haken bekommt, fände ich es praktisch wenn dies irgendwie visuell deutlich gemacht wird (Haken, Umrandung, dick geschrieben?) oder einfach der Name der Randbedingung angezeigt wird.

**Comment by ghorwin** [comment]
Visuell sieht man das im "Property mode" -> "Buildings" -> "Boundary Conditions".
