### ISSUE TITLE
VariableSubstitutions.txt schreibt nur hydraulische Ausgaben

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#190]
Es fehlen die thermischen Ausgaben in der mapping-Datei

Für mich würde es auch reichen nur eine mapping für name und id zu schreiben, also
NetworkElement(id=15)	detailled pipe_15

statt wie jetzt mit jeder quantity
NetworkElement(id=15).FluidMassFlux	detailled pipe_15.FluidMassFlux

**Comment by ghorwin** [comment]
Fehlende Ausgaben in `VariableSubstitutions.txt` liegt an fehlenden Zuweisungen an `QuantityDescription::m_displayName` in den `XXX::resultDescriptions()` Funktionen.

**Comment by ghorwin** [comment]
Nochmal drüber nachgedacht, es gäbe 2 Use-Cases:

**Option 1:** ich bin mit der Bezeichnung der eigentlichen Variablen einverstanden, möchte aber den Präfix, also die Objektidentifikation ersetzen

Tabelle:
`NetworkElement(id=15)` -> `Langes Verbindungsrohr`
`NetworkElement(id=16)` -> `Zuleitung zum Haus 17`

Dann würden mehrere Ausgaben wie folgt ersetzt werden:

`NetworkElement(id=15).FluidMassFlux` -> `Langes Verbindungsrohr.FluidMassFlux`
`NetworkElement(id=15).FluidTemperature` -> `Langes Verbindungsrohr.FluidTemperature`


**Option 2:**

...

**Comment by Labauke** [comment]
ich plädiere auch für Varaiante 1.

**Comment by ghorwin** [comment]
Ok, dann ist das entschieden:
Implementierung ist anzupassen, sodass jedes Modellobjekt bei der Erstellung von Ergebnisreferenzen auch gleichzeitig Substitutionskandidaten erzeugt. Um die bisherige Schnittstelle nicht aufzublähen würde ich eine weitere, abstrakte Schnittstelle hinzufügen:

```c++
AbstractModel::VariableReferenceSubstitutionMap(std::map<std::string, std::string> & varSubstMap) {
}
```
