### ISSUE TITLE
Interaktives Drehen von Objekten mit der Maus

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#191]
Es werden um die sichtbaren und selektierten Objekte Kreise gezogen einer liegt in jeder Ebene des aktuellen lokalen Koordinatensystems. 
Auf dem Kreis befindet sich ein Snapball den man anpassen kann. Sobald dieser angeklickt (Klick wird gehalten) wurde entstehen virtuelle Fangpunkte auf dem Kreis. Nur diese sie jetzt zum Fangen noch möglich. Alle anderen Fangpunkte "vergisst" das System bis der Mausklick wieder aufgehoben wird. Ein snappen an anderen Systeme ist daher nicht mehr möglich in diesem Moment. Die Unterteilungen müssen wir irgendwo einstellbar gestalten. Nachdem es eine Änderung des Balls gab wird diese Aktion auf die selektierten+sichtbaren Objekte ausgeführt.

**Comment by Arombolosh** [comment]
Auch zu Modi2 liegt das Bild ab

**Comment by ghorwin** [comment]
Modus 2 hab ich verstanden, dafür brauchen wir in der Tat einen neuen Modus, analog zu "PlaceVertex", da ja nun parallel zur Mausbewegung (ohne gedrückter Maustaste) was auf der Szene passiert.

Modus 1 wäre der "Standard Interaktive Rotationsmodus", der bei Auswahl "PropertyWidget -> EditGeometry -> Rotation" aktiv ist. 

Es gibt ein Problem. Wenn einer dieser Drehpunkte auf einer der lokalen Achsen liegt, dann ist der formal immer 2 Ebenen zugehörig - das wäre also eine Doppeldeutigkeit und müsste vermieden werden. Siehe folgender Screenshot:

![RotaMausModi1-localcoordsystem](https://github.com/ghorwin/SIM-VICUS/blob/master/doc/SIM-VICUS-Discussion/img/RotaMausModi1-localcoordsystem.png)

**Comment by ghorwin** [comment]
Hmm, sieht irgendwie nach Ausschlag aus :-)

**Comment by ghorwin** [comment]
Umsetzung:

- lokales Koordinatensystem hat eine Translation und Rotation;
- anfängliche Rotationsmatrix wird gespeichert, Rotationsachse wird ausgewählt (je nach Fangpunkt), als "Z-Achse und Drehachse" gesetzt und dazugehörige X und Y-Achsen ausgewählt; gedreht wird in der so entstandenen X-Y Ebene.

Beispiel Bild oben: am blauen Punkt wird angefasst; z-Achse wird Rotationsachse, y-Achse wird "Dreh-X-Achse", negative X-Achse wird "Dreh-Y-Achse"

- Vektor zur Maus wird in X-Y-Ebene projeziert
- Cosinus des Winkels zum "X"-Vektor wird bestimmt
- Cosinus des Winkels zum "Y"-Vektor wird bestimmt
