### ISSUE TITLE
Data structure for abstract control models

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#199]
We need a NANDRAD data structure to hold parameters of an abstract control block. Control models should be:

- digital, direct (feed through)
- digital, hysteretic: parameter "min time delay"
- analog, P-controller: parameter: kP, normalization range on s (implies clipping)
- analog, PI-controller: parameters: kP, kI, normalization range in s (implies clipping)

Flag: direct/indirect feedback; for indirect, controller state is adjusted only between integration steps
Flag: transient - if set, the controller result value will be approached slowly, see explanation below

Transient handling (only needed of indirect PI controller is not sufficient to decouple input and controller result):

1. controller computes target control value s_target
2. controller has internal state s_current
3. controller implements equation `s(t) = k_S*(s_target - s_current)`, by indirect integration (step completed) or by handing equation to integrator
4. k_S parameter determines how fast the output signal s_current follows the target signal. This mimics to some extend the PI control method.

**Comment by KnutKnudson** [comment]
Some ideas:
Obviously, we need two structures: an abstract controller and a hydraulic control valve. The valve is responsible for choosing control quantity and performing some pre-calulations. 
As an example consider Hauke's pdf document. In example 2 control quantity is the temperature difference between supply and return branch of the hydraulic component. Note, that current supply temperature is not available at the moment, when hydraulic equations are updated and must be estimated (Hauke suggests a predefined heat loss along the hydraulic component). It is preferable to capsulate such calculations into an independent model.
The abstract controller only should be responsible for calculating an abstract regulating value (from given control value) and performing integration for PI control.
