### ISSUE TITLE
PersonLoadsDatabas

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#201]
wenn ein neues internal load model erstellt wird, wird dieses direkt mit einem haken versehen. Selbst wenn der Zeitplan noch unvollständig ist und keine weiteren Eingaben gemacht wurden.

**Comment by miradoa** [comment]
und in der Schedule Database kann man unter Periods 'start date' nicht ganz lesen.

**Comment by miradoa** [comment]
selbe Situationen bei den anderen internal loads databases

**Comment by ghorwin** [comment]
Dirk, bitte mal die "isValid()" Implementierungen reviewen. Da ist ja schon einiges da, müsste nur nochmal geschaut werden, ob das so vollständig ist. Dann kann das Ticket geschlossen werden.
