### ISSUE TITLE
Geregelte natürliche Lüftung

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#206]
Folgende Regelmodelle brauchen wir für die natürliche Lüftung:

- Konstant (implementiert)
- Zeitplan (implementiert)
- Geregelt (mehrere Varianten)

## Geregelte Lüftungsrate nach DIN

- Basisluftwechsel nach Zeitplan oder konstant
- Erhöhter Tag/Nachtluftwechsel nach DIN Regeln
- Implementierungsoptionen: Zeit-Delay, Hysterese (Totband), P-Controller (lineare Interpolation), ...

**Comment by ghorwin** [comment]
Erhöhte Tag/Nachtlüftung kann auf verschiedene Weise parametriert werden. Im Solver wird berechnet:

```
p_control = (T_zone - T_limit(t) ) / DELTA_T
p_control = max(0, min(1, p_control) )
rate = basic_rate + p_control * ventilation_increase(t)
```
alternativ kann auch ein anderer Controller verwendet werden. 

Über den zetabhängigen T_limit(t) Parameter lassen sich Tag/Nachtlüftungszeiten und jeweilige Temperaturen abbilden. In Zeiten ohne erhöhte Lüftung setzt man T_limit(t) eben auf sehr hohe Werte (100°C oder so). ventilation_increase(t) ist die Erhöhung der Lüftungsrate gegenüber dem Grundluftwechsel (Differenz).

Damit ließen sich auch die DIN Lüftungsregeln umsetzen (oder?).

Wir bräuchten also 2 Schedule-Parameter:

-  `EnhancedVentilationTemperatureSchedule`
-  `EnhancedVentilationRateSchedule` (gibt die zu verwendende erhöhte Rate an)

```
ventilation_increase = EnhancedVentilationRateSchedule - VentilationRateSchedule
```

Im VICUS Datenmodell müssten wir aber ein Parametrierung nach DIN vorsehen, die dann für NANDRAD in die Schedules umgewandelt wird.

**Comment by Arombolosh** [comment]
Das Lüftungsmodell würde ich von EnergyPlus übernehmen.
Darin wird die Lüftung folgendermaßen beschrieben:
rate = zeitplan(t) * rateValue * (A + B*(Tzone - Tout) + C*vWind + D*vWind²)
Zusätzlich gibt es für die Kontrolle:
Innerhalb dieser Bereiche wird das Modell aktiviert:
min./max. Außenlufttemperatur
min./max. Innenlufttemperatur
deltaT (Innen-Außen)
max. Wind

EnergyPlus lässt aber mehrere Modelle für einen Raum zu. Daher müsste man bei uns wie du vorschlägst noch einen zweiten Zeitplan mit rannehmen. Dann kann der erste ohne Bedingungen ausgeführt werden und der zweite mit den Bedingungen.

Damit lassen sich dann auch die DIN Vorgaben umsetzen.

**Comment by ghorwin** [comment]
Das Modell scheint in der Art der Parametrierung wieder eine Mischung aus Bequemlichkeit/Ingenieursparametrierung und Notwendigkeit für den Solver sein.

Letztlich würde ich die Parametrierung im SIM-VICUS und NANDRAD trennen. In der Oberfläche kann man sich mit den Lüftungsmodellen und Parameteroptionen ja austoben wie man will, aber der Solver sollte so wenig Redundanz implementieren, wie möglich.

Bei dem Modell oben ist rateValue einfach ein Skalierungsfaktor für den Zeitplan und könnte damit in den Zeitplan mit rein - außer der Zeitplan wird auch noch für was anderes mitbenutzt. Aber auch das wäre eine Sache für die Oberfläche.

CvWind und DvWind^2 sind natürlich Faktoren für den Staudruck - aber hier ist mir die Trennung von rateValue und dem Faktor auch nicht ganz klar. Der effektive Luftwechsel hängt im Raum (unter Annahme perfekter Abdichtung der Räume untereinander) doch von:

- Geometrie: Fensterposition/größe/anzahl/Verteilung im Raum ab
- Raumgeometrie: Volumen, Höhe
- Temperaturverteilung im Raum/Stratifizierung
- Temperaturdifferenz zur Außenluft
- Staudruckschwankungshäufigkeit und Druckschwankungsamplitude ab

Die knifflige Frage ist hier: welche dieser Effekte sind unabhängig voneinander, oder sind alle so miteinander verknüpft, dass ich bei detaillierter Betrachtung doch für jeden Raum einzeln was definieren muss.

Und dann bleibt eigentlich nur als dynamische Einflussfaktoren:

- rein zeitabhängig: 
   + Winddruck/schwankungseffekte
   + Belegung/Nutzungszeiträume (und daraus resultierende Setpoints)
- zustandsabhängig: Temperaturdifferenz zur Außenseite (damit Raumlufttemperaturzustand)

Damit bleiben als dynamische Eingangsvariablen für das Modell übrig:

- Außenlufttemperatur (Zeitreihe)
- Winddruckeffekte (Zeitreihe der dadurch zusätzlich entstehenden Luftwechselrate)
- Belegung/Nutzungsanforderung (Zeitreihe für geplante Luftwechsel aus Fensterlüftung)
- Raumlufttemperatur (aus Raumbilanzmodell)

Der Rest sind statische Parameter.

In meinem Modellvorschlag fehlt soweit eigentlich nur der Einfluss des Staudrucks bzw. Wind und damit Staudruckschwankungen. 

Vielleicht sollten wir das Modell inkrementell parametrieren:

Variante 1: Standardmodell
-  ohne Wind, ohne Temperaturstratifizierungseffekt, nur geplanter Grundluftwechsel und erhöhter Luftwechsel (und der Ingenieur muss dann wie in der DIN begründen, wie er das bewerkstelligen will.... Elektrolüfter vor das Fenster etc. :-)

Variante 2: Realklimamodell
- mit Wind, mit Temperaturdifferenzabhängigkeit, Luftwechsel ergibt sich aus vereinfachter Geometriebetrachtung: Fenster zu (Grundluftwechsel z.B. aus Leckage oder eingebauter Fenster-Spalt-Lüftung), Kipplüftung, Stoßlüftung; Zeitplan gibt dann den Fensterzustand an bzw. die grundsätzliche Möglichkeit für den Nutzer, den Fensterzustand zu ändern (von zu auf Stoßlüftung).


Variante 1 brauchen wir auf jeden Fall für die DIN, und das müsste mit dem Modellvorschlag von mir oben umsetzbar sein. Für Variante 2 müsste sich jemand nochmal ein entsprechendes Buch zur Lüftung schnappen und mal eine kleine Studie dazu machen.
