### ISSUE TITLE
Zone erstellen über Koordinaten

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#207]
Wenn ich eine Zone über Koordinateneingabe erstellen möchte, fixiere ich mir die jeweilige Achse in deren Richtung ich den nächsten Punkt eintragen will. Wenn ich dann einen Wert eingebe, wird dieser jedoch immer auf den x-Wert addiert. Selbst wenn die y- oder die z-Achse fixiert sind. Wie kann ich denn die Werte für diese beiden Richtungen eingeben?

**Comment by ghorwin** [comment]
Ist ein Bug, die eingegebene Zahl sollte für die gesperrte Achse gelten.
