### ISSUE TITLE
Akzeptieren Fehlermeldung

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#208]
Erstelle ich eine Zone und gebe einen Buchstaben als Koodinate ein oder eine Zahl, die das Polygon ungültig macht, kommt die Fehlermeldung. Diese geht nur durch anklicken des 'OK'-Buttons weg. Wenn ich mit Enter bestätige, muss ich sehr oft bestätigen bis sie weg geht. Kann man das fixen?

**Comment by ghorwin** [comment]
Ist ein Bug bei der Fehlerbehandlung.
