### ISSUE TITLE
Anzeige gesperrte Achse

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#214]
![falscheAchse](https://user-images.githubusercontent.com/75358827/115242404-1e0c1380-a122-11eb-8c64-e1f4d3e690a0.png)

die gesperrten Achsen werden verkehrtherum angezeigt. Sperre ich y, kann ich mich nur auch x bewegen und umgekehrt. Die Eingabe der Werte passt, also ist nur die visuelle Darstellung vertauscht.

**Comment by ghorwin** [comment]
![Bildschirmfoto von 2021-04-20 19-46-46](https://user-images.githubusercontent.com/6892676/115441479-3018af80-a211-11eb-8521-d42eaf6191e8.png)

Für die Achsensperrung gilt immer das lokale Koordinatensystem (siehe Screenshot oben).
