### ISSUE TITLE
Löschen von Räumen

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#216]
![grafik](https://user-images.githubusercontent.com/75358827/115250796-354eff00-a12a-11eb-9f21-9a6081cccb53.png)

lösche ich Räume etc. werden diese in der Darstellung gelöscht, werden aber immernoch in der Geometrieauflistung gelistet, auch nach Neustarten. (siehe Bild)
Für einen guten Überblick wäre es schön, wenn sie auch da gelöscht werden.

**Comment by ghorwin** [comment]
Regel dafür: ein markierter Raum wird mit gelöscht, wenn nach dem Löschvorgang keine sichtbaren/unsichtbaren Oberflächen des Raumes verbleiben
