### ISSUE TITLE
Flächenheizungsmodell

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#229]
Es werden zwei unterschiedliche Flächenheizungsmodelle (ohne Netzwerk)  benötigt:

## Ideales Flächenheizungsmodell

Bei diesem Modell wird ausgehend von einem Regelsignal eine Wärmemenge in eine beheizte Konstruktionsschicht eingeführt. Das wäre z.B. anwendbar bei elektrischen Heizrastern oder bei idealer Auslegung einer Heizung. Die Details der Wärmeübertragung werden hier nicht betrachtet.

Regelgröße ist ein Thermostatkontroll-Signal -> `HeatingControlValue`, welches z.B. vom ThermostatModell geliefert wird.

Es gibt eine nominale/maximale Heizlast. "Nominal" bei hysteretischen On/Off-Thermostaten. "Maximal" bei P-Controllern. Für die Konfiguration des Kontrollers, siehe ThermostatModell.

Parameterblock: `IdealSurfaceHeatingModels` statt `IdealFloorHeatingModels`, weil man das ja auch für Wandflächenheizungen verwenden kann.

```xml
<IdealSurfaceHeatingModels>
	<IdealSurfaceHeatingModel id="4001">
		<!-- Identify the zone that these heated constructions are controlled by -->
		<ThermostatZoneID>12</ThermostatZoneID>
		<ConstructionObjectList>Heated floor constructions</ConstructionObjectList>
		<IBK:Parameter name="MaxHeatingPowerPerArea" unit="W/m2">50</IBK:Parameter>
	</IdealSurfaceHeatingModel>
</IdealSurfaceHeatingModels>
```

## Ideales Rohrregistermodell

Hier wird ein durchströmtes Rohrregister modelliert. Dabei wird die physikalische Wärmeübergabe von Medium im Rohr an die Umgebung in Abhängigkeit von Vorlauftemperatur, Umgebungstemperatur (=Temperatur der Konstruktionsschicht) und Massestrom berechnet.

Das Modell ist in sofern "ideal", als dass die Wärmeabgabe im Rohrregister keinen Einfluss auf die Vorlauftemperatur hat.

Geregelt wird der Massestrom. Die Vorlauftemperatur ist entweder konstant ("modelType=Constant") oder als Zeitplan vorgegeben ("modelType=Scheduled").

Je nach `HeatingControlValue` vom Thermostat wird der Massestrom geregelt. Wiederum gibt es einen nominalen/maximalen Wert für den Massestrom. 

```xml
<IdealPipeRegisterModels>
	<IdealPipeRegisterModel id="4001" modelType="Constant">
		<!-- Identify the zone that these heated constructions are controlled by -->
		<ThermostatZoneID>12</ThermostatZoneID>
		<ConstructionObjectList>Heated floor constructions</ConstructionObjectList>
		<IBK:Parameter name="SupplyTemperature" unit="C">30</IBK:Parameter>
		<IBK:Parameter name="MaxMassFlow" unit="kg/s">0.2</IBK:Parameter>
		<!-- TODO : andere Parameter für Rohrregister -->
	</IdealPipeRegisterModel>
</IdealPipeRegisterModelss>
```

**Comment by KnutKnudson** [comment]
Ideales Flächenheizungsmodell:
Es müsste geklärt werden, wie die Zuordnung des Heizelements zu der geregelten Zone erfolgt. Soll das faktisch aus der Geometrie 'erraten' werden? 
Andererseits könnten ja andere Fälle interessant sein, zum Beispiel wenn die Vorgabe einer Schichttemperatur gewünscht ist (darüber wurde schonmkal in einem der ersten Meetings im FMI4BIM diskutiert). Dies ließe sich umsetzen, indem die Ideale Leistung nach einer SChichttempertaur geregelt wird. Solche Anwendungen sind nur möglich, wenn man Soll- und Regelgröße frei lässt.

Von daher zur Diskussion:
Sollten Stelltemperatur und SOlltempertaur nicht zusätzliche EIngaben sein?
