### ISSUE TITLE
Unvollständige Inputs im FMI Dialog

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#234]
In dem FMI-Dialog werden optionale Größen (Inputs) angezeigt, die nicht vollständig mit Einheiten befüllt werden, konkret ist dies die Größe 'WindowSolarRadiationFluxSum' in dem FMU-Beispiel 'data/fmu/IntensityControlledCooling/CooledZone.nandrad'. DIeser Effekt tritt auf, wenn zu einer InputReference in der 'input_reference.txt' keine anständige Ergebnisbeschreibung (QuantityDescription) gefunden wird.

Folgendes geschieht: in der Initialisierung erzeugt der NandradSolver die Datei 'input_reference_list.txt', die !!!alle!!! (optionale und obligatorische) InputReferences enthält. Optionale InputReferences müssen aber nicht zwingend vorhanden sein. So kann es also passieren, dass keine Ergebnisgröße gefunden wird, damit keine vollständige Objektbeschreibung gefunden wird und fehlende Informationen einfach nicht eingetragen werden. Genau das ist der Fall, wenn keine Fenster vorhanden sind, aber dennoch eine Außenkonstruktion simuliert wird. Das Modell, welches die optionale Größe 'WindowSolarRadiationFluxSum' berechnen soll, wird gar nicht erst erzeugt, und die Referenz verbleibt unbefüllt (und wird im Solver ignoriert).

Nun, zu sagen, dass nur befüllte (also ersetzbare) InputReferences in der 'input_reference_list.txt' erscheinen sollen, schließt ja die Möglichkeit aus, später durch FMU-Import eventuell noch ein paar Dinge nachzutragen (so zum Beispiel einen 'WindowSolarRadiationFluxSum'). Die einzige Lösung für das Problem, die ich derzeit sehe, ist, dass der Abgleich einer Referenzenbeschreibung nicht an die tatsächliche Exitsenz einer passenden Ergebnisgröße gebunden sein darf.

Ideen gesucht.

**Comment by ghorwin** [comment]
Einfachste Variante (wenn auch mit Pflegeaufwand verbunden):

- für alle optionalen InputReferenzen wird ein Verzeichnis im NandradFMUGenerator hinterlegt, welches Variablenname mit Einheit und Beschreibung verknüpft

```c++
// in der Initialisierung
m_variableInfoMap["Zone.WindowSolarRadiationFluxSum"] = std::make_pair("W", "Sum of solar radiation loads through all windows");
```
