### ISSUE TITLE
FMU Generator: Doppeltes Mapping: FMIVar -> {NANDRADVar1, NANDRADVar2} in Oberfläche unterstützen

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#238]
Es sollte möglich sein, für unterschiedliche NANDRAD-Variablen den gleichen FMI-Variablennamen festzulegen, unter folgenden Bedingungen:

- Variable muss eine FMU-Input-Variable sein
- alle NANDRAD Variablen müssen die gleiche Einheit haben

Dies sollte beim Speichern/Generieren der FMU geprüft werden. 

Doppelklick auf die Tabellenzelle mit dem FMI-Variablen-Namen sollte eine Umbenennung ermöglichen.

**Comment by KnutKnudson** [comment]
Die Verwendung der Qt-Oberfläche unterliegt einem generellen Umbau und kann erstmal zeitnah nicht weiter fortgesetzt werden. Bitte um Verschiebung, bis endlich mal Zeit ist, mich mit der Oberflächenprogrammierung befassen zu können.
