### ISSUE TITLE
NANDRAD FMI Interface: FMI Input-Var -> mehrere NANDRAD Variablen unterstützen

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#239]
Das FMI-Interface im NANDRAD sollte bei der Erstellung von ResultRefs auf doppelte Verwendung der assoziierten FMI-Variablen prüfen und je FMI-Variable nur eine Speicheradresse befüllen und diese dann für alle zugeordneten NANDRAD-Variablen ausliefern.

**Comment by KnutKnudson** [comment]
Bisher war die Annahme, die Variablen-Ids sind bindend. Was soll also geschehen, wenn zwei FMI-Variablen den gleichen Namen tragen, aber mit unterschiedlichen Ids ausgeliefert werden? Meiner ANsicht nach ist dies ein Fehler.
