### ISSUE TITLE
Gleichnamige vektorwertige/skalarwertige Ergebnisgrößen in Sammelmodellen und Wand/Zone

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#240]
Es fiel mir bei Ausgaben auf. Zwei unterschiedliche Typen (z.B. Wand und Modell) können gleichnamige Ergebnisgrößen zur Referenzierung anbieten. Wenn Modelle auf mehreren Elementen (Wand oder Zone) arbeiten und dabei vektorwertige Ergebnisgrößen verwenden, so stimmt ihre Referenz und id-Nummer mit dem skalaren Modell überein, es wird also Gleichwertigkeit unterstellt. Erfolgt die Referenz nun auf die wand- oder zonenspezifische skalare Ausgabegröße, so kann sich das berechnende Modell 'vordrängeln' und seine vektorwertige Ergebnisgröße anbieten.

Die Ursache hierfür ist im Vergleichsoperator '<' der QuantityDescription zu suchen, welcher nach Referenztyp, Id und Ergebnisvariablennamen vergleicht, das Attribut 'vektorwertig' oder 'skalar' aber ignoriert. Genau dieser Vergleich wird nämlich angewendet, um beim Auflösen der Referenzen das zuständige Modell ausfindig zu machen (siehe Zeile 1824 in 'NandradModel.cpp'). Dies ist sogar inhaltlich nicht ganz falsch, weil die Größen in diesem Fall tatsächlich identisch sein sollten. Dennoch einmal nachgefragt:

Darf eine zonen- oder wandspezifische Last als Ergebnisgröße denselben Namen tragen wie ein Modell, das genau vektorwertig diese Größe für mehrer Zonen oder Wände berechnet?

Oder sollte unterschieden werden, ob via Index ein Zugriff auf eine vektorwertige Größe/ohne Index auf eine skalare Größe erfolgt? Das Problem besteht hier in der unterschiedlichen Handhabung von Vektorindizes in den Strukturen QuantityDescription und InputReference. Der Name der InputReference enthält den Vektorindex immer als Zusatzinformation im Namen, während die QuantityDescription alle möglichen Indizes als indexKeys gesammelt listet. Für eine korrekte Suche müsste der Vergleichsoperator in der 'QuantityDescription' soweit nachgerüstet werden, dass er einzelne Indexkey-Anfragen erkennen kann.

**Comment by ghorwin** [comment]
Der Variablengleichheitstest sollte tatsächlich die Eigenschaft "Vektorwertig" oder "skalar" beinhalten. Allerdings sehe ich das als Design-Problem an, wenn ein Modellschreiber eine bereits anderswo verwendete Variable benutzt, und dabei den vektorwertig/skalar Typ ändert.

Besser wäre es in jedem Fall, einen unterschiedlichen Variablennamen zu verwenden, da dies auch die Fehlerquellen in der Anwendung reduziert.

Das muss auch nicht im Quelltext geprüft werden, sondern kann beim Schreiben der Dokumentation und der Überblickstabelle über alle Ausgaben erfolgen (Liste mit Modelltypen und deren Ausgaben).
