### ISSUE TITLE
Add ControllerType `ThermostatValue` for HydraulicNetworkControlElement

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#243]
`HydraulicNetworkControlElement` bekommt eine neue `ControlledProperty` vom Typ `CP_Thermostat` und eine Referenz auf eine Zone mit Thermostat.

`HNPipeElement` bekommt eine Referenz auf das ihm zugeordnete `TNSimplePipeElement`.

`TNSimplePipeElement` implementiert `inputReferences()` und erfragt Thermostat.

`TNSimplePipeElement::zetaControlled()` bekommt eine Kontroller-Implementierung, welche das Thermostat-Signal in einen zeta-Wert verwandelt.

`HNPipeElement::systemFunction()` holt sich diesen zeta-Wert.

**Comment by KnutKnudson** [comment]
Die Impelmentierung von 'inputReferences' setzt eine Vererbung des SImplePipeModel von AbstractStateDependency voraus - die gesamte Modell und Verknüpfungslogik landet also dann gemischt im  ThermalNetworkModel und teilweise in den konkreten Implementierungen.
Das kann nicht im Sinne des Erfinders sein.
Eventuell ist die direkte Mitgabe des Thermostats als Referenz eine mögliche Lösung.

**Comment by KnutKnudson** [comment]
Oder das Modell bekommt gleich eine optionale Kontrollwertreferenz, welche passend durch das ThermalNetworkBalanceModel initialisiert und aufgelöst wird.

**Comment by ghorwin** [comment]
Ach so, hab ich vergessen zu erwähnen. Die Funktion `inputReferences()` wird von `ThermalNetworkBalanceModel::inputReferences()` durchgereicht, siehe `TNHeatPumpIdealCarnot::inputReferences()`.

**Comment by KnutKnudson** [comment]
Meinetwegen kann man dies über inputRfereences lösen. Allerdings ist das TN SimplePipeModel nach wie vor der falsche Ort hierfür. Die Verwaltung sollte vollständig über das HydraulicNetworkModel erfolgen (was das richtige Modell in der Graphenstruktur ist). 
Damit die gesamte Implementierungs ins HNPipeElement wandern.

**Comment by KnutKnudson** [comment]
Außerdem noch eine Frage: wenn das ThermalNetworkBalanceModel zuständig ist, Referenzen für Fluidkontrollelemente aufzulösen - wie kann man sicherstellen, dass der Modellgraph dann richtig aufgebaut wird?
Eiegentlich bestehen die ABhängigkeiten ja bereits bei der hydraulichen Berechnung (im HydraulicNetworkModel) und nicht erst im nachgelagerten ThermalNetworkBlanaceModel.
