### ISSUE TITLE
Fehler beim verschieben

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#246]
Beim Verschieben  (mittlere Maustaste gedrückt gehalten) springt, wenn man das Gebäude von der Vogelperspektive sieht und nach unten schiebt, die Ansicht und damit auch das Gebäude.
Eigentlich sollte es wenn man über den Rand geht nur der Mauszeiger springen. Das funktioniert auch beim Seitwärtsschieben.
Aber bei hoch und runterschieben funktioniert es nicht.
Testfall Sichtlinie fast parallel zu x-y-Achse und dann in z-Richtung verschieben.
Man kommt nicht voran.

**Comment by ghorwin** [comment]
It's a feature, not a bug! :-) beim "Umsetzen" des Mauscursors wird das "Panning" neu gestartet. Da beim runter-scrollen der Cursor dann oben in der Luft hängt und hinten die Far-Ebene trifft, verschiebt man dann entsprechend langsamer.

Frage: was ist das gewünschte Verhalten? Gleiche Pan-Geschwindigkeit, auch wenn nach dem "Umsetzen", der Mauscursor nicht mehr über dem Objekt bleibt?

**Comment by ghorwin** [comment]
Problem erkannt:

Panning startet nicht, wenn kein Objekt getroffen wurde:

```c++
if (!pickObject.m_candidates.empty()) {
 // pan
}
```

In diesem Fall sollte aber die "Backplane" oder ggfs. eine virtuelle Ebene getroffen werden. Beim Umsetzen des Cursors an den oberen Bildschirmrand passiert das eben recht häufig (bei paralleler Ansicht über dem Boden), dass im "Himmel" nichts getroffen wird.

Frage bleibt: wie definiert man denn diese virtuelle Ebene, die man dann trifft?
