### ISSUE TITLE
HydraulicNetworkControlElement -> Aufteilen

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#247]
Aktuell kombiniert der Block:

```xml
<ControlElements>
	<HydraulicNetworkControlElement id="1" controlledProperty="ThermostatValue">
		<ThermostatZoneId>1</ThermostatZoneId>
		<MaximumControllerResultValue>1e+08</MaximumControllerResultValue>
	</HydraulicNetworkControlElement>
</ControlElements>
```

sowohl die häufiger verwendbare Kontroller-Konfiguration _und_ die nur einmal verwendbare Thermostat-Zonen-Id. Letzteres funktioniert gut, wenn ich mehrere Fußbodenheizungen nach dem gleichen Thermostat regeln will. Wenn ich aber mehrere Fußbodenheizungsfeldern jeweils nach eigenen Thermostaten regeln will, muss ich den `HydraulicNetworkControlElement` für jede Zone kopieren.

Alternative wäre, die `ThermostatZoneId` in das Element (sprich, die verbaute Fußbodenheizung selbst) zu übernehmen.

Also statt:

```xml
<HydraulicNetworkElement id="2" inletNodeId="0" outletNodeId="101" componentId="2" pipePropertiesId="9" controlElementId="1" displayName="surface heating">
	<IBK:Parameter name="Length" unit="m">100</IBK:Parameter>
	<HydraulicNetworkHeatExchange modelType="TemperatureConstructionLayer">
		<ConstructionInstanceId>3001</ConstructionInstanceId>
	</HydraulicNetworkHeatExchange>
</HydraulicNetworkElement>
```

macht man

```xml
<HydraulicNetworkElement id="2" inletNodeId="0" outletNodeId="101" componentId="2" pipePropertiesId="9" displayName="surface heating">
	<IBK:Parameter name="Length" unit="m">100</IBK:Parameter>
	<HydraulicNetworkHeatExchange modelType="TemperatureConstructionLayer">
		<ConstructionInstanceId>3001</ConstructionInstanceId>
	</HydraulicNetworkHeatExchange>
	<HydraulicNetworkFlowController controllerId="1">
		<ThermostatZoneId>1</ThermostatZoneId>
	</HydraulicNetworkFlowController>
</HydraulicNetworkElement>
```

Lohnt sich so ein Umbau?

**Comment by KnutKnudson** [comment]
Ich bin dafür. Eine Hand geht nach oben.

**Comment by Labauke** [comment]
Für die Quartiersnetzwerke habe ich im Moment keinen Fall im Blick, bei dem etwas ähnliches gebraucht wird.
Inwiefern das beim Gebäude Sinn macht kann ich nicht einschätzen.

**Comment by ghorwin** [comment]
Entschieden: solange es nur den Anwendungsfall mit dem Zonen-Thermostat gibt, bleibt es beim aktuellen Design.
Begründung:

- Anwendungsfall: mehrere Fußbodenheizflächen geregelt nach dem gleichen Thermostat ist doch recht häufig.
- Anwendungsfall: Fußbodenfläche je Thermostat bedingt eine Duplikation des Kontroller-Definitionsblocks (normalerweise 3 Zeilen in der Projektdatei ohne optionale Max-Wert-Begrenzung); Einbettung in das hydraulische Element wären auch 3 Zeilen, in Summe also nichts an Projektdateiplatz gespart.
