### ISSUE TITLE
Bug Zone erstellen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#250]
Vorgehen:

Zone Add Widget öffnen (Zone erstellen)
Am Floor Polygon ein paar Punkte abklicken (dabei eine invalid Linie durch Überschneidung herstellen) dann einfach ESC drücken
Dialog ist weg aber die Linie ist noch da.
Zudem ist der Add Button auch noch eingedrückt

**Comment by Arombolosh** [comment]
aso ich denk ich hab zwischendurch den fokus auf den menübaum gesetzt dadurch wurde die szene nicht aktualisiert

**Comment by ghorwin** [comment]
Reproduzierbar: Zone zeichnen beginnen, dann Auswahl eines Knotens ändern -> die darauf ausgeführte Undo-Action führt nicht zum korrekten Zurücksetzen des Modus (da fehlt schlicht die Undo-Action Behandlung).
