### ISSUE TITLE
not working select button in ZoneTemplate

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#261]
Auswahlbutton (...) öffnet mögliche Templates, wenn ich eins anwähle und select klicke bleibt jedoch das vorheringe erhalten. Auswechseln geht also im Moment nur über Löschen und neu anwählen.

**Comment by ghorwin** [comment]
Funktioniert bei mir. Ein zugewiesenes Zonentemplate in der Liste auswählen, auf "Exchange..." klicken, neues auswählen und mit Select-bestätigen -> Farbe und Zuweisung ändert sich.

**Comment by miradoa** [comment]
Ja das hatte Dirk dann schon behoben.
