### ISSUE TITLE
Ideal Heating/ Cooling without Thermostat

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#262]
Es muss ein Thermostat verwendet werden. Dies ist aber nicht ersichtlich. Wird erst als Fehler angezeigt wenn ich die Simulation (nandrad) starte

**Comment by ghorwin** [comment]
Ja, das ist korrekt. Ein ideales Heizungsmodell braucht immer ein ZoneThermostat.

**Comment by miradoa** [comment]
Wäre gut wenn das direkt bei der Erstellung der Zone ersichtlich ist, oder IdealHeatin/Cooling nur einen Haken bekommt wenn auch ein Thermostat mit eingetragen wird.
