### ISSUE TITLE
IdealHeaterCooler: MixedReturnTemperature

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#263]
Die Variable 'MixedReturnTemperature' lässt die Vermischung des originalen Netzstranges mit einem Bypass zu und berechnet die dazu gemischte Auslasstemperatur - bei Vorgabe eines Setpointwertes für den Massestrom.

Wird kein Setpointwert gesetzt, so wird die 'MixedReturnTemperature' exakt mit der Vorlauftemperatur gleichgesetzt. Eigentlich würde man ja vermuten, dass in diesem Fall kein Bypass existiert, die 'MixedReturnTemperature' also tatsächlich der Rücklauftemperatur aus dem Netzwerk entspricht.

Fehler oder kein Fehler, das ist die Frage?

**Comment by ghorwin** [comment]
Ist aktuell ein Feature, weil das Setzen des `MassFluxSetPoint` beim Stand-alone-Betrieb (d.h. nur Setzen der Vorlauftemperatur) in der Regel nicht geschieht.

Also, es gibt für den IdealHeaterCooler zwei Anwendungsfälle:
a) Stand-alone-Betrieb (z.B. im Quartiersnetzwerk, oder zu Validierungsfällen); hier wird wirklich nur die Vorlauftemperatur erzwungen und Rücklauftemperatur ist eigentlich egal
b) Betrieb mit FMI-Schnittstelle - hier sollte der `MassFluxSetPoint` gegeben sein.

Schick wäre natürlich, wenn nur im Anwendungsfall b) die Ergebnisgröße `MixedReturnTemperature` zur Verfügung steht. Aber das gibt das Framework nicht her - man muss die Ergebnisgrößen veröffentlichen, *bevor* man mittels `setInputRefs()` weiß, welche Variablen einem zur Verfügung stehen.
