### ISSUE TITLE
Schedule properties Periods

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#265]
Es kann eine Periode erstellt werden, jedoch kann die nicht umbenannt werden. Wäre praktisch wenn das mit möglich wäre und das erstellte Intervall nicht immer nur "newInterval" heißt. 
Außerdem ist die erste Spalte zu schmal (start date ist nicht ganz lesbar).

**Comment by miradoa** [comment]
Das erste Intervall kann umbenannt, aber das start date nicht verändert werden

**Comment by Arombolosh** [comment]
erledigt
