### ISSUE TITLE
Cancel Schedule Database

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#266]
Wenn ich einen Schedule für ein Template ausgewählt habe, dann jedoch nochmal ins Auswahlmenü gehe und auf Cancel klicke, wird der bereits eingetragene Zeitplan im vorheringen Fenster (Light, person loads, database,..) wieder rausgelöscht.
Wäre nutzerfreundlicher wenn einfach der vorher ausgewählte Zeitplan stehen bleibt. 
Ist bei den anderen Fenstern ja auch schon so, ich weiß nur nicht wo das im Code zufinden ist, sonst hätte ich es selbst gemacht...

**Comment by Arombolosh** [comment]
is behoben bitte testen

**Comment by miradoa** [comment]
ja passt!
