### ISSUE TITLE
Smart Select

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#267]
Anklicken von vielen Objekten mit gleichen Eigenschaften:

Im Smart Select werden folgende Oberkategorien ausgewählt

* Components
  * Wand
    * Außenwände (alle folgenden sind die Types in der Component), diese Liste ist sozusagen statisch
      * jetzt werden in dieser Ebene alle Componenten diese Types aufgelistet die im aktuell sichtbaren Modell verbaut sind
      * Bsp. "AW01"
      * Bsp. "AW02"
    * Innenwände
  * Fenster
  * Decken
  * Böden
  * Dächer
* Thermal Conditions
  * Außen
  * Adiabat
  * Erdberührt
  * Innen
* Shading (hier werden alle Verschattungselemente selektiert. also nur die extern erzeugten. NICHT die Fensterverschattung)

So wenn ich dafür ein Template habe kann ich schonmal weiter machen

**Comment by ghorwin** [comment]
Umsetzungskonzept:

- es gibt zwei Layouts: oben ein horizontalLayout mit den "Brotkrumen" und darunter ein Grid-Layout, welches dynamisch mit Schaltflächen befüllt wird
- je nach Hierarchieebene wird das Gridlayout mit Buttons befüllt
- ein Klick auf einen Button fügt diesen der Brotkrumenleiste hinzu (entfernt alle eventuell späteren Auswahlbuttons) und aktualisiert das Grid
