### ISSUE TITLE
loss of component while nandrad simulation

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#273]
![grafik](https://user-images.githubusercontent.com/75358827/123622541-a129a400-d80c-11eb-84ee-d4bcdb2aab0d.png)

ich befinde mich in dem auf dem Bild abgebildeten Modus und hatte components zugewiesen. Dann habe ich eine Nandrad-Simulation ausgeführt und all meine zugewiesenen Components sind verloren..
mit strZ bekomme ich sie wieder, aber eigentlich sollten sie ja bestehen bleiben.

**Comment by ghorwin** [comment]
@Dirk: das lokale Projekt im SimulationsStartDialog darf bei der Transformation zu NANDRAD nicht gelöscht werden oder sonstwie zu Datenverlust führen. Empfehlung: in der NANDRAD-Export-Funktion nur lesend auf Projektdaten zugreifen.

**Comment by ghorwin** [comment]
@miradoa: der Verlust der Componentenzuweisungen muss einen anderen Grund als die Simulation haben - zumindest im aktuellen Quelltext scheint es keine Möglichkeit zu geben, die Komponentenzuweisungen zu löschen.

Lässt sich das Verhalten reproduzieren?

**Comment by miradoa** [comment]
@ghorwin ja, habe nochmal ein neues Projekt angelegt und es passiert das gleiche.

**Comment by ghorwin** [comment]
Ja, jetzt seh ich es auch. Wird gleich behoben
