### ISSUE TITLE
Buttons vor/zurück beim Schedule austauschen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#274]
Die Buttons vor und zurück (derzeit Undo/Redo) bei den umschalten von einen Tageszyklus auf den anderen austauschen 
Button zurück
<-- 

Button vor (es müssen schon weitere Tageszyklen existieren)
-->

Button einfügen (Es darf noch kein weitere Tageszyklus nach dem aktuellen vorhanden sein)
+

**Comment by hirseboy** [comment]
done
