### ISSUE TITLE
Rect erstellen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#275]
Das Rect ist eigentlich kein Rechteck sonder eher ein Parallelogramm. Hier sollten wir die mal einen neuen Namen definieren.

**Comment by ghorwin** [comment]
Oder tatsächlich die Orthogonalität durchsetzen. Sollte ja einfach sein:
- Nach dem Absetzen des 2. Punkts wird bei jeder Mausbewegung zunächst mit aktueller Position des LKS die Ebene berechnet
- dann wird in dieser Ebene eine Snaplinie durch den letzten Punkt definiert
- die LKS-Position auf diese Snaplinie projiziert (ohne dabei die Linie neu zu berechnen)

Für Parallelogramme kann man einen eigenen Button machen?
