### ISSUE TITLE
Schedule Scale

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#280]
![grafik](https://user-images.githubusercontent.com/75358827/124487328-dc991500-ddae-11eb-9b02-dc8673f11c2b.png)

Skala anpassen. Wenn es anteilig dargestellt wird ist eine Skala bis 1 (100%)  ausreichend. Tatsächliche Werte werden dann in der airchangerate angezeigt.

**Comment by ghorwin** [comment]
Vorschlag: Untere Scale immer = 0, obere = 20 % über aktuellem Maximalwert.
