### ISSUE TITLE
Component Database text not readable

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#282]
![grafik](https://user-images.githubusercontent.com/75358827/125095422-6f4df280-e0d4-11eb-8b18-e642550a4cc5.png)

Untere Teil rechts im Construction-Reiter nicht lesbar. (Construction has active layer(s....????))

**Comment by ghorwin** [comment]
Man kann das Eigenschaftenfenster mit dem Trenner zwischen Tabelle und Eigenschaftsfenster vergrößern. Ich werde aber die Größeneinstellungen nochmal anpassen.
