### ISSUE TITLE
VICUS Datenmodell und Anzeige stimmt nicht überein

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#284]
ein Zeitplan mit folgenden Definitionen:

00:00   10
20:00   20
23:00   20

Die Tabelle zeigt bei 10:00 auch ein Wert von 10 das ist natürlich falsch

**Comment by ghorwin** [comment]
Wieso ist das falsch?

**Comment by ghorwin** [comment]
Die Tabelle ist nur für die Eingabe von stündlichen Werten gedacht. Bei linear interpolierten Werten müsste man eigentlich ein anderes Widget verwenden, welches nur die Stützstellen erfasst und anzeigt (ähnlich wie das Perioden-Widget) und daneben ein Diagramm anzeigt. Da die meisten Zeitpläne aber "konstant" sind, passt das für's Erste so.
