### ISSUE TITLE
Netzwerkausgaben direkt nach Simulationsende umbenennen

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#286]
Beim ersten halbwegs praxisnahen Auswerten der Netzwerkausgaben habe ich folgendes Problem:

Im Moment können die Nandrad Namen wie "NetworkElement(id=32).FluidMassFlux" im PostProc durch Auswahl der richtigen objectref_substitutions.txt ersetzt werden. Das muss man aber für jedes Nandrad-Projekt machen und erweist sich als ziemlich nervig wenn man schnell mal 2-3 Varianten vergleicht die leicht unterschiedliche Namen oder Elementanzahl haben. Vor allem weiß man nie welche substitution man gerade gewählt hat und das führt ganz schnell zu Missverständnissen bei der Auswertung.

Wie können wir das Problem lösen? 
Am einfachsten wäre es vermutlich am Ende der Simulation ein Skript laufen zu lassen das die Namen entsprechend ändert. Ist dann halt blöd wenn man während der Simulation schon auswertet...

Gibt es eine andere Möglichkeit?
Vielleicht könnte PostProc auch direkt default-mäßig die objectref_substitutions.txt verwenden, wenn diese vorhanden ist?

**Comment by Labauke** [comment]
Ich nutze im Moment ein Pythonskript, hat also keine so hohe Priorität

**Comment by Labauke** [comment]
Das ist ja genau das Problem.
Ich vergleiche verschiedene NANDRAD Projekte in einer p2-Session. Die Nandrad Projekte sind aber leicht unterschiedlich aufgebaut. Die ObjectRef_substitutions passt also nicht für alle und die Namen werden dann falsch angezeigt

**Comment by ghorwin** [comment]
Ok, das ist eine andere Anforderung. Hier wären ja Quelldatei-spezifische Substitutionslisten notwendig.

**Comment by ghorwin** [comment]
--> Feature-Request im PostProc angelegt https://baukli01.arch.tu-dresden.de/PostProc2/ticket/254#ticket

**Comment by ghorwin** [comment]
Nein, von derartigen "mache was wenn oder sonst nichts" Funktionalitäten halte ich nichts. Das ist für Anwender sehr wenig durchschaubar und auch fehleranfällig. Dann lieber explizit vorgeben und eine sinnige Fehlerbehandlung einbauen.
