### ISSUE TITLE
Schedule name for infiltration rate of natural ventilation model

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#29]
Natural ventilation model with model type "Scheduled" needs to request a schedule by name for the infiltration (air change) rates.
If the name "InfiltrationRate" were to be used as "Zone" property, i.e.:
```
reftype = ZONE
id = <zone ID>
name = "InfiltrationRate"
```
this property could be provided by the schedules. However, if later someone decides to add this as a convenience result output to RoomBalanceModel, this would be bad. The provided variable would then have the same global lookup property and would be picked up _earlier_ than the scheduled quantity - leading to a cyclic dependency with singularity (=garbage).

Solution:
- forbid ambiguous definition of such quantities and rigorously check each code commit for such problems - might require quite some discipline in the long run
- distinguish scheduled quantities by adding a "Schedule" suffix, for example "InfiltrationRateSchedule". It is very unlikely that some model implementor will decide to call a zone specific result value a "XXXSchedule", or at least this would be recognized easily as error.

My vote: take solution 2, because it is less errorprone in the long run.

**Comment by hirseboy** [comment]
I'd prefer also solution 2.  Then there is no (or at least an unlikely) ambiguity in the lookup process

**Comment by ghorwin** [comment]
Decided: use "InfiltrationRateSchedule" to avoid ambiguities.
