### ISSUE TITLE
Eingabe von relativen Klimapfad nicht möglich

### ISSUE THREAD

**Issue by miradoa** [ghorwin/SIM-VICUS#291]
Das Wetherfile muss für die Nandrad-Simulation im Moment immer einen absoluten Pfad haben, da qt von dem bin Ordner darauf zugreift und nicht von dem Ordner in dem die aktuelle vicus-Datei gespeichert ist. Deshalb ist die relative Pfadeingabe nicht möglich. 
Die Wetterdaten liegen für alle Testfälle unter SIM-VICUS/data/validation/SimQuality/climate

**Comment by ghorwin** [comment]
Das ist so nicht direkt ein Fehler - damit in der Oberfläche mit der Datei gearbeitet werden kann, braucht man den absoluten Dateipfad.
Was aber fehlt ist eine Optionsauswahl wie bei DELPHIN:
- Pfad als Absoluten Pfad speichern
- Pfad relative zur Projektdatei speichern

Das baue ich schnell noch ein.
