### ISSUE TITLE
View-Actions "Center Geometry" and "Search geometry"

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#300]
Die Funktion "Suchen" (Strg+F) hat zwei Funktionen.

1. bei selektierten Objekten:
  * Stellt den Mittelpunkt der "virtuelle" Boundingbox in der sich alle selektierten Objekte befinden in die Mitte der Szene. Somit sind alle selektierten Objekte sichtbar.
2. Falls nichts selektiert ist:
  * Es wird ein Dialog aufgerufen der die Objekte (Raum, Wände, etc.) nach einer Zeichenkette durchsucht. Dabei müssen Wildcarts verwendet werden können (entweder am Anfang für Präfix oder am Ende für Suffixe)

**Comment by ghorwin** [comment]
Funktion würde ich trennen:

1. Ctrl + M - "Place geometry in the middle" 

- bei ausgewählten Elementen werden diese zentriert (Viewport verschoben bis alle ausgewählten Element gut sichtbar sind)
- ist nichts ausgewählt, wird die gesamte Geometrie zentriert

2. Ctrl + F - "Find" ... was soll denn passieren, wenn was gefunden wurde? -> Auswählen? Dann ist der Smart-Select-Dialog hier sinnvoller.
