### ISSUE TITLE
Clarify: should it be possible to mix cyclic/non-cyclic climate data with cyclic/non-cyclic schedule data?

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#31]
Climatic loads and schedules are both time-dependent value providers.

For each data source we can select either continuous data or cyclic data. In the case of climate conditions, we might have regular annual climate data (typically hourly values), or we may simulate a real case with continuous (possibly measured) data. 

Similarly for schedules we may have some kind of regular, annually repeating schedules, and we may simulation real schedules, possibly measured or obtained from building automation systems.

For climate data, the type of data and usage is controlled implicitely in the c6b files.

For scheduled data, the type of usage is controlled by the `<IBK:Flag name="Cyclic">true</IBK:Flag>` parameter in the schedules data block.

Question: while quite possible to mix continuous and cyclic usage, for example use measured continuous climate data and at the same time cyclic annual generic schedules, this may cause problems when leap years are involved and when multi-year data (applied in cyclic manner) will cause deviations in day-of-the-week assignments. So, should we prevent that, so that user can only use either can use continuous data for both climate and schedules, or generic cyclic data for both?

**Comment by Arombolosh** [comment]
DailyCycle only for cyclic simulations.
Non-Cyclic only AnnualSchedules possible.
