### ISSUE TITLE
Get SIM-VICUS listed on the FMI tools page

### ISSUE THREAD

**Issue by chrbertsch** [ghorwin/SIM-VICUS#315]
It would be nice to get sim-vicus listed on https://fmi-standard.org/tools/

Even better would be participation in the FMI Cross-Check https://github.com/modelica/fmi-cross-check

**Comment by ghorwin** [comment]
@Hauke: please generate a simple network FMU on Windows and Linux using FMI4 CoSim v2.0 and a MasterSim test project.

I'll create two simple building model FMUs with a simple control model from Modelica, also with MasterSim as test-master.

Please store the input project (vicus and nandrad project files) in github repo (`data/fmu`) and scripts to generate the respective FMUs. I'll do the same for my FMUs and for MacOS.

We should then have 3 FMUs for 3 plattforms, which should satisfy the requirements.
