### ISSUE TITLE
Add FMI Output "FlowElementHeatLossPerLength"

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#321]
FMI Output of length specific heat loss of network elements would simplify FMI coupling with soil

**Comment by ghorwin** [comment]
Implementation wouldn't be difficult, yet adds a memory overhead to all network projects. 

If workflow involves creating both `.nandrad` and `.msim` files, as well as NANDRAD-FMU, this conversion can be included in the MasterSim-Graph-Statement.

Let's look at the workflow...

**Comment by ghorwin** [comment]
Not needed anylonger, handled in FMU session export
