### ISSUE TITLE
Keyboard handler "shift pressed" state is not reset when using shortcut with shift that opens a dialog (like save as with Ctrl+Shift+S)

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#322]
Problem:
1.Save an existing project that contains a network using a new project name
2. Try to select a single node or edge by clicking in the scene
--> the entire network is selected instead of the single node / edge

**Comment by ghorwin** [comment]
Resolution: when global shortcut is detected that opens a modal dialog with own event loop, reset keyboard handler's shift/modifier key states (or for simplicity, clear all "held" states).
