### ISSUE TITLE
Mathematische Regel für die Skalierung des MausKoordinatenSystems

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#338]

**Comment by ghorwin** [comment]
Analyse:
- Koordinatensystem bekommt vom Szenenmanagement lediglich neue Weltkoordinate (und gelegentlich Rotationsmatrix) gegeben. 
- Koordinatensystem kennt nicht den Abstand zum Betrachter und weiß auch selbst nicht, wie groß die Kugel erscheint
- Kameraposition ist aber bekannt
- Kameralinse ist bekannt

Vereinfachend könnte man bei Abstand < LIMIT einfach das Koordinatensystem transparent zeichen und die Achsen als Linien.
