### ISSUE TITLE
Normalen verschwinden nicht nach ausblenden

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#340]
Man klickt eine Fläche an (mit Normalen eingeschaltet) dann blendet man die Fläche (ohne Sie abzuselektieren) aus. 
Dann bleiben die Normalen erhalten.
Die Fläche ist weg das ist gut aber die Normalen brauchen ein update.

**Comment by ghorwin** [comment]
Kann ich nicht reproduzieren. Im Code wird bei "NodeStateChanged" Undo-Actions jeweils das Normalen-Vektor-Objekt aktualisiert.
