### ISSUE TITLE
Fehler bei COmponentenzuweisung

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#355]
Wenn 2 Flächen Verknüpft sind ist, muss wenn sich die Komponente einer der beiden Flächen ändert, die zweite sich mit ändern. Das funktioniert noch nicht immer richtig, manchmal kann es sein, dass verknüpfte Flächen unterschiedliche Komponenten zugewiesen haben. Wo genau der Fehler produziert wird sollte geklärt werden, aber generell sollte es eine Prüfung geben, dass verknüpfte Oberflächen diesselbe Komponente zu gewiesen haben

**Comment by ghorwin** [comment]
Habs in verschiedenen Konstellationen getestet - kann den Fehler nicht reproduzieren.
