### ISSUE TITLE
Don't save DB elements from project to user DB (for network elements)

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#369]
Bei den Netzwerkelementen wie Hydraulische Komponenten, SubNetworks, Controllers hat sich gezeigt, dass das bisherige Vorgehen jedes DB element in der DB zu speichern unpraktisch ist. man ändert einen Parameter (z.B. Sollwert des Controllers) und hat dann beim nächsten Laden des Projekts das Element doppelt (mit altem und neuem Wert). Die DB bläht sich schnell auf.

Vorschlag: Die Elemente bleiben immer lokal im Projekt. Mit einem Button kann man ein Element gezielt in die user DB speichern.
Außerdem werden natürlich weiterhin die elemente der build-in DB angezeigt.

**Comment by ghorwin** [comment]
Ok, Implementierung wie besprochen:

- DB-Elemente erhalten neues (runtime-only) Flag: `m_local`
- Beim Import von Projekt-DB-Elementen (nach dem Einlesen der Projektdatenbank) werden die neuen DB-Elemente mit `m_local = true;` angelegt
- DB-Modelle werden um neue Itemrole `Local` erweitert, die den Zustand des Flags `m_local` an das Delegate weiterreicht
- DB-Delegate zeichnet `Local=true` DB-Elemente mit neuer Hintergrundfarbe (ähnlich wie built-in DB Elemente), z.B. in hellblau oder so
- Bei Auswahl von DB-Elementen mit `m_local=true` wird ein neuer Button "Store in User-DB" aktiv
- "Store in User-DB" Button setzt `m_local=false` 
- Beim Schließen eines Projekts (SVProjectHandler) wird neue Funktion `SVDatabase::removeLocalDBElements()` aufgerufen, diese entfernt alle DB-Elemente mit `m_local=true`

**Comment by Labauke** [comment]
Einen kleinen Haken gibt es noch: Man könnte jetzt ein neues DB-Element erstellen, was man aber noch nirgends benutzt (referenziert) hat. Da es `m_local` ist würde es dann weder in die userDB, noch in die embedded-DB gespeichert werden. Es wäre also nach speichern und neu öffnen des Projekts weg.

Die Lösung wäre in der updateEmbeddedDatabase() Funktion auch alle Elemente die `m_local` sind speichern. Sollte ok sein. Es werden dann eben im Projekt nicht mehr nur referenzierte Elemente gespeichert sondern alle die lokal erstellt wurden und nicht in der DB sind.

Ansonsten würde ich das wie oben beschrieben mal einbauen ...

**Comment by ghorwin** [comment]
Beim Erstellen von neuen DB-Elementen gibt es folgendes zu berücksichtigen:

- ist kein Projekt geladen, werden neue DB-Elemente automatisch der NutzerDB hinzugefügt (local=false)
- ist ein Projekt geladen, werden neue DB-Elemente als lokale DB-Elemente hinzugefügt

Beim Speichern eines Projekts werden alle __referenzierten__ DB-Elemente (egal aus welcher Datenquelle) in die Projektdatei gespeichert. Damit kann das Projekt auf andere Rechner ohne Datenverlust übertragen werden. Nach Schließen eines Projekts werden alle lokalen DB-Elemente entfernt (also wenn man ohne Projekt die DB bearbeitet, sieht man nur Built-in und UserDB-Elemente).

Dies birgt aber die Gefahr von Datenverlust, wenn jemand ein Projekt geöffnet hat, ein neues DB-Element (local=true) erstellt und dann diese DB-Element *nicht* referenziert. In diesem Fall würde es beim Speichern des Projekts nicht eingebettet und geht beim Schließen des Projekts verloren.

Daher sollten lokale DB-Elemente ebenfalls immer in die Projektdatei eingebettet werden, um ungewollten Datenverlust zu verhindern.

Allerdings führt dieses Verhalten potentiell zu einer ungewollten Ansammlung alter, nicht mehr verwendeter DB Elemente. Beispiel:

Ich habe ein Projekt mit 2 Konstruktionen, die 6 Materialien referenzieren. Beim Einlesen dieses Projekts werden diese 6 Materialien als lokale Materialien importiert. Nun tausche ich beide Konstruktionen aus und verwende andere Materialien. Beim Speichern des Projekts werden nun sowohl die neuen als auch die alten 6 lokalen Materialien eingebettet. Öffne ich das Projekt das nächste Mal, habe ich sowohl die alten, nicht mehr verwendeten, wie auch die neuen Materialien in der DB.

Hier wäre eine Funktion "entferne alle nicht mehr referenzierten, lokalen DB Elemente) hilfreich (=NiceToHave-Feature).

Außerdem müsste noch folgender Anwendungsfall berücksichtigt werden:

- ich erstelle ein neues Material mit gleichzeitig geöffnetem Projekt (->lokales DB-Element)
- ich bearbeite eine UserDB-Konstruktion und referenziere dieses Material

Frage: soll das so referenzierte lokale Material durch diese Referenz automatisch zum UserDB-Element gemacht werden? Falls nicht, würde die UserDB-Konstruktion nach Entladen des Projekts (und damit Entfernen des lokalen Materials) ungültig werden...

**Comment by Arombolosh** [comment]
Ich würde diesen Weg anders lösen. Ich würde ruhig alles löschen was noch im freien Raum rumhängt. Sonst müllen wir nur die Projektdatei zu,

* ist kein Projekt geladen, werden neue DB-Elemente automatisch der NutzerDB hinzugefügt (local=false)
* ist ein Projekt geladen, werden neue DB-Elemente als lokale DB-Elemente hinzugefügt
hier geh ich mit.
Sind beim Schließen des Projekts noch Datenbankelement vorhanden die anschließend gelöscht werden würden bin ich dafür eine Abfragemeldung kommen zu lassen. Löschen oder Bearbeiten!

In den Datenbankeinträgen muss der Nutzer entscheiden können ob er die Element mit in die NutzerDB aufnimmt oder nicht. Hierfür reicht eine Checkbox ja aus.
Will er das nicht werden nicht referenzierte halt gelöscht. So entsteht kein Datenmüll.

**Comment by Labauke** [comment]
Schau dir am besten mal an wie es jetzt implementiert ist (im master).

Wenn man eine Komponente erstellt, es dann aber doch gerade nicht schafft die zuzuweisen und das Projekt schließt, würde die verschwinden. Deshalb habe ich es so gemacht das lokale Elemente immer gespeichert bleiben. 

Für deine Abfragemeldung müsste man sowieso prüfen ob das Element irgendwo referenziert ist. Dann könnte man diese Prüfung auch gleich im Dialog anzeigen (kursiv, grau -> nicht zugewiesen, fett -> zugewiesen z.b.), so wie in DELPHIN. Fände ich eigentlich schöner. Dann kannst du auch mal verschiedene Varianten in einem Projekt probieren ohne das dir was verloren geht oder du die user DB zu müllen musst ...

Man kann ja noch einen Button "bereinigen" einbauen, der dann die nicht referenzierten Elemente löscht. Das betrifft sowieso alles nur lokale Elemente.

**Comment by ghorwin** [comment]
Die "Hervorhebung von aktuell benutzen DB-Elementen" finde ich auch hilfreich, idealerweise gibt es noch einen Filter, oder irgendwo eine Zusammenfassungsübersicht aller genutzten DB-Elemente. Hier müsste man die Funktion `updateEmbeddedDatabase(VICUS::Project & p)` aufteilen: einmal referenzierte Elemente suchen und separat lokale, nicht referenzierte Elemente suchen. Oder man macht einen Diff: d.h. aus allen lokale DB elementen werden die referenzierten Elemente entfernt. Bleiben welche übrig, sind das "Löschkandidaten" und der Nutzer kann dann entscheiden, ob er die ins Projekt speichern will oder löschen.

**Comment by TriKat** [comment]
finde @Labauke ansatz am besten

**Comment by ghorwin** [comment]
Ist nach Diskussion mit Dirk und Hauke entschieden: neue DB Elemente sind lokal wenn ein Projekt geladen ist. _alle_ lokalen DB Elemente werden _immer_ im Projekt gespeichert.

Zusätzlich gibt es eine Funktion "nicht referenzierte DB Elemente anzeigen" und unterhalb der Liste einen "Löschen" Button.
@Hauke: könntest Du bitte die Umsetzung übernehmen?

**Comment by Labauke** [comment]
see
feature/Feature-DBElementDependencies
