### ISSUE TITLE
Konstruktionsbearbeitung anpassen

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#384]
Wenn man im Konstruktionsmanager schichten verschieben will, sollte der Cursor beim nach links oder rechts verschieben immer auf der verschobenen schicht bleiben und nicht auf die dann an dieser position befindliche schicht hopsen, das verbessert wesentlich das handling

**Comment by ghorwin** [comment]
-> ist was für Heiko, QtExt-Erweiterung

**Comment by HWFechner** [comment]
gefixt
