### ISSUE TITLE
Klima File speichern, wenn man es einmal eingegeben hat 

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#386]
Wenn man in einer vicus datei einmal ein klima vorgegeben hatte, sollte der pfad gespeichert werden in der datei bitte. ist schöner für's handling

**Comment by ghorwin** [comment]
Der Startdialog ist nicht sehr intuitiv - wenn man eine Klimadatei ausgewählt hat und diese im Projekt gespeichert werden soll, muss man den Dialog mit "Store input data and close project" beenden. Das  kann man leicht übersehen.

Vorschlag: redesign dieses Dialogs. Wir machen aus einem fetten Simstart-Dialog mehrere über Pfeilbuttons verknüpfte Einzeldialoge - beim Wechseln zwischen Dialogseiten wird bei Änderungen automatisch eine Undo_Action ausgeführt. So wäre sichergestellt, dass beim Rückwechseln vom Location-Dialog der Klimadateipfad auch im Projekt landet.

**Comment by Labauke** [comment]
Die Einzeldialoge sollten am besten aber auch direkt zugänglich sein. So dass man nicht erst 5 Dialoge durchklicken muss um bei den Netzwerkeinstellungen zu landen.

**Comment by ghorwin** [comment]
Ganz genau - jeder Dialog bekommt einen eigenen Menüeintrag (und notfalls eigenen Shortcut)
