### ISSUE TITLE
Stephans Climate File Problem 

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#397]
Der Climate File muss immer wieder auf das Lokale Directory des jeweiligen computers, wo die datei geöffnet ist bzw. bearbeitet wird abgestimmt werden, wenn man die datei öffnet. Das muss immer aktualisiert werden, sonst gibts den fehler.

**Comment by ghorwin** [comment]
Also:

Wenn man einen eigenen Klimadateipfad auswählt, kann man dort einen absoluten oder relativen Pfad zur Projektdatei angeben. In letzterem Fall wird in der Projektdatei das mit Platzhalter gespeichert:

```xml
<Location>
	<IBK:Parameter name="Latitude" unit="Deg">51.03</IBK:Parameter>
	<IBK:Parameter name="Longitude" unit="Deg">13.7</IBK:Parameter>
	<IBK:Parameter name="Albedo" unit="---">0.2</IBK:Parameter>
	<TimeZone>1</TimeZone>
	<ClimateFilePath>${Project Directory}/../../../projekte/Bockwen/climate/DWD2020GarsebachBeiMeißen.epw</ClimateFilePath>
</Location>
```

Beim Einlesen des Projekts wird die Klimadatei relativ zur Projektdatei gesucht.

Bei Auswahl einer Klimadatei aus der Datenbank wird der Pfad relativ zur Datenbank gespeichert:

```xml
<Location>
	<IBK:Parameter name="Latitude" unit="Deg">51.03</IBK:Parameter>
	<IBK:Parameter name="Longitude" unit="Deg">13.7</IBK:Parameter>
	<IBK:Parameter name="Albedo" unit="---">0.2</IBK:Parameter>
	<TimeZone>1</TimeZone>
	<ClimateFilePath>${Database}/DB_climate/Europe/Germany/TRY2011/DE-04-TRY-2010__Potsdam__Jahr_00000K0_00081m.c6b</ClimateFilePath>
</Location>
```

In jedem Fall ist das unabhängig vom Absolutpfad.

Wo genau ist das Problem?

**Comment by ghorwin** [comment]
Wahrscheinlich ein Duplikat zum Platzhalter-Problem.
