### ISSUE TITLE
Database geht in die Hose

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#398]
Im SimVicus wir in der Vicus datei ständig die Database versemmelt, wenn am nauf unterschiedlichen Systemen arbeitet hat er immer den pfad des letzten bearbeiters drin. der pfad muss immer aktuell gesetzt werden beim jeweiligen bearbeiter (gerät)

**Comment by ghorwin** [comment]
Das sollte eigentlich automatisch funktionieren, in der Funktion:

```c++
IBK::Path SVProjectHandler::replacePathPlaceholders(const IBK::Path & stringWithPlaceholders) {
	std::map<std::string, IBK::Path> mergedPlaceholders;

	mergedPlaceholders["Database"] = QtExt::Directories::databasesDir().toStdString();
	mergedPlaceholders["User Database"] = QtExt::Directories::userDataDir().toStdString();
	....
```
wird ein gegebenfalls verwendeter Platzhalter "Database" mit dem Pfad des aktuellen Anwenders überschrieben.

Wie kann man das Problem reproduzieren?

**Comment by ghorwin** [comment]
Ok, Problem erkannt - es liegt am NANDRAD Projektexport. Dort wird der Platzhalter unverändert aus der eingelesenen Projektdatei (mit alten Database-Pfaden) übernommen und beim Auflösen des Absolutpfads wird `SVProjectHandler::replacePathPlaceholders` *nicht* verwendet.

Ich würde jetzt einfach das Problem grundlegend umgehen und nach dem Einlesen eines Projekts die Platzhalter im `VICUS::Project` aktualisieren.

**Comment by ghorwin** [comment]
Ich würde sogar soweit gehen, in der VICUS-Projektdatei **gar keine Platzhalter** zu erlauben!
