### ISSUE TITLE
Schedules in Nandrad: Invalide Splines werden nicht erkannt

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#401]
see NANDRAD::Schedules::readXML() Zeile 221:
es wird keine Exception geworfen wenn z.B. der x-Vektor nicht monoton ist. 
Lösung: Man könnte in IBK::LinearSpline::setValues() eine Exception statt der Message werfen.

**Comment by Labauke** [comment]
https://github.com/ghorwin/SIM-VICUS/commit/1a9b0889ecc30e20604042bb45daafa2fff26075

**Comment by ghorwin** [comment]
Der Patch 1a9b088 funktioniert so nicht. Entweder man hat einen tsv-Dateipfad, oder man hat die Splinedaten gesetzt. Im erstenen Fall muss man erst die Daten laden, dass passiert in checkAndInitialize().

**Comment by Labauke** [comment]
stimmt. Die beste Lösung ist in IBK::LinearSpline Zeile 137 statt der Warnung eine Exception zu werfen. Hab mich nur nicht getraut in der IBK Lib was zu ändern. Würde ich so machen wenns ok ist?

**Comment by ghorwin** [comment]
Das greift eine inkonsistenz in der IBK::LinearSpline auf. Diese ist nämlich auch als Datenkontainer für Zeitreihen gedacht, die noch korrigiert werden müssen. Deshalb kann man in setValues() auch zunächst die Vektoren setzen (lediglich die gleiche Länge müssen sie haben) und dann kann man via valid-check oder makeSpline() testen, ob das so gültig ist.

DIe Unterscheidung zwischen Exception und stiller Warnung ist hier fließend. Ich würde im SimVicus in der Tat statt einer Warnung eine Exception auslösen. Ob das im DELPHIN dann knallt, weiß ich nicht.
