### ISSUE TITLE
NandradFmuGenerator: Dateinamen separat vom model name editieren

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#402]
Als Dateinamen der FMU möchte man oft Unterstriche verwenden, im model name sind die aber nicht erlaubt. Deshalb: separates line edit für Eingabe des FMU-Dateinamen.

**Comment by ghorwin** [comment]
Ist entsprechend der FMI-Richtlinien nicht erlaubt (oder sollte nicht gemacht werden). Ich hatte im Normungsausschuss auch mehrfach auf das Problem der Internationalisierung hingewiesen (Stichwort Chinesische/Kyrillische Zeichen), aber das hat kein Gehör gefunden.

Man müsste nochmal nachlesen, ob _ wirklich ein verbotenes Zeichen ist. Meines Wissens nach kann das nur bei unserem FMU-Generator zu problemen führen, wenn jemand z.B.  _win32`  als FMU-Name verwendet :-)

**Comment by Labauke** [comment]
>  wenn jemand z.B. _win32 als FMU-Name verwendet :-)
finde ich nicht witzig :)

Alternative Lösung: Statt der harten Fehlermeldung "Invalid FMU Name" geben wir eine Warnung aus, dass der Name nicht den Richtlinien entspricht, also weiter nur auf eigene Gefahr . Dan können wir das trotzdem mit MasterSim nutzen. Mit SimulationX z.b. funktioniert es dann halt nicht ...
