### ISSUE TITLE
Movement Issues bei großprojekt

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#405]
Bei Großprojekten ist das fangen von Punkten unmöglich
und man sieht den Bubbel nie, der bubbel muss iwie mit zoomgröße auch angepasst werden, dass der immer sihctbar ist. 
VGL projekt ist Fackel bappert @ghorwin ... wenn du die datei von mir brauchst schick ich sie dir. aber die steuerung müssen wir dringend überarbeiten, das tötet den workflow bissl und steigert den blutdruck manchmal in ungesunde höhen, wenn man den verdammten punkt nicht geklickt kriegt grrrrrrrrrrrrrrrrrrrrr vorallem zum freitag

**Comment by ghorwin** [comment]
Ja, kann ich nachvollziehen... ich denk da mal über die Mathematik nach (war eigentlich auf dem "kleinen" TODO-Stapel von Dirk, aber...) :-)
