### ISSUE TITLE
Rücksetzen von Ausgaben in FMUs

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#406]
Ausgaben werden derzeit nach festgelegtem Zeitfenster ausgeschrieben. In FMUs mit Rücksetzfähigkeit sind aber aktuelle Ausgabewerte nicht automatisch gültige Werte - es kann ein einmal durchgeführter Rechenschritt als ungültig verworfen werden. Es muss also das Rücksetzen von Ausgaben vorgesehen werden:
1.) Das Schreiben von FMU-Ausgaben ist auf gültige Kommunikationsschritte einzuschränken.
2.) Das Löschen von Ausgabwerten für ungültige Kommunikationsschritte im Ausgabebuffer muss möglich sein.
3.) ...?

**Comment by ghorwin** [comment]
Aktuell werden Ausgaben je Ausgabedatei zunächst im Speicher gecached. Dazu wird je nach aktiven Ausgaberaster die Funktion `OutputFile::cacheOutputs()` in jeder Ausgabedatei aufgerufen, die die aktuellen Variablen in den Cache überträgt.

Dabei werden die Variablen
```
m_cache
m_tLastStep
m_integralsAtLastOutput
```
aktualisiert.

Die Funktion `OutputHandler::writeOutputs()` ruft nach dem Aktualisieren des Caches auch die Funktion `flushCache()` auf, die je nach Menge der gespeicherten Ausgaben und/oder vergangener Simulationszeit die Ergebnisse in die Datei schreibt.

Im Fall einer FMU Ausführung ist bei iterativen FMUs eine Veränderung des Cache-Verhaltens notwendig.

- Beim Wiederholen eines Co-Sim-Zeitschritts müssen die bisherigen Cache-Variablen in der Klasse `OutputFile` zurückgesetzt werden. 
- Die Funktion `flushCache()` darf nicht während der normalen Berechnung nicht mehr aufgerufen werden.
- Immer wenn ein Kommunikationsinterval erfolgreich abgeschlossen wurde (kein Rücksetzen mehr), muss die Funktion `flushCache()` aufgerufen werden.

**Comment by KnutKnudson** [comment]
Tatsächlich hat sich in dem bisherigen Konzept ein Fehler eingeschlichen. Also, das angedachte Prozedere in fmi2DoStep war

1.) Abfrage, ob der letzte Zeitschritt wiederholt wird (via 'noSetFMUStatePriorToCurrentPoint'). Wenn nicht, dann werden alle Ausgaben der FMU Slaves zum Schreiben freigegeben und gleichzeitig der Ausgabezwischenspeicher gelehrt.

2.)  Leeren des Ausgabespeichers jedes FMU Slaves (außer zu Beginn der Simulation). 

3.) Durchführen der Integration in den FMU Slaves (und auffüllen des Ausgabechaches).

Bei 1.), wird ein nicht wiederholter Zeitschritt mit einem akzeptierten Zeitschritt gedanklich gleichgesetzt (und alle Ausgaben im Chache werden übernommen). Kritisch ist dies, wenn im SImulationsmaster eine maximale Iterationszahl vorgegeben ist.

**Comment by KnutKnudson** [comment]
Also, das angedachte Prozedere in fmi2DoStep ist

1.) Abfrage, ob der letzte Zeitschritt wiederholt wird (via 'noSetFMUStatePriorToCurrentPoint'). Wenn nicht, dann werden alle Ausgaben der FMU Slaves zum Schreiben freigegeben und gleichzeitig der Ausgabezwischenspeicher gelehrt.

2.) Leeren des Ausgabespeichers jedes FMU Slaves (außer zu Beginn der Simulation).

3.) Durchführen der Integration in den FMU Slaves (und auffüllen des Ausgabechaches).

**Comment by KnutKnudson** [comment]
Dieses Prozedere ist insofern kritisch, da verschiedene Ursachen zu einem Abbruch der Iteration führen können. 
Wird bei 1.) ein fehlerhafter Zeitschritt wiederholt und dabei die maximale Iterationszahl erreicht, so ist  'noSetFMUStatePriorToCurrentPoint' auf true. Die Ausgabewerte werden also als 'korrekt' angenommen und in den Stream geschrieben, obwohl  sie fehlerlastig sind.

**Comment by KnutKnudson** [comment]
Ein alternativer Vorschlag wäre, die Verwaltung des internen Ausgabecaches dem Slave selbst zu überlassen. Hierfür muss in der Serialisierungsinformation der letzte Ausgabezeitpunkt abgelegt und beim Deserialisieren aktualisiert werden. Kommt es zum Rücksprung, so ist  der neue Ausgabezeitpunkt <= alter Ausgabezeitpunkt. In diesem Fall muss der Ausgabecache innerhalb des Slaves selbstständig gelehrt werden. 

In  fmi2DoStep würde nur nmoch das Folgende getan:
1.) Abfrage, ob der letzte Zeitschritt wiederholt wird (via 'noSetFMUStatePriorToCurrentPoint'). Wenn nicht, dann werden alle Ausgaben der FMU Slaves zum Schreiben freigegeben und gleichzeitig der Ausgabezwischenspeicher gelehrt.

3.) Durchführen der Integration in den FMU Slaves (und auffüllen des Ausgabechaches).
