### ISSUE TITLE
Wenn man ein lokales DB Element von einem UserDB-Element referenziert, wird das lokale DB Element automatisch auch zum UserDB-Element

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#410]
Beispiel:

1. Material 1 (UserDB) wird von Construction 1 (UserDB) referenziert
2. Material 2 (lokal) wird neu erstellt
3. Construction 1 wird verändert und referenziert nun Material 2  -> Material 2 wird automatisch in UserDB verschoben

Aber:
- falls die Konstruktion selbst auch lokal ist, bleibt das Material lokal

**Comment by Labauke** [comment]
see 
feature/Feature-DBElementDependencies
