### ISSUE TITLE
Wärmekapazität der Rohrwand berücksichtigen

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#414]
Vor allem für das Paper und für den DESTEST wichtig.

Möglichkeit 1: Aus der Wärmekapazität der Rohrwand wird ein äquivalentes Wasservolumen berechnet, welches auf die diskretisierten Rohrvolumina addiert wird
--> sehr einfach zu implementieren

Möglichkeit 2: Es wird ein zusätzlicher Zustand eingeführt, z.B. 1 Kapazität für die gesamte Rohrwand. 
--> aufwändiger zu implementieren

**Comment by ghorwin** [comment]
Variante 1, definitiv. Unterschied hängt nur am Wärmeübergangskoeffizienten zwischen Rohrwand und Fluid, und so klein ist der nicht.
