### ISSUE TITLE
Fehler beim Entfernen der Surface Heating

### ISSUE THREAD

**Issue by ansoehnchen** [ghorwin/SIM-VICUS#415]
* Component A mit Acitve Layer erstellt und mehreren Räumen/Flächen zugewiesen
* Surface Heating zugewiesen
* Component A kopiert -> Component B
* aus Component B Active Layer deaktiviert und dann einen Teil der oberen mit bereits Comp. A belegten Flächen zugewiesen.
* Anschließend den Building->"Surface Heating" Modus wieder aufgerufen
* Die Szene stellt eine andere Visualisierung dar wie die Tabelle (Tabelle hat die richtigen Components) Visualisierung zeigt noch die Comp A an die aber jetzt schon Comp B enthalten und nicht mehr hervorgehoben sein dürften.

- Änderung wird in der Liste sichtbar - in der Szene erfolgt hingegen keine Änderung
- auch nach erneutem Öffnen von SIMVICUS keine Änderung ###

**Comment by ansoehnchen** [comment]
In der Projectdatei müssen im ComponentInstance die Daten vom SurfaceHeating gelöscht werden. Dann stimmt die Szene mit der Tabelle überein.

**Comment by ghorwin** [comment]
Problem: Zuweisung der SurfaceHeating und Component sind unabhängige Eigenschaften der ComponentInstance. 

Vorschlag: wenn die Komponentenzuweisunge geändert wird, und die neue Komponente keine aktive Schicht hat, kann man automatisch auch die SurfaceHeating entfernen. Ich bau das mal so ein.
