### ISSUE TITLE
Lüftungsmodell NANDRAD --> Modelldoku und Diskussion

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#416]
# Einfache Modellvorstellung für Lüftung zur Einhaltung der thermischen Behaglichkeit

- es gibt ein Behaglichkeits-Temperaturband, definiert durch

```
T_roomMin
T_roomMax
```
- wir formulieren folgende Wunschvorstellung:

1. Solange der Raum im Behaglichkeitsinterval liegt, verwenden wir den nach Zeitplan vorgegeben Luftwechsel = B(t)
2. Liegen wir außerhalb des Behaglichkeitsintervals, erhöhen wir die Lüftungsrate um C(t), aber _nur_ wenn das was bringt (=wir nähern uns dem Behaglichkeitsinterval wieder an). Dadurch kann man mit der Lüftung sowohl Heizen als auch Kühlen.
3. Zusätzlich gelten Einschränken (wie z.B. max. Windgewindigkeit), die eine Fensterlüftung unmöglich machen.

Formel:

```
n = eps * C(t) + B(t)

B(t) - Luftwechselrate nach Vorgabezeitplan (wird vom Nutzer definiert)
C(t) - mögliche maximale Erhöhung der Luftwechselrate die zum Steuern verwendet wird
eps - Steuerparameter der sich durch die Bedingungen ergibt.

```
Einflussparameter für Regelsignal `eps`:

```
Konstanten/rein zeitabhängige Größen:
- Außenlufttemperatur
- (Außenluft-CO2-Konzentration)

Dynamische Parameter:
- Raumlufttemperatur
- (für CO2-Bilanz später auch die aktuelle CO2-Konzentration)
```

Hinweis: `eps` muss eine Rampe haben (geglättet sein)

Algorithmus:
```python
# Windgeschwindigkeit zu hoch?
if vWind > vWindMax:
    keine Erhöhung
    stop

eps = 0 # Standardmäßig erhöhte Lüftung aus
RAMPING_DELTA_T = 0.2 K # Toleranzbereich für Rampenbildung
# im Heizfall?
if T_room < T_roomMin:
   epsRamp = scale( (T_roomMin - T_room)/RAMPING_DELTA_T )
   # T_room == T_roomMin --> epsRamp = 0 
   # T_room == T_roomMin - RAMPING_DELTA_T --> epsRamp = 1

    # Lüftung bringt Heizwirkung?
    if T_out > T_room:
       epsRamp2 = scale( (T_out - T_room)/RAMPING_DELTA_T )
       # T_out == T_room -> epsRamp2 = 0
       # T_out == T_room - RAMPING_DELTA_T -> epsRamp2 = 1
       eps = epsRamp * epsRamp2

# Kühlfall?
else if T_room > T_roomMax:
   epsRamp = scale( (T_room - T_roomMax)/RAMPING_DELTA_T )
   # T_room == T_roomMax --> epsRamp = 0 
   # T_room == T_roomMax + RAMPING_DELTA_T --> epsRamp = 1

    # Lüftung bringt Kühlwirkung?
    if T_out < T_room:
       epsRamp2 = scale( (T_room - T_out)/RAMPING_DELTA_T )
       # T_out == T_room -> epsRamp2 = 0
       # T_out == T_room + RAMPING_DELTA_T -> epsRamp2 = 1
       eps = epsRamp * epsRamp2

```

Erweiterung auf CO2-Bilanz (zunächst  in externer FMU):

- in der Praxis ist üblich, die CO2-Konzentration (1700 ppm) bis auf einen maximalen Grenzwert ansteigen zu lassen, dann gründlich zu lüften (dabei auch ggfs. die thermischen Behaglichkeitsforderungen kurzzeitig zu ignorieren) und a) nach einer bestimmten Lüftungszeit; b) nach Unterschreiten einer Mindestkonzentration (1100 ppm) die erhöhte Lüftung zu beenden. Diese Totband-Regelung wäre mit einem zustandsbehafteten Hystereseregler umzusetzen - damit muss die FMU den eigenen Zustand speichern/wiederherstellen (klappt mit FMICodeGenerator bereits automatisch)

- ein Toleranzband analog zu thermischen Behaglichkeit oben macht keinen Sinn, da es ja nicht "zu wenig" CO2 geben kann, was man von draußen reinlüften möchte

Algorithmus-Vorschlag:

```python
# Prüfung, ob erhöhte CO2 Lüftung an ist
if INCREASED_CO2_VENTILATION_ACTIVE:
   eps = 1
   stop
else:
  # thermische Regeln wie oben


-----
in stepCompleted() bzw. zu Beginn/am Ende einer Kommunikationsschritts:

# Prüfung auf erhöhte Lüftung wegen zu hoher CO2-Belastung
if C_CO2Room > C_CO2_MAXLIMIT:
   INCREASED_CO2_VENTILATION_ACTIVE = true
else if  C_CO2Room < C_CO2_MINLIMIT:
   INCREASED_CO2_VENTILATION_ACTIVE = false
```

----

# alte Ideen
Zuerst kurz was wir brauchen.

Wir benötigen ein Lüftungsmodell (Ventilation (NICHT Infiltration das bleibt eigenständig wie es derzeit in NANDRAD ist.)) was nach folgenden Maßgaben reagieren kann:

- Einhaltung der CO2 Konzentration im Raum
- Entlastung der Kühlung/Heizung im Raum
- konstant und zeitplangestütze Luftwechselraten

Wie sollte das Modell reagieren.

1. konstanter und zeitplangestütze Luftwechselraten
Hierbei wird einfach der vordefinierte Luftwechsel aufgeprägt anschließen wird die Raumbilanz gerechnet.

2. CO2 Konzentration
Es wird eine CO2-Bilanz gelöst. Außenluft hat eine CO2-Konzentration, ebenso die Innenluft. Durch Quellen oder Senken im Raum sowie durch Luftwechsel zwischen innen und außen wird die Bilanz modifiziert. Als Parametereigenschaften gibt es:

- max. Luftwechsel der auf diesen Raumluftknoten angewendet werden darf
- Zulässiger Höchstwert der CO2-Konzentration. --> Wird dieser Überschritten fängt dieLüftung an. Dabei kann der Luftwechsel langsam ansteigen, wenn die CO2-Raumkonzentration leicht über der Sollkonzentration liegt. Ist sie weit weg wird mit dem max. Limit gelüftet. Der zulässige Höchstwert wird konstant (das brauch ich eigentlich nicht) oder nach Zeitplan vorgegeben.

Limits:
ventilationRateMax = 1 1/h (beispielhafte Vorgabe) (das ist Zeitplangesteuerter Wert)

Setpoint:
CO2Setpoint = 1000 ppm (beispielhafte Vorgabe)

>> AN: CO2-Bilanz derzeit nur in externer FMU, also kein natives NANDRAD-Modell und daher werden auch keine Parameter abgelegt.

3. Heizungs-/Kühlunterstützung (Sommerlicher Wärmeschutz, etc.)
Der Raum wird durch die Lüftung entlastet (Man könnte je nach Parameterset auch Belastungen definieren.).
Parameter:

* Limits ab wann die Lüftung arbeitet KANN:
** Raumluftminimum/-maximum -> liegt die akt. Raumluft innerhalb dieser Grenzen ist die Lüftung arbeitsfähig
** Außenluftminimum/-maximum -> liegt die akt. Außenluft innerhalb dieser Grenzen ist die Lüftung arbeitsfähig
** deltaT -> Differenz zwischen Raumluft und Außenluft (T_room - T_out) -> Ist die aktuelle Differenz zwischen Raum- und Außenluft größer als dieser Vorgabewert ist die Lüftung arbeitsfähig. Wertebereich ist von -unendl. < deltaT < +unendl. (Ich weiß das unendlich bissel viel ist :))

>> AN: Unklar wir DeltaT vom Vorzeichen zu interpretieren ist, wenn sowohl Kühlung als auch Heizung durch Lüftung erreicht werden soll.

** max. Windgeschwindigkeit. -> liegt die akt. Windgeschwindigkeit unterhalb dieser Grenze ist die Lüftung arbeitsfähig.

WICHTIG
Nur wenn die Raumluft unterhalb des Heiz- oder Kühlsollwertes liegt UND die oberen Limits eingehalten sind wird die Lüftung aktiv.

Beispiele:
3.1. Raumkühlung im Sommer (in Klimazonen, in denen es im Sommer draußen üblicherweise kälter ist als drinnen)

Limits:
T_roomMin = 20 °C (sorgt dafür, dass der Raum infolge Lüftung nicht zu kalt wird)
T_roomMax = 100 °C (effektiv deaktiviert)
T_outMin = 18 °C (sinnvoll?, Lüftung bleibt unterhalb der Temperatur aus... warum? Behaglichkeitseinbuße? vielleicht nur benötigt bei "alten" Simulationsprogrammen mit Stundenschritten, um ein Unterkühlen zu verhindern)
T_outMax = 100 °C (sinnvoll?)
T_delta = 2 K (Lüfte nur, wenn Lüftungseffekt sinnvoll---> kann auch negativ werden. !!! Schwierig, Kontinuitätsforderung in der Gleichung zu gewährleisten).
v_WindMax = 40 m/s (übersteigt die Windgeschwindigkeit den Wert, wird Lüftung abgeschaltet = Fenster zu)

ventilationRateIncrease = 3 1/h (das ist zeitplangesteuerter Wert, der wird auf die Grundluftrate addiert, wenn Regelung greift)

Setpoints:

Heizfall: "ich erwärme den Raum durch Lüftung"
- ist aktiv, wenn: T_Raum - T_Outside <=  T_delta und übrige Bedingungen oben sind auch erfüllt
- Zusatzbedingung: T_setpointHeat > T_Raum
 
Kühlfall: "ich kühle den Raum durch Lüftung"
- ist aktiv, wenn: T_Raum - T_Outside <=  T_delta und übrige Bedingungen oben sind auch erfüllt
- Zusatzbedingung: T_setpointCool < T_Raum

T_setpointHeat = 20 °C 
T_setpointCool = 25 °C

Limits:
T_roomMin = 20 °C
T_roomMax = 40 °C
T_outMin = 15 °C
T_outMax = 100 °C
T_delta = 2 K
v_Wind = 40 m/s
ventilationRateMax = 3 1/h (das ist Zeitplangesteuerter Wert)

Setpoints:
T_setpointHeat = 20 °C
T_setpointCool = 25 °C

Zustände zum Zeitpunkt 1:
T_room = 30 °C
T_out = 25 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung anmachen da alle Bedinungen eingehalten sind. Würde sich die Raumluft auf 27 °C dabei abkühlen wird anschließend die Lüftung gestoppt, da das T_delta von 2 K dann greift. Obwohl der Raum kühler gelüftet werden könnte.

Zustände zum Zeitpunkt 2:
T_room = 30 °C
T_out = 35 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung aus da T_delta nicht ok.

Zustände zum Zeitpunkt 3:
T_room = 30 °C
T_out = 5 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung aus, da T_out den Bereich nicht einhält.

Zustände zum Zeitpunkt 4:
T_room = 19 °C
T_out = 5 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung aus, da T_roomMin unterschritten.

3.1. Raumheizung im Winter (das wird wahrscheinlich seltenst vorkommen)

Limits:
T_roomMin = 20 °C
T_roomMax = 40 °C
T_outMin = 15 °C
T_outMax = 100 °C
T_delta = -10 K
v_Wind = 40 m/s
ventilationRateMax = 3 1/h

Setpoints:
T_setpointHeat = 20 °C
T_setpointCool = 25 °C

Zustände zum Zeitpunkt 1:
T_room = 19 °C
T_out = 25 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung aus da T_room < T_roomMin

Zustände zum Zeitpunkt 2:
T_room = 21 °C
T_out = 24 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung aus da Setpoint nicht nach Lüftung oder Kühlung fragen.

Zustände zum Zeitpunkt 3:
T_room = 19 °C
T_out = 30 °C
v_Wind = 4 m/s
Ergebnis: -> Lüftung an -> Heizfall.

Setzt man die T_roomMin und Max auf einen größeren Bereich wird nur gelüftet, die Raumluft außerhalb ihrer beiden Sollwerte ist. Dadurch kommen im Winter natürlich dann Lüftungsverluste zustande.

Kobination
########

Jetzt müssen alle drei Elemente kombiniert werden. D.h. es werden die (ich nenn es mal) Grundlüftung oder Vorgabelüftung + MAXIMUM aus (CO2 Lüftung; Heiz-/Kühllüftung) addiert.

Zur Steuerung
###########

Für die Steuerung sollte dann das Therakles Modell verwendet werden. D.h. sind wir nahe eines Setpoint sollte nicht mit der maximalen Lüftung reingefahren werden, sondern dort sollte eine gewisse Rampe entstehen. Da würde ich aber auf Heiko und Andreas verweisen. 

Beispiel 1:

CO2_Setpoint = 1000 ppm
CO2_room = 1050 ppm
ventilationRateMax = 3 1/h

Hier jetzt nicht mit dem 3 fachen Hammer draufhauen sondern meintwegen mit einer Rampe die zwischen 0 und 100 ppm geht und damit hier einen Luftwechsel von 1,5 1/h erzeugen würde.

Beispiel 2:

CO2_Setpoint = 1000 ppm
CO2_room = 1150 ppm
ventilationRateMax = 3 1/h

Hier volle Leistung -> 3 1/h

So hat wer fragen oder Kritiken?

ENTSCHEIDUNG: Stephan, Katja und ich sehen die ventilationRateMax als Zeitplanvorgabe bitte.

**Comment by HWFechner** [comment]
Hallo,

Das Thema Raumheizung durch natürliche Lüftung würde ich eher weglassen. Ich bezweifle, dass so ein Fall praktisch relevant ist. Da könnten wir einen Setpoint weglassen.

Was die Kombination betrifft könnte man folgendermaßen vorgehen:
- Test ob ein Ausschlußkriterium für Lüftung vorliegt - dann keine Lüftung und keine weitere Berechnung
- Berechnung der aktuell notwendigen Luftwechselrate für jedes Modell (Kühlung und CO2, evtl. noch Luftfeuchte?)
  * dabei das lineare Modell zur Anpassung nehmen (für Alle)
- Maximalwert wird genommen

**Comment by ghorwin** [comment]
Bitte klarstellen (gerne auch gleich oben im Text):

- *Infiltration* = durch Fugenlüftung/Undichtigkeiten der Gebäudehülle entstehende Luftwechselrate; konstant oder in Abhängigkeit von Staudrücken; enthält keine Fensterlüftung; keine Abwärmegewinnung
- *Natürliche Lüftung*  = Benutzergesteuerte erhöhte Lüftung durch Fensterlüftung bei Bedarf (Komforterhöhung), keine mechanische Lüftungsanlage; keine Abwärmegewinnung; schließt auch automatische Fensteröffnungsmechanik ein; Luftwechselerhöhung in Abhängigkeit von Fenster-/Lüftungsöffnung ist eine konstante Erhöhung, oder (in fortgeschrittenen Modellen) abhängig von Temperaturunterschieden und Staudrücken
- *Mechanische Lüftung (Ventilation)* = Jedwege automatisierte, mechanisch unterstützte Erhöhung des Luftaustauschs im Raum, mit oder ohne Konditionierung der zugeführten Luft; mit oder/ohne der Bilanzerung von Abwärmegewinnung

**Comment by Arombolosh** [comment]
Jup das hier ist erstmal nur für NANDRAD. Ich habe auch alles aus NANDRAD Sicht geschrieben.

@HWFechner  für unsere Breiten und Häuser ist der Heizfall egal. Schauen wir den Iran an die nur Kühlung und keine Heizung haben, dann wird dieser Heizfall interessant. Daher bin ich für Flexibilität.

@ghorwin
Infiltration ist ein anderes Modell und hier extra ausgeklammert. Soll so wie es derzeit ist eigenständig behalten werden.
Diese Modell betrifft nur die Position 2 bei dir. Man kann auch die Pos 3 in gewissen Grenzen damit abbilden.

Man muss fürs Modell 2 aber nochmal klarstellen was wir da haben wollen.
1. Reglung nach Zeitplan (um Normvorgaben zu erfüllen, bspw. 30 m3/(h*Person). 
2. Zusätzlich eine Komfortlüftung (falls zu heiß und draußen kalt genug dann Luftwechsel hochziehen)
3. Bei einer CO2 und Komfortlüftung Steuerung kommt dann beides zum Tragen. Wichtig dabei ist das ich vorher schon einen zeitplanabhängige Lüftung haben kann. Und dann on Top nochmal der Wert der ventilationMaxRate kommt. Das geht derzeit im NANDRAD nicht abzubilden.
Ich kann derzeit nur alles regeln oder nur nach Zeitplan fahren. Beides zusammen geht nicht.

Nun nochmal an alle ist die Definition von oben erstmal klar?

**Comment by Arombolosh** [comment]
Formeln:

```

n = eps * C(t) + B(t)

B(t) - Vor

```
