### ISSUE TITLE
Anzeige Component View -> Construction Preview

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#417]
Das Bild, welches im Construction Dialog existiert soll auch im Component View eingebunden werden. Die Maßkette sollte aber nicht mitgenommen werden.

Zusätzlich soll bei einer ActiveLayer-Schicht (Checkbox darunter) dieses Material schraffiert werden.
Achtung :
Es gilt jedes mal zu prüfen ob der Index der ActiveLayer noch innerhalb der Anzahl der Schichten ist.

Bsp. einer nutzt eine Konstruktion mit 10 Schichten.
Die Schicht neun wird als aktive Schicht gekennzeichnet.
Falls dann die Konstruktion gewechselt wird und darin nur noch 6 Schichten sind, zeigt der ActiveLayer derzeit immernoch auf die neunte Schicht.

Das ganze ist übrigens ein Index.
Index 1 -> erste Schicht betrachtet von der A Seite aus

**Comment by Arombolosh** [comment]
prüfen

**Comment by HWFechner** [comment]
Punkt 1 ist erledigt.
