### ISSUE TITLE
Fragen zum Report

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#418]
Wie stelle ich sicher, dass immer alle Monate im Diagramm in der horizontalen Achsenbeschriftung dargestellt werden?
Hierzu ReportFrameClimateReport03 ..

Wie schalte ich die rechte Achse beim Plotten ab?
Hierzu ReportFrameClimateReport03 ..

**Comment by ghorwin** [comment]
Musst Du wie beim Therakles die Klasse ScaleDivider überschreiben und anpassen.... Schwierigkeit: hoch

**Comment by Arombolosh** [comment]
ne hab das mit heiko geklärt ... und funzt auch schon...
du bist hier net zugewiesen also raus bitte
ich brauch dich für andere fragen :)
