### ISSUE TITLE
Discuss: quantity (checking) manager

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#42]
Right now, quantity names are hardcoded in the various models when input references are created. Or, they are written as keywords in model-specific keyword lists.

For inter-model communication and user-provided quantities via schedules, we should add a checking mechanism like a quantity manager:

- a central place where all names of all quantities (scalar and vector valued) are stored, alongside their descriptions and units
- in model code where currently c-string constants are used, now constant variables are written

Discuss: we would effectively duplicate information currently provided in model-specific results and inputRef enumerations. Is this smart? Or is there a nice way to merge these two?

Alternatively, since quantity checking is most important for user-supplied data (in schedules), we might just an an keywordlist-based enumeration again that we can use during schedule checking to see if the scheduled quantities are spelled correctly and have the right unit.

**Comment by Arombolosh** [comment]
Decided: Keywordlist based enums
