### ISSUE TITLE
Verschieben von Objekten funktioniert nicht zuverlässig

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#425]
Schritte zum Reproduzieren:

Testprojekt (Anhang) einladen

- Geometry Modus > Edit
- ich setze das lokale Koordinatensystem an einen unteren Eckpunkt, bspw. (-5, 10, -12.5)

- ich wähle "Move to world coordinates"
- ich tippe bei z "0" ein -> Quader wird optisch verschoben
- ich klicke irgendwoanders hin oder drücke Escape -> Quader ist wieder an originaler Position

--> eindeutig ein Bug
[Test.vicus.zip](https://github.com/ghorwin/SIM-VICUS/files/7790607/Test.vicus.zip)

**Comment by hirseboy** [comment]
Das müssen wir mal diskutieren. Bisher war der work-flow Eingabe der neuen Position(Rotation,Bounding Box, etc.) und anschließend Eingabe oder Tab wenden die Änderungen an. Aber ich finde das ehrlich gesagt auch nicht gut so. Eigentlich sollte bei focus wechsel die Operation angewendet werden und eine Undo-Action erzeugt werden.

**Comment by hirseboy** [comment]
Habe mir das nochmal angessehen und der Fehler war ein fehlendes `std::fabs()`. 

Ist jetzt auch im master mit dem alten Code gefixt.
