### ISSUE TITLE
Anzeige für U-Wert und maximalen g-Wert im Fensterdialog hinzufügen (wenn Verglasung gewählt)

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#429]
Wenn man ein fenster auswählt u ein glazing system zuweist und das ganze nochmal macht und aber Cancel drückt statt select, dann wird das zuvor eingetragene objekt gelöscht und somit ist kein glazing system mehr zugewiesen...das ist mist, bei cancel sollte es unverändert bleiben

UND der U-Wert muss im Component Kalatol für Fenster auch angezeigt werden und g-Wert gleich mit!

UND überlegen wie dort und im GLazing katalog der U-Wert angezeigt wird, dass es nicht aussieht als wäre er editierbar in nem textfeld, aber er soll dennoch herauskopierbar für den anwender sein

**Comment by ghorwin** [comment]
Den ersten Teil kann ich nicht reproduzieren, und im Quelltext ist das eigentlich ordentlich gelöst:
```c++
	unsigned int conId = glazSysEditDialog->select(m_current->m_idGlazingSystem);
	if (conId !=  VICUS::INVALID_ID && conId != m_current->m_idGlazingSystem) {
		m_current->m_idGlazingSystem = conId;
		modelModify(); // tell model that we changed the data
	}
```

Das beschriebene Problem wurde am 29.06.2021 behoben.

Die anderen beiden Punkte kann man als FeatureRequest stehen lassen, deshalb ändere ich mal den Tickettitel.

**Comment by TriKat** [comment]
Es war im WIndow, nicht das GLazing system. dirk hats aber gefixt und eingecheckt

**Comment by Arombolosh** [comment]
negativer uwert beim fenster checken

**Comment by Arombolosh** [comment]
erledigt
