### ISSUE TITLE
Abbildung Konstruktion in Komponentenansicht fehlerhaft

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#431]
Die Beschriftung bei Bildchen der Konstruktion ist beschriftet mit "Sida A" und "Sida B" .. es müsste "Side A/B" heißen

**Comment by Arombolosh** [comment]
erledigt

**Comment by ghorwin** [comment]
Style-sheet (DarkStyle) an Konstruktionsansicht durchreichen (Schwarzer Text auf Dunkelgray ist suboptimal)
