### ISSUE TITLE
Berechnung/Eingabe der Zonen-Nutzfläche und Raumvoluminas

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#433]
Für den Export der NANDRAD-Simulation brauchen wir für jede Zone:

- Nutzfläche, wird für die Umrechnung von flächenbezogenen Lasten benötigt
- Luftvolumen, wird für Energiebilanz/CO2-Bilanzen benötigt (Umrechnung Erhaltungsgrößen zu Temperatur/Konzentrationen) und für Lasten aus Luftwechsel

Bei prismatischen Räumen ist Volumen = Grundfläche*lichte Höhe.
Bei allen anderen Räumen (auch bei  stufenförmigen Fußböden) ist die Berechnung komplizierter und nur bedingt automatisiert durchführbar.

Zudem muss noch zwischen Grundfläche = Fläche des Fußbodenpolygons und Nutzfläche unterschieden werden. D.h. Nutzfläche*Höhe wäre Falsch (Beispiel: Dachraum mit Drempelbereich, der nicht zur Nutzfläche zählt).

Daher sollte man Volumen und Nutzfläche zwingend als Nutzer manuell anpassen können. Im entsprechenden Dialog sollte es aber einen Automatismus geben, der diese Größen unter bestimmten Voraussetzungen automatisiert berechnet. Das kann auch für mehrere Zonen erfolgen.

Man müsste anhand von Kriterien (zur Vermeidung von Berechnungsfehlern) prüfen, ob die einfache Formeln Gültigkeit haben:

```
Nutzfläche = Fußbodenfläche
Volumen = Fläche des Fußbodenfläche * Höhe einer Wand
```

Zu klären wäre weiterhin: - wie bestimmt man die Fußbodenfläche und wie bestimmt man die Raumhöhe (was ist eine Wand, und was die Höhe).

Ganz eng könnte man folgende Regeln aufstellen:

- Fußbodenfläche ist die Summe aller Polygonflächen mit Normalenvektor nahezu 0,0,-1 *und* die nahezu die gleichen z-Werte der Vertexe haben (keine Stufen in der Fußbodenfläche)
- Fußbodenpolygon ist die Fläche des Raumes mit den niedrigsten z-Werten (vermeide Fehler, wenn Deckenpolygon falsch herum gedreht ist)
- eine gültige Wandfläche steht nahezu senkrecht auf dem Fußbodenpolygon und hat 2 Vertexe mit gleicher z-Koordinate die != Fußboden-z-Koordinate ist

Falls die automatische Aktualisierung der Fußbodenflächen nicht möglich ist, muss der Anwender diese manuell eingeben können. Dafür gibt es ein neues Propertywidget "Zone properties":

In diesem Widget gibt es oben eine Tabelle mit Zonen - jeweils eine kann angeklickt werden und wird in der Scene farblich hervorgehoben (wie im Geisterhausmodus, sodass man auch innenliegende Zonen sieht).
Im underen Teil des Widgets werden die Zoneneigenschaften direkt editierbar angezeigt, und dort gibt es auch den Button "Updated zone volume/area"

Skizze zum Dialog liefert Dirk...

**Comment by ghorwin** [comment]
Designvorschlag für Zoneneigenschaftstabelle von Dirk:

![image](https://user-images.githubusercontent.com/6892676/148679899-0a4f5446-d2ef-4b11-8287-eda2ddd59ab4.png)

**Comment by Arombolosh** [comment]
muss noch geprüft werden

**Comment by Arombolosh** [comment]
wurde von anne geprüft und für gut befunden
