### ISSUE TITLE
NANDRAD-Export von personenbezogenen Lasten

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#434]
Personenbezogene Lasten werden in VICUS templatespezifisch definiert und abgelegt. Der NANDRAD-Export erzeugt derzeit Objektlisten für alle Zonen, die das entsprechende Template referenzieren. Dabei können folgende Situationen eintreten:

1.) Ein inhaltlich gleicher Schedule wird mehrfach verwendet -> ist gelöst.
2.) Ein Template erzeugt mehrere Schedules -> ist teilweise ungelöst. 

2.) kann auftreten, wenn die Personenanwesenheit absolut gegeben ist. Da NANDRAD aber flächenbezogene Daten verlangt, muss für jede Zonengrundfläche ein eigener Schedule erzeugt werden (ist gelöst). Dieser muss eine Objektliste mit individuellem Namen referenziert werden (ist ungelöst). Zur Erstellung und Benennung der Objektlisten ist der Templatename also nicht mehr ausreichend, sondern es muss eine Namenskonvention für Mehrfachreferenzierung desselben Templates eingeführt werden.
Gern in DIskussion.

**Comment by ghorwin** [comment]
Beispiel (@Anne: bitte korrigieren, falls ich das falsch verstanden habe)

im VICUS Modell:

- 2 Zonen mit jeweils individuelle Zonentemplates

Zone 1: 20 m2, -> Personenlastschedule gegeben in 4 Personen absolut
Zone 2: 10 m2, -> Personenzahl gegeben in 5 m2/Person

- Jetzt wird aus jeder VICUS-Schedule eine NANDRAD-Schedule gemacht
- Unter Annahme gleicher Zeittaktung (d.h. Wochentagszuordnung/Tageszyklen identisch) entstehen nun 2 gleiche NANDRAD-Schedules mit je 0.2 Personen/m2
- Nun soll aber in der finalen NANDRAD-Datei nur ein Schedule geschrieben werden, und die Objektliste enthält beide Zonen
