### ISSUE TITLE
Übetragung Ausgaben VICUS -> Nandrad fehlerhaft?

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#435]
Problem: Ich kann keine custom Outputs für Netzwerke setzen.

siehe 
VICUS_Project.cpp Z1045: 
d.m_quantity = def.m_sourceObjectType + "." + def.m_quantity;

Damit steht bei mir "NetworkElement.FluidTemperature" als quantity im Nandrad Projekt. Von Nandrad wird aber erwartet "FluidTemperature".
Für mich funktioniert also: 
d.m_quantity = def.m_quantity;

Ist das bei den Gebäuden anders?

**Comment by ghorwin** [comment]
Beispiel: Zone.CompleteThermalLoad und ConstructionInstance.ElementTemperature[0]  (vektorwertig)

VICUS-Projekt:

```xml
<OutputDefinition quantity="CompleteThermalLoad" sourceObjectType="Zone">
	<TimeType>Mean</TimeType>
	<SourceObjectIds>243</SourceObjectIds>
	<GridName>Hourly values</GridName>
</OutputDefinition>
<OutputDefinition quantity="ElementTemperature[0]" sourceObjectType="ConstructionInstance">
	<TimeType>None</TimeType>
	<SourceObjectIds>2</SourceObjectIds>
	<GridName>Hourly values</GridName>
</OutputDefinition>
```
Generiertes NANDRAD-Projekt:

```xml
<OutputDefinition>
	<Quantity>Zone.CompleteThermalLoad</Quantity>
	<TimeType>Mean</TimeType>
	<GridName>Hourly values</GridName>
</OutputDefinition>
<OutputDefinition>
	<Quantity>ConstructionInstance.ElementTemperature[0]</Quantity>
	<TimeType>None</TimeType>
	<GridName>Hourly values</GridName>
</OutputDefinition>
```

2 Bugs:

- Präfix für Objekttyp ist falsch
- `ObjectListName`-Element fehlt

@Hauke: versuchst Du bitte gleich mal selbst, das zu reparieren? Der Quelltext müsste recht einfach zu lesen sein.
