### ISSUE TITLE
Erweiterung WireFrame/Transform3D-Klasse um Surfaces mit veränderter Geometrie

### ISSUE THREAD

**Issue by hirseboy** [ghorwin/SIM-VICUS#437]
Um Objekte mit lokalem Koordinatensystem skalieren zu können, ist die derzeitige Datenhaltung nicht ausreichend.

Da die Transformationen vom Transform3D Objekt gehalten und durch das WireFrame-Objekt bei Geometrie-Änderungen als Vorschau angezeigt werden, muss die Transform3D-Klasse bzw. die WireFrame-Klasse neben der Anwendung von globaler Skalierung/Rotation/Translation ebenso eine Funktionalität erhalten, womit Surface-Objekte mit geänderter Geometrie direkt übergeben werden können.

Damit sind vorberechnete Transformations-Operationen mit lokalem Koordinatensystem direkt durchführbar.

Konkret bedeutet dies folgende Änderungen:

- [ ] Das Wireframe-Objekt verwendet keine eigene Transformationsmatrix mehr und damit auch nur noch den reguläre Shader
- [ ] Bei Verwendung jeglicher Transformationsoperationen im Propertywidget wird das Wireframe-Objekt manuell aktualisiert, wobei die kopierten Vertexes jeweils ausgehend von der unveränderten VICUS-Projektstruktur transformiert werden. 
- [ ] Dafür muss lokal im Propertywidget eine Kopie der aktuell gewählten Geometrie gehalten werden.
- [ ] Für jede Transformationsoperation (Translation/Rotation/Skalierung) muss die Veränderung der Vertexes in der kopierten Geometrie erfolgen (via CPU) und danach muss das Wireframe-Objekt aktualisiert werden.
- [ ] Bei Bestätigung der Transformationsoperation werden die bereits transformierten lokalen Geometrien aus dem Propertywidget in das Projekt via Undo-Action übernommen.

**Comment by ghorwin** [comment]
Implementierung:

`WireFrameObject::m_selectedObjects` hält Adressen aller aktuell ausgewählten Objekte. Bei jedem Aufruf von `updateBuffers()` wird diese Liste aktualisiert. Das passiert _unabhängig_ vom EditGeometry-Widget!.

Daher muss das WireFrameObject ausgewählte Geometrie basierend auf den Daten in VICUS::Project rendern.

Veränderte Geometrie:

- wird im EditGeometry-Widget die Geometrie manipuliert, so muss das WireFrameObject wissen, dass es beim nächsten `updateBuffers` die Geometriedaten _nicht_ aus dem Projekt ziehen soll, sondern stattdessen aus dem EditGeometry-Widget.

Optionen:

- veränderte Geometrie wird im WireFrameObjekt-selbst gehalten
-  EditGeometry-Widget stellt eine Liste von veränderten Geometriedaten zur Verfügung zum Abruf für das Wireframe-Objekt

**Comment by hirseboy** [comment]
Beide Optionen sind für mich ok, aber mir persönlich gefällt Option 1 besser.

**Comment by ghorwin** [comment]
Siehe 8422d895
