### ISSUE TITLE
spezielles style sheet für read only line edits

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#439]
reduziertes style sheet erstellen für line edits dabei den hover (rahmen) ausschalten und dieses style sheet jedem read only line edit zuweisen

**Comment by Arombolosh** [comment]
für white theme müssen die farbwerte angepasst werden

im constructor einbinden

**Comment by ghorwin** [comment]
Hi Stephan,

 

Du scheinst eine sehr neue Qt-Creator-Version zu benutzen. Jedenfalls trägt diese beim Bearbeiten von ui-Dateien (siehe Dein Commit-unten) XML-Tags ein, die unter Qt 5.11 zu Compilefehlern führen. Deshalb wirst Du rote Lampen beim Qt-Bauen im Jenkins sehen. Lösung? Vielleicht eine ältere Qt Creator-Version manuell installieren?

 

-Andreas

 
 

Gesendet: Mittwoch, 02. Februar 2022 um 17:11 Uhr
Von: "hirseboy" ***@***.***>
An: "ghorwin/SIM-VICUS" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: Re: [ghorwin/SIM-VICUS] spezielles style sheet für read only line edits (Issue #439)


 

Closed #439 via 7c88312.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hirseboy** [comment]
Bei mir hat der Online-Installer nur die Version 6.0.1 installieren lassen. Aber dann schaue ich mal, dass ich auf 5 oder 4.11 oder sowas downgrade.
