### ISSUE TITLE
Lege Mappingtabellen beim nandrad Projektexport an

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#441]
- [ ] Raum-IDs
- [ ] Geschoss
- [ ] Gebäude
- [ ] Optional, Wände

Benötigt für automatisierte Auswertung/Rückführung der Ergebnisse nach IFC und Visualisierung in SIM-VICUS Oberfläche

**Comment by Arombolosh** [comment]
Ids kann ich demnach nur von Räumen und/oder Wänden (ConstructionInstances) speichern.
Geschosse und Gebäude gibs im NANDRAD ja nicht.

**Comment by Arombolosh** [comment]
so es kommt jetzt eine Datei heraus aus der man die beiden oben genannten Sachen wieder herauslesen kann.
