### ISSUE TITLE
Automatische Ausrichtung von Fläche ausgehend von Raumzuordnungen (Igelerstellung)

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#448]
- Schleife über alle Räume

  + Mittelpunkt aller Vertexes von allen zugeordneten Flächen berechnen (=Volumetrischer Mittelpunkt)
  + Schleife über alle Flächen

      * Skalarprodukt Normalenvektor der Fläche und Verbindung von Flächenmittelpunkt zum Raummittelpunkt berechnen; wenn Ergebnis negativ (="Fläche schaut zum Raum") Normalenvektor invertieren

**Comment by Arombolosh** [comment]
Das ist Schwachsinn
Nur so das Ding funktioniert nicht:
Beispiel:
Ein Würfel mit 9 m Kantenlänge 
Darin schwebt ein anderer Raum (Würfel) mit 3 m Kantenlänge
Schon funktionierts net.
Ebenso bei L- oder U-Räumen.

**Comment by ghorwin** [comment]
Also, der Algorithmus würde bestimmt bei 90% aller typischer Räume funktionieren. Da wo der Algorithmus nicht funktioniert, flippt man die Seiten eben manuell. Grundsätzlich würde man aber recht einfach eine "Grundordnung" schaffen.

**Comment by Arombolosh** [comment]
Beim Import gibt es eine Flächennormalendefinition.
Sollte diese falsch sein, kann man alles markieren dann FLIP drücken und hat bei einer falschen Definition dann alles schnell gedreht.
Daher stecken wir hier erstmal keine Arbeit rein.
