### ISSUE TITLE
Datenbankelemente verschwinden beim IDF Import

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#449]
ich hab ne test idf in der alles drin ist: Verknüpfungen, Konstruktionen, Materialien, etc . etc.
Wenn ich die importiere und auf "merge project" klicke bekommt er die geometrie richtig, aber die verknüpfungen sind weg. Ebenso sind die konstruktionen u materialien zwar in den datenbanken, aber nichtmehr zugewiesen im modell
Importiere ich es nun mit" save as new project" bekommt er die geometrie richtig, die verknüpfungen sind da, ABER jetzt wirds abenteuerlich: konstruktionen u materialien sind nun nicht mehr in den datenbanken

Bitte sofort reparieren, sonst sind wir arbeitsunfähig. IDF Import muss sitzen!

**Comment by ghorwin** [comment]
Am IDF Import wurde ewig nichts geändert - muss also am Datenbankmanagement liegen. Ich brauch eine überschaubare Test-IDF.

**Comment by ghorwin** [comment]
Ah, gefunden:

SVMainWindow.cpp:1010
```c++
			if (!m_importIDFDialog->m_importedProject.m_buildings.empty()) {
				// TODO : Dirk, merge databases into UI DB
				// TODO : Dirk, import all project data with overwriting tests
```
