### ISSUE TITLE
HiDPI Scaling Problems

### ISSUE THREAD

**Issue by hirseboy** [ghorwin/SIM-VICUS#451]
Ich habe mal etwas nachgesucht, weil bei mir die Einträge im TreeWidget als auch die Icons immer so klein sind bei HiDPI.

Und das Problem liegt vor allem darin, dass das Attribut `QApplication::setAttribute(Qt::AA_EnableHighDpiScaling)` in der `main.cpp`
nicht gesetzt ist. Wenn ich das setze, dann sind bei mir eigentlich alle Probleme auf meinem 4K-Bildschirm weg.

Können wir das standardmäßig setzen? Oder soll das ein _Flag_ in den Einstellungen werden?

**Comment by ghorwin** [comment]
Bitte standardmäßig setzen:

```
QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
// eventuell auch
QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
```

**Comment by hirseboy** [comment]
Closed with 1d2e2d10

**Comment by hirseboy** [comment]
Update Icons so that all are HighDPI

**Comment by Arombolosh** [comment]
also bei mir ist im sim vicus jetzt das ui total groß
zudem geht das  selektieren nicht mehr ordentlich
drehen ist auch kaputt
 der drehpunkt wird weit ab von der eigentlichen mouse position gesetzt

icons sind riesig name sind dafür klein
wer auch immer da was gemacht hat bitte mal mir bescheid geben

**Comment by hirseboy** [comment]
Kann eigentlich nicht sein. 

Habs unter Linux ohne Skalierung getestet. Hast du den letzten Commit ausgecheckt?
