### ISSUE TITLE
Messen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#453]
Im Parametrierungsmodus geht das messen nicht da das lokale Mauskoordinatensystem fehlt.
Somit ist Treffen nicht möglich.

Bitte mal noch umbauen sodass es nur im Geo-Modus geht.

**Comment by ghorwin** [comment]
Uh oh, aufpassen. An der Existenz/SIchtbarkeit des lokalen Koordinatensystems hängen einige andere Funktionen.
@Stephan: bitte mal schauen, wo die Sichtbarkeit des LKS geprüft wird. 

... oder einfach anpassen und ausprobieren, wo's knallt :-)
