### ISSUE TITLE
Ausgaben

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#454]
Beim Einstellen der VentilationRate unter Model (wir haben viele Ausgaben hier) wird der Hinzufügen-Button (Plus-Button) nicht aktiviert.
Zu testen beim Kiebitzsee Projekt

**Comment by ghorwin** [comment]
Wann sollte der Button aktiviert werden? Wenn man in der Liste der verfügbaren Ausgaben eine Zeile ausgewählt hat? Was passiert, wenn man andere Ausgaben auswählt?

**Comment by ghorwin** [comment]
@Stephan: falls Du es reproduzieren kannst, die Funktion `SVSimulationOutputOptions::on_listWidgetObjectIDs_itemSelectionChanged()` debuggen, hier wird der Enabled-Zustand gesetzt.
