### ISSUE TITLE
Outputs für Simu klappt noch nicht

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#455]
Wenn man die Ventilation Rate für mehere Zonen einstellen will funktioniert das noch nicht. Da müsste er oben Einzelobjekte anlegen und nicht alles in eine Liste schreiben, das macht er aber und die Liste funtioniert nicht.

**Comment by ghorwin** [comment]
Fehler in der Darstellung im Ausgabe-Definitionswidget - NANDRAD verarbeitet die erstellten Definitionen problemlos.
