### ISSUE TITLE
Error messages from model initialization are not shown, es passiert einfach nichts!

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#460]
Anne: ich kann dir ein Beispiel mit Netzwerk geben. Wenn der schedule z.B. nicht gefunden wird kommt keine Fehlermeldung!

**Comment by Labauke** [comment]
[ThermoHydraulicNetworkHeatPumpIdealSource.txt](https://github.com/ghorwin/SIM-VICUS/files/8030451/ThermoHydraulicNetworkHeatPumpIdealSource.txt)

Das ist eine NANDRAD Datei, einfach in .nandrad umbenennen. Ist ein Regressionstest wo der Schedule fehlt.

**Comment by hirseboy** [comment]
same as #537
