### ISSUE TITLE
Review Zonenvolumenberechnung: Formel prüfen

### ISSUE THREAD

**Issue by KnutKnudson** [ghorwin/SIM-VICUS#461]
Ich kann die Berechnung in VICUS::Room::calculateVolume nicht anerkennen. Bei meinem Nachrechnen kommt etwas Anderes heraus. Ich bitte von daher auf Prüfung, gern auch Korrektur meiner ANmerkungen.
Das Dókument befindet sich eingecheckt unter \doc\SIM-VICUS-Discussion\Raumvolumenberechnung.lyx

**Comment by TriKat** [comment]
geprüft siehe #458
