### ISSUE TITLE
Import-Plugin workflow

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#462]
Workflow beim Import von Projekten via Plugin:

- importiertes Projekt ist in eigener Kopie von `VICUS::Project` einschließlich embedded DB enthalten
- Projekt-IDs werden mittels aufruf von `updatePointers()` geprüft
- Projekt wird mit `fixProject()` repariert (entfernen unbenutzer CI and subsurface-CI)

Kein Projekt geladen:

- importiertes Projekt wird via `SVProjectHandler::newProject()` als neues Projekt verwenden
- embedded DB des importierten Projekts wird in Datenbank importiert, via `SVProjectHandler::importEmbeddedDB()`
- abschließend wird eine UndoAction AllModified gesendet

Projekt bereits geladen:

- importiertes Projekt wird via `SVProjectHandler::importProject()` in existierendes Projekt eingefügt; dies ruft automatisch `SVProjectHandler::importEmbeddedDB()` auf; Funktion ruft automatisch ModifyProject-UndoAction auf

*Hinweis*: Die parallel existierende Funktion `importProjectFromPlugin()` wird eigentlich nicht benötigt und funktioniert derzeit auch nicht korrekt (ID-Duplikationen...)

**Comment by HWFechner** [comment]
import project for plugins now uses same function is idf import. importFromPlugins function removed
