### ISSUE TITLE
Rendering when project imported via plugin

### ISSUE THREAD

**Issue by hirseboy** [ghorwin/SIM-VICUS#465]
> AN: was geht nicht? Möglicherweise ein Duplikat von #462

**Comment by hirseboy** [comment]
was war der Fehler?

**Comment by ghorwin** [comment]
Keiner, zumindest nichts, was mit dem "Rendering" zu tun hat. Nach dem Import wird immer die gesamte Scene neu erstellt (AllModified-Undo-Action)
