### ISSUE TITLE
Pick Zone Height

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#466]
Wenn man einen Raum baut mit rechtsdrehenden Polygon wird er nach oben extrudiert.
Wird die Drehung vertauscht wird er nach unten extrudiert. 
So weit so gut.

Stellt man aber "Pick Zone Height" ein sollte dann die Höhe auch in die Richtung zeigen wie die Höhe abgegriffen wird?
Derzeit bleibt der Vorrang durch die Normalenvektoren bei der Fußbodenfläche.
Wie wollen wir das halten?

Meinungen bitte.

**Comment by ghorwin** [comment]
Erledigt sich mit Umstellung der Polygon-Behandlung auf 2D-Polygone: dann spielt die Drehrichtung keine Rolle mehr und der Normalenvektor wird immer nach "oben" (Skalarprodukt mit Ebenen-Normale > 0) eingestellt.
