### ISSUE TITLE
Ausgeblendete Objekte werden durch select in der szene angewählt

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#478]
Ich glaub bei deinen fenstern selektieren ist was falsch gelaufen

man kann zwar die fenster (die eingeblendet sind) anwählen aber auch ausgeblendet objekte werden nun angewählt.
also wenn eine decke ausgeblendet ist und man selektiert die unsichtbare decke dann wird sie angewählt

**Comment by ghorwin** [comment]
Grundsätzlich funktioniert das richtig:

- Ausgeblendete Objekte können nicht angewählt und markiert werden
- im Navigationsbaum ist die "Ausgewählt" Eigenschaft und abhängig von der "Sichtbar"-Eigenschaft umschaltbar

Klarstellung wird für folgendes Verhalten benötigt:

Wenn Fenster ausgeblendet sind, und man klickt (selektiert) die übergeordnete Fläche, sollen dann die Fenster mit ausgewählt werden oder nicht?

**Comment by hirseboy** [comment]
> Wenn Fenster ausgeblendet sind, und man klickt (selektiert) die übergeordnete Fläche, sollen dann die Fenster mit ausgewählt werden oder nicht?

Fenster würde ich in dem Falle dann mit auswählen.

**Comment by hirseboy** [comment]
Is already fixed as needed
