### ISSUE TITLE
Fenster Database kleine meckerei

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#479]
Wie bei Konstruktionen sollten auch hier im Modell verbaute Komponenten fett markiert werden in der auswahhl (konsistenz)

**Comment by TriKat** [comment]
Und Button "assign selected component" einfügen noch bitte (konsistenz .. wie bei opakem konstruktionsdialog)

**Comment by Labauke** [comment]
Sollte jetzt gehen
