### ISSUE TITLE
Fragen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#49]
in outputs dokumentation ist ein satz nicht zu ende geschrieben ToDo andreas.

equesting energy supplied to layer in construction instance (floor heating): object list must reference construction instance, variable name must reference heat source + index of heat source (if several in construction): <Quantity>HeatSource[1]</Quantity> (first heat source in layer, counting from side A in construction, see Heat sources in constructions/layers).

sicher das hier die erste schicht der index 1 verwendet wird?

**Comment by ghorwin** [comment]
Addressierung der Schichten wird final geklärt, wenn das Schichtheizungsmodell implementiert ist.
