### ISSUE TITLE
Beim Export der NANDRAD Dateien aus SIM-VICUS, die jeweilige Objekt-ID vor den Displaynamen setzen, also bspw. "15: Wohnzimmer" für SIM-VICUS Room(id=15, displayName="Wohnzimmer")

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#492]
Die Output-Mapping Dateien werden derzeit vom NANDRAD-Modell automatisch geschrieben und fest mit dem Displaynamen verknüpft. Diese Regelung als fix anzunehmen, ist ungünstig. Ein möglicher Anwendungsfall ist das Schreiben von Reports bei uneindeutigen Raum-Displaynamen. In diesem Fall sind Ergebnisse nicht mehr den Räumen zuordenbar.

1.) NANDRAD Ausgaben sollten id-basiert bleiben. Automatisierte Auswertbarkeit bleibt dadurch bestehen.
2.) Für Ingenieure sollte ein Ersetzungsalgorithmus außerhalb von NANDRAD implementiert werden, der die Ids mit den Diisplaynamen nach der Mapping-Tabelle ersetzen kann. Dafür ist eine Dateikopie anjzulegen.
3.) De Mapping-Tabellen sind flexibler und erlauben alternative Festlegungen und sollten nicht in NANDRAD, sondern, im NANDRAD-Datenexport geschrieben werden.

Beispiel
Id                 DisplayName
Zone(id=1)  RaumA
Zone(id=2)  RaumA

Dies ist im NANDRAD als auch im SIM-VICUS möglich. Werden nun die Namen gemappt ist keine eindeutige Auswertung mehr möglich.
Daher nur mit IDs arbeiten.
Die Architekten haben leider solche Ideen.

**Comment by ghorwin** [comment]
Einfacher Umbau:

NM_NandradModel.cpp:371:

```c++
// Ersetzung für alles ausschalten
m_outputHandler->writeOutputs(t_out, t_secondsOfYear, std::map<std::string, std::string>());
```

**Comment by ghorwin** [comment]
Die Datei `var/objectref_substitutions.txt` enthält die Übersetzungen und kann dann für ein externes Script genutzt werden. Eigentlich müsste man aus SIM-VICUS heraus keine extra Mapping-Tabelle erstellen - lediglich beim NANDRAD-Export geeignete Display-Namen generieren.

Es spricht eigentlich auch nichts dagegen, beim NANDRAD-Export die nativen Displaynamen um zusätzliche Attribute für die automatische Auswertung zu erweitern, also z.B.:

```c++
zone.m_displayname = IBK::FormatString("%1:%2").arg(zone.m_id).arg(zone.m_displayname).str();
```
So spart man sich zusätzlichen Programmieraufwand für ein extra Tool.

**Comment by Labauke** [comment]
`Es spricht eigentlich auch nichts dagegen, beim NANDRAD-Export die nativen Displaynamen um zusätzliche Attribute für die automatische Auswertung zu erweitern, also z.B.:`

Genau so mach ich es auch bei den Netzwerken. Einfach immer den Displaynamen UND die ID in den neuen NANDRAD Displaynamen schreiben. Damit kann man jederzeit automatisiert auswerten und es ist trotzdem noch für mich lesbar.

Die automatische Umbenennung würde ich also BITTE drin lassen. Bei einigen GB Ausgabedateien kann hat ein externes Script viele Nachteile:
- braucht möglicherweise lange
- man kann nicht während der Simulation auswerten!
- Dateien kopieren bei großen Ausgabedateien ist keine so tolle Idee

**Comment by ghorwin** [comment]
Ok, dann ist das so entschieden: das Mapping bleibt drin, und beim NANDRAD-Dateiexport wird einfach die ID "gepräfixt".
Ich ändere den Titel des Tickets entsprechend.

**Comment by ghorwin** [comment]
Ein Beispiel zur Klarstellung:

**IST-Zustand**

Zone in VICUS-Modell:
```
  Zonenname: "Diele", Vollständig: "Imported IDF Building Geometry.Default building level.Diele"
  Zonen-ID: 11
```

Generierte NANDRAD-Zonen-Definition:
```xml
<Zone id="11" displayName="Imported IDF Building Geometry.Default building level.Diele(11)" type="Active">
	<IBK:Parameter name="Area" unit="m2">18.31</IBK:Parameter>
	<IBK:Parameter name="Volume" unit="m3">47.05</IBK:Parameter>
</Zone>
```

Zeile in `objectref_substitutions.txt` :

```
...
Zone(id=11)	Imported IDF Building Geometry.Default building level.Diele(11)
...
```

Header in `states.tsv`:
```
Imported IDF Building Geometry.Default building level.Diele(11).AirTemperature [C]
```

Zeile in `BockwenRealPipe_mappingTable.txt`:
```
11	11	Diele	Imported IDF Building Geometry.Default building level.Diele(11)	80004	Bockwen Wohnen	18.31	47.05
```


@Dirk: Bitte jetzt die gewünschte Variante genauso dokumentieren!

**Comment by ghorwin** [comment]
Format is now: `<building>.<level>.<zone>(ID=<vicusID>)` and quantities are named 
`<building>.<level>.<zone>(ID=<vicusID>).<quantity>`  (can't have (ID=..) at end of quantity!).
