### ISSUE TITLE
Messwerkzeug

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#495]
Soll das Messwerkzeug sich immer auf globale Achsen beziehen?
Falls ja dann sollten wir das noch mit aufnehmen.
Offset (**global** deltaX,...

Falls nein dann ist die Implementierung falsch.
Derzeit wird alles auf globale Achsen bezogen.

**Comment by Arombolosh** [comment]
BUG
Wenn man den Modus verlässt ist und das Messwerkzeug noch aktiv ist, bleibt der Dialog aktiv.
Das ist noch falsch.

**Comment by Arombolosh** [comment]
Features

Wäre auch schön wenn man hier die Achsen sperren könnte.
Spätestens bei einem gedrehten Objekt mal ne Länge zu messen wird dann extrem schwer bis gar nicht möglich
Bsp. Wand 45° verdreht um z Achse
dann Fenster drin
und ich will den Abstand von Fensterkante zur wandkante wissen
Nicht messbar

**Comment by ghorwin** [comment]
Ich glaube, wir müssen das Mess-Thema nochmal kollektiv diskutieren... also was braucht man wann während der Geometrieerstellung?

**Comment by hirseboy** [comment]
Added local measurement in 84e592b3
