### ISSUE TITLE
Translation/Skalierung

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#501]
Immer auf das Lokale Koordinatensystem anwenden.
Derzeit wird das Global KS genommen (FALSCH)

**Comment by ghorwin** [comment]
Zu Diskutieren: wenn ich ein Objekt via Translation direkt platzieren möchte, dann will ich globale Koordinaten angeben.
Wenn das mal global oder mal mit dem lokalen System gehen soll, müssen wir, wie von Stephan ursprünglich vorgeschlagen, eine Wahlmöglichkeit schaffen.

Oder wir nehmen immer das lokale Koordinatensystem, und falls einer mit globalen Koordinaten arbeiten will, muss er das LKS eben in den Ursprung legen. Das wäre wahrscheinlich die einfachste und schnellste Lösung.

**Comment by ghorwin** [comment]
Bei der Skalierung wird bereits _immer_ das lokale KS genommen.
