### ISSUE TITLE
Skalierung mit gleichen Verhältnissen (Proportional)

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#502]
Eine Checkbox einführen dann wird immer nach der Eingabe alle LineEdit mit der aktuellen Eingabe gefüllt.

**Comment by ghorwin** [comment]
Wenn Checkbox dann ausblenden von zwei lineedits, und nur eine Eingabe für alle erlauben

**Comment by ghorwin** [comment]
Besser alle LineEdits lassen, dann kann man weiterhin im "Resize Geometry"-Modus die Zielgröße als DX,DY, oder DZ angeben. Man muss dann nach Berechnung des Skalierungsfaktors eben die anderen Größen in den LineEdits anpassen.
