### ISSUE TITLE
Der Knotenpunkt Verschattung braucht eine Lampe für alle

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#505]
Der Knotenpunkt Obstacles im Navigationsbaum muss auch eine Lampe und eine checkbox genau wie bei den Gebäuden/Etagen/Räumen

Damit sollen alle Verschattung (de-)selektiert oder ein-/ausgeblendet werden können

**Comment by ghorwin** [comment]
Welcher Knotenpunkt "Verschattung"? Habt Ihr hier schon was programmiert, was ich nicht kenne? :-)
