### ISSUE TITLE
map als Datenstruktur für Codegenerator

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#507]
ich müsste eine Struktur in der Form map< unsigned int, std::vector<unsigned int> > mit dem Code Generator schreiben, lesen.

**Comment by ghorwin** [comment]
Kann man machen, man könnte aber auch einfach eine Klasse "IDVectorMap" schreiben, welche dann manuell read/write implementiert. Den Code-Generator für derart komplexe Datentypen zu erweitern, würde ich nur machen, wenn sowas häufiger gebraucht wird. Beim Einlesen wird es auch schwierig mit der Prüfung, z.B. sollen alle Vektoren die gleiche Längen haben oder flexibel?

Vorschlag für die Serialisierung:
```c++
// serialisiert wird
IDVectorMap m_blubb;
```

```xml
<IDVectorMap name="blubb" count="15">
  <IDVector id="15">1 4 5 6 3 2</IDVector>
  <IDVector id="25">1 4 5 6 3 2</IDVector>
  <IDVector id="30">1 4 5 6 3 2</IDVector>
  ...
  <IDVector id="255">1 4 5 6 3 2</IDVector>
<IDVectorMap>
```

**Comment by Labauke** [comment]
done
