### ISSUE TITLE
Aktualisierung nach Punkteingabe über das lineedit feld geht nicht

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#510]
bei der erstellung von geometriekörpern/-flächen fehlt die aktualisierung der szene.
man gib beispielsweise ein punkt über den mausklick vor (0|0)
anschließend gibt man im lineedit unten links die koordinaten in eine richtung ein bspw. 10 --> daraus entsteht ein neuer punkt (10|0) in der punktliste
im szenenmenü wird erst eine aktualisierung durchgeführt wenn die maus bewegt wird.

**Comment by hirseboy** [comment]
Fixed
