### ISSUE TITLE
Verschieben von Flächen (Translation)

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#511]
nach Bestätigung der Verschiebung von Flächen fehlt ein update.
Nach Anwendung wird die Fläche wieder an die ehemalige Ursprungsposition zurückgesetzt.
Wird das Projekt dann gespeichert und neu geladen ist die Fläche aber an der richtigen Stelle.

**Comment by ghorwin** [comment]
Kann das bestätigen, ist aber seltsam... hab da noch keine Erklärung für.
