### ISSUE TITLE
Mauszeiger und tatsächliche Position verschoben

### ISSUE THREAD

**Issue by beajifu** [ghorwin/SIM-VICUS#512]
Der Mauszeiger war ein Stück entfernt von der tatsächlichen Position in der GUI, weswegen es schwierig war Elemente zu selektieren. Ich konnte das Problem lösen in dem ich unter Einstellungen > Theme  den Haken für 'Use Scaling for high resolution displays' rausgenommen habe. Ich habe die Version 0.8 für Windows. Mein Bildschirm nutzt eine Auflösung von 2560x1440. Scheinbar gibt es ein Problem mit der Skalierungsfunktion.

**Comment by Labauke** [comment]
Das Problem ist bekannt. Tritt bei mir immer dann auf wenn ich auf 2 Bildschirmen arbeite. Beim Tutorial kam das natürlich schön zum Vorschein.

**Comment by ghorwin** [comment]
Ich benutze selbst die Skalierung auch nicht - ist nicht ganz klar, warum das bei einigen Auflösungen Probleme macht. Scheint auch platformabhängig zu sein.

**Comment by Labauke** [comment]
Ohne Skalierung funktioniert es tatsächlich. Allerdings sind die Symbole und Schriften auf einem 4K Monitor dann schon sehr klein.

**Comment by hirseboy** [comment]
Problem wird sein:
Beim start von SIM-VICUS wird ein Skalierungsfaktor gesetzt, der aus Windows ausgelesen wird. Windows kann an sich unterschiedliche Skalierungsfaktoren je Bildschirm haben. Ziehe ich jetzt SIM-VICUS auf einen anderen Bildschirm, ändert sich der Skalierungsfaktor, dieser wird aber in SIM-VICUS nicht aktualisiert. Ich schaue mir noch mal das Problem an und fixe das.

**Comment by ghorwin** [comment]
Bitte mal in einer früheren Version testen (checkout des Standes von vor ein paar Wochen) und schauen, ob eine zwischenzeitliche Änderung dieses Verhalten bewirkt hat

**Comment by ghorwin** [comment]
Das mit dem Speichern-Zoom und danach fehlerhaftem Mouse-Positionsverhalten kann ich bestätigen (Dual-Monitor, 2. Monitor mit 125%, 2560x1440).

Die SVMainWindow::moveEvent() hatte noch ein paar Bugs, da bin ich noch dran. Jedenfalls hat die Variante:

```c++
void SVMainWindow::moveEvent(QMoveEvent *event) {
	QMainWindow::moveEvent(event);
	SVViewStateHandler::instance().m_geometryView->moveMeasurementWidget();
	double windowRatio = window()->windowHandle()->devicePixelRatio();
	SVSettings::instance().m_ratio = windowRatio;
}
```

unter Windows und Linux sauber funktioniert. D.h. beim Verschieben des Fensters von Bildschirm 1 (eingebaut, 1920x1080, 100%) auf Bildschirm 2 (extern HDMI, 2560x1440, 125%) wird ungefähr wenn das Fenster mittig zwischen den Bildschirmen ist, das `window()->windowHandle()->devicePixelRatio()` von 1 auf 1.25 umgeschaltet und das Fenster und alle Elemente skalieren richtig. Ich kann nach dem Verschieben (hin und her) jeweils exakt Elemente auswählen. 

Offensichtlich ist die Verwendung der Screen-Eigenschaft falsch, d.h. man nimmt besser die Eigenschaften des Hauptfensters.

Das mit dem Speicher debugge ich noch.

**Comment by ghorwin** [comment]
Scale-beim-Speichern-Problem lag a, falschen Viewport-Update in `SceneView::dumpScreenshot`... hab das repariert.

Der ganze Code in moveEvent() ist sinnlos, da ja bereits `onScreenChanged()` den Skalierungsfaktor neu setzt - hab das alles rausgeschmissen.

Bei mir funktioniert das jetzt zuverlässig unter Windows - zwei Bildschirme mit unterschiedlicher Skalierung und Auflösung, high-resolution-scaling ist an. 

Bitte mal testen und ggfs. das Ticket wieder öffnen, wenn sich das Problem nochmal zeigt/reproduzieren lässt!
