### ISSUE TITLE
IFC Import plugin needs to be added to repository

### ISSUE THREAD

**Issue by hirseboy** [ghorwin/SIM-VICUS#516]
- [ ] IFC-PlugIn needs to be compiled in Linux
- [ ] GUI in SIM-VICUS for parametrisation of import needs to be added
- [ ] Add some examples

**Comment by ghorwin** [comment]
IFC-Import-Plugin bleibt extern. Schnittstelle zur UI-Integration muss noch definiert werden.

**Comment by ghorwin** [comment]
Hängt mit PluginManager-Entwicklung zusammen... -> Duplikat
