### ISSUE TITLE
ViewState wechseln nach Änderung der Auswahl ? Brauche Input

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#520]
Es gab bisher die Funktion `SVPropModeSelectionWidget::selectionChanged()`, die ausgelöst durch Änderung der Auswahl eine andere PropertyPage zeigt. 
z.B. wenn ich auf ein Rohr klicke werden rechts Rohreigenschaften gezeigt.
Das war zuletzt nur noch für Netzwerke implementiert.

Ich würde das rauswerfen, wenn niemand was dagegen hat. Auch die `SVPropModeSelectionWidget::onModified` wird entfernt.

**Comment by ghorwin** [comment]
Das `SVPropModeSelectionWidget` zeigt ja eine Auswahlliste der zu bearbeitenden Netzwerke an. Und wenn ich mich richtig erinnere, war das `selectionChanged` nur dafür da, das zur Auswahl passende Netzwerk auszuwählen.

Frage zur Benutzerführung:

- Wenn der Nutzer ein Objekt aus Netzwerk "A" auswählt, in der Kombobox aber Netzwerk "B" auswählt... welche Eigenschaften werden dann angezeigt und bei Änderung verändert? 
- Wenn ein Nutzer Objekte aus mehreren Netzwerken auswählt, was wird dann in der Kombo-Box ausgewählt und wie werden die Eigenschaften dann zugeordnet?

Ich würde - wahrscheinlich - die Kombobox "Netzwerk" entfernen und in der jeweiligen Netzwerk/Rohr-Property-Seite die Information basierend auf der aktuellen Auswahl anzeigen.

Man könnte dann auch mehrere Rohre aus mehreren Netzwerken auswählen und deren Eigenschaften gleichermaßen bearbeiten. Man müsste aber noch eine Regel einführen: was wird im Property-Widget anfänglich angezeigt, wenn man Rohre mit unterschiedlichen Eigenschaften auswählt?

**Comment by Labauke** [comment]
Ja, die Kombobox habe ich schon entfernt, zumindest für die PropertyPage. Habe es so umgesetzt wie von dir beschrieben.
