### ISSUE TITLE
Bei allen DB Elementen: Wenn sich der displayName unterscheidet sollten diese NICHT als gleich gelten oder?

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#522]
Das würde wahrscheinlich 90 % der nervigen "Remove/Merge duplicates in database" messages beim Start verhindern.

Mann kann also mehrere Konstruktionen etc. in der Database haben die sich NUR im Namen unterscheiden. Praktisch gesehen hat man das oft, wäre also sinnvoll oder?

**Comment by ghorwin** [comment]
Da fehlt mir noch etwas die langjährige Anwendungserfahrung...

Man könnte das so machen (also Displaynamen-Änderungen ignorieren), aber es gibt einen Haken:

- wenn man ein älteres Projekt öffnet und zwischenzeitlich die Datenbank bearbeitet hat und Elemente umbenannt hat, dann stimmen die Ergebnis-/Berichtsausgaben nicht mehr mit vorherigen Ausgaben überein.

Beispiel: Jemand hat vor 1 Jahr eine "Außenwand - Wassermühle, Ostwand" angelegt. Inzwischen wurde diese in einem neuen Projekt verwendet und in "Außenwand, ungedämmt, Fachwerk" umbenannt.
Öffnet man nun das alte Projekt und sucht in den Ausgaben nach der Wassermühlen-Wand, so findet man diese nicht mehr. Das kann zu Verwirrung führen.

@Dirk: Deine Meinung dazu?

**Comment by Labauke** [comment]
Ich habe das falsch geschrieben: Mein Wunsch wäre alle DB Elemente sollten als GLEICH gelten wenn sich nur der Name unterschiedet. Im Moment wird der Name auf Gleichheit geprüft.

**Comment by ghorwin** [comment]
Ja, so war mein Kommentar auch gemeint. Im Beispiel würde man das alte Projekt laden, würde _keine_ Fehlermeldung angezeigt bekommen und sucht dann vergeblich nach der alten Bezeichnung.

**Comment by hirseboy** [comment]
wird erstmal so gelassen
