### ISSUE TITLE
Valid Funktionen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#530]
Im Window Dialog stimmen die Valid Funktionen nicht.
Wenn kein Rahmen ausgewählt ist dürfen die Felder für bspw. die Rahmendicke auch nicht rot werden. (siehe Email)

Ebenso bei der Skalierung.
Wenn ich eine Ebene anklicke (die hat keine 3te Dimension) dann ist dieses Feld rot gefärbt.

**Comment by hirseboy** [comment]
Should already be fixed
