### ISSUE TITLE
Gitternetz

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#531]
Das Gitternetz wird nicht angezeigt.
Aber die Checkbox war gesetzt.
Der Fehler ist beim Laden des Projekts entstanden.

**Comment by ghorwin** [comment]
Schau ich mir an

**Comment by ghorwin** [comment]
Altlast: Seit Einführung mehrerer Gitterebenen (UI-Unterstützung fehlt noch) wird die Sichtbarkeit in den GridPlanes gesetzt. Ich entferne mal die alten Attribute
