### ISSUE TITLE
Performance Improvement: Verzögerung beim Anklicken von Flächen

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#533]
Das Problem scheint in der ´SVPropBuildingSurfaceConnectionWidget::updateUi()´ zu sein. Wenn sich nur die selection ändert muss nicht das ganze table widget neu gebaut werden. Ein entsprechendes Funktionsargument habe ich schon eingebaut. 
Die update Logik müsste man sich überlegen.

**Comment by ghorwin** [comment]
Man kann das Timing auch durch den Profiler jagen, da bekommt man dann raus, welche Funktionen tatsächlich wie lange brauchen.

Skaliert das Problem mit größeren Modellen?
