### ISSUE TITLE
Verschiebungsfehler

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#534]
Raum erstellen.
Alles markieren
Translationsmodus aktivieren
Lok. KS neu setzen an einen Eckpunkt.
Raum durch Maus verschieben.
nochmal das KS anpassen zum zweiten Verschieben.
Schupp das Objekt liegt sofort wieder im Ursprungspunkt vor dem ersten Verschieben.
Das ist irgendwie blöd.
da muss ne bessere Lösung her

**Comment by ghorwin** [comment]
schau ich mir an

**Comment by hirseboy** [comment]
Should be fixed with d770a018
