### ISSUE TITLE
Fehler in der NANDRAD Initialisierung / Simulation werden beim Start aus SIM-VICUS nicht gefangen

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#537]
Wenn man eine Simulation startet die Fehler enthält, welche nicht während der Projektgenerierung erkannt werden, dann bekommt man KEINE Fehlermeldung!

Das Terminal schliesst sich einfach, da (zumindest in Windows) der `CreateProcess()` ein success zurückgibt, obwohl der Nandrad-Solver eine `EXIT_FAILURE` zurückgibt.

Damit wird der Prozess beendet und der Terminal schliesst sich auch direkt, man hat keine Chance den Fehler zu finden, es sei denn man startet Nandrad über die Kommandozeile.

**Comment by ghorwin** [comment]
see https://stackoverflow.com/questions/9369823/how-to-get-a-sub-process-return-code

Use `GetExitCodeProcess()` aus der WinAPI -> https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess

**Comment by ghorwin** [comment]
Im Falle eines ExitCode != 0 sollte man netterweise den Log-Dialog mit dem Fehlerlog vom NANDRAD aufploppen lassen.

**Comment by Labauke** [comment]
Ist eingebaut, es wird nach Simulationsstart 3 sec gewartet um einen sinvollen Fehlerwert zu bekommen. Fehlerlog wird gezeigt
