### ISSUE TITLE
Take into account geodetic height of flow elements for calculation of absolute pressure

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#539]
Das Thema ist in der Praxis durchaus relevant, gerade bei großen Wärmenetzen, die relevante Höhenunterschiede haben.
Für geschlossene Netze hängt die berechnete Verteilung der Massenströme natürlich nicht von der geodätischen Höhe der Elemente ab. Die absoluten Drücke an den Knoten und damit auch die Druckdifferenzen aber schon, auch wenn es erstmal komisch klingt. 

Letztlich ist es einfach: für die Lösung des Gleichungssystems ist die geodätische Höhe nicht relevant. Es reicht, die Höhendifferenz jedes Knoten im Vergleich zum Referenzknoten zu bestimmen und das vor der Ausgabe auf die berechneten Drücke zu addieren.
Für NANDRAD müsste ein Map `m_nodeHeights[Id] = height` geschrieben werden.

In VICUS würde ich die Höhe jeder NetworkNode speichern.

Ich müsste dann nur wissen an welcher Stelle ich die Druckdifferenzen vor der Ausgabe uf die Knotendrücke addiere.

**Comment by Labauke** [comment]
Eine Map mit KnotenId zu Höhe in NANDRAD::HydraulicNetwork speichern.
Neue Ausgabegrößen "OutletNodeRealPressure" bzw "Inlet..." einführen. Diese in HydraulicNetworkModel::stepCompleted() aktualisieren mit den Höhen aus der Map also OutletNodeRealPressure"  = OutletNodePressure + Höhe.
Die Ausgaben in resultDescription veröffentlichen.

**Comment by ghorwin** [comment]
Druckerhöhung:

```
DeltaP_i = deltaH*rho*g
```

Aktuell haben Knoten im NANDRAD keine eigenen Eigenschaften (abgesehen von den neuen Luftströmungsnetzwerken, in denen für manche Knoten `Knoten = Zone` gilt).

Optionen:

1. Knotenlist als Datenstrukturelement hinzufügen und so zukunftsfähig Container für Knoten-Metadaten schaffen
2. Knotenhöhen als Eigenschaft des `HydraulicNetwerk` kodieren

Ich bevorzuge eigentlich die Variante 1, d.h. in der Projektdatei:

```xml
<Nodes>
  <Node id="12" height="14">
    <!-- ggfs weitere Attribute -->
  </Node>
  <Node id="14" height="16"/>
</Nodes>

<Elements>
   <HydraulicNetworkElement id="201" inletNodeId="12" outletNodeId="24" componentId="1" displayName="Pump" />
    ...
</Elements>
```

**Comment by Labauke** [comment]
Kann ich so machen. Dann kann man noch weitere Eigenschaften speichern falls es welche gibt.
Alternativ hätte ich sonst als Datentyp die Nandrad::IDVectorMap genutzt.

**Comment by ghorwin** [comment]
Ok, dann machen wir es so. Die neue Klasse "HydraulicNetworkNode" nennen, und vor m_elements einbetten als

```c++
    std::vector<HydraulicNetworkNode> m_nodes;   // XML:E

```

**Comment by Labauke** [comment]
Ist prinzipiell drin, allerdings:
@ghorwin : Die neue Ausgabe "OutletNodeAbsolutePressure" wird bei HydraulicNetworkModel::stepCompleted() geschrieben. Dabei wird einfach ein vorher berechneter Wert auf m_p->m_outletNodePressures[i] addiert.
Trotzdem ist die Differenz zwischen "OutletNodeAbsolutePressure" und "OutletNodePressure" nicht konstant! Die schwankt ein bisschen und kann schonmal +-100 Pa sein ?!

Das heißt die Outputs, wie m_p->m_outletNodePressures[i], werden nach stepCompleted() nochmal geändert ???
