### ISSUE TITLE
geoJSON import/export for networks

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#540]
Import:
Der bisherige csv-import kann einfach für das offene geoJSON Format umgeschrieben werden. Es sollen `LineString` und `Point` unterstützt werden. Der Import von zusätzlichen Eigenschaften (wie z.B. Rohrdurchmesser) ist denkbar. Dazu müsste der Wert der Eigenschaft aber gegen einen vorhandenen Rohrtyp gemappt werden. Also es müsst eine Tabelle erzeugt werden in der jeder importierte Wert (z.b. "50") der importierten Eigenschaft (z.b. "da") einem VICUS Rohrtypen zugeordnet wird.

Export:
Das berechnete Rohrsystem und Gebäude werden als geoJSON exportiert. Für Rohre wird die Eigenschaft "Außendurchmesser" mit geschrieben, so dass z.B. in QGIS ein beschrifteter 2d-Plan erstellt werden kann. Für Gebäude kann die Eigenschaft "Heizlast" mit geschrieben werden. Der Export von Simulationsergebnissen wäre aufwändiger.

**Comment by hirseboy** [comment]
Should be implemented by @Brockaaa. If not reopen it @Labauke
