### ISSUE TITLE
Verschattungsberechnung funktioniert nicht

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#547]
- Neue Hausgeometrie erstellen
- Simulationsdialog öffnen
- Klimastandord auswählen
- Verschattungsberechnung öffnen -> auf "Ausführlich" gehen
- "Berechnung" anklicken -> es kommt sofort der Bestätigungsdialog, aber die angegebene Datei existiert nicht

Hier fehlt offensichtlich noch die Fehlerbehandlung, Ausgabe in der Konsole:

```
Kann Log-Datei '/home/ghorwin/git/_IBK-Apps/SIM-VICUS/data/vicus/ShadingTest/PV_Panel/log/screenlog.txt' nicht öffnen.
```

**Comment by hirseboy** [comment]
Kann das geschlossen werden?
