### ISSUE TITLE
Austausch von Komponenten

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#552]
Beim Austausch von Komponenten werden auch die nicht dargestellten Komponenten ausgetauscht.
Ich würde die geltenden Regel für das Zuweisen von Komponenten auch hier anwenden.
Alle Konstruktionen die nicht sichtbar sind werden auch nicht getauscht.

**Comment by ghorwin** [comment]
Ja, wir sollten das konsequent so durchziehen: nur was _ausgewählt_ und _sichtbar_ ist, wird durch Änderungen im PropertyWidget beinflusst.
