### ISSUE TITLE
Geometrieerstellung 

### ISSUE THREAD

**Issue by lilouki** [ghorwin/SIM-VICUS#558]
Eingabe ins Textfeld wird bei Achsensperrung mit Buchstaben belegt 

Wenn man per Eingabe in das Textfeld XYZ bei der Geometrieerstellung die Achsensperrung (über x, y oder z) einstellen möchte, werden die Buchstaben (x, y, oder z) in das Textfeld geschrieben, es sollten nur Zahlen valide sein.

**Comment by hirseboy** [comment]
Fixed by 7020b527
