### ISSUE TITLE
Flächenobjekte einem Raum zuordnen (umordnen)

### ISSUE THREAD

**Issue by clrfl** [ghorwin/SIM-VICUS#573]
Flächenobjekte können bereits beim Erstellen einem Raum zugeordnet werden.
Es soll möglich sein, nachträglich eine Umordnung vorzunehmen.

Wo soll der Dialog dafür untergebracht werden? Die modeSelectionToolbar umfasst bisher hauptsächlich Items die unmittelbar mit der 3D Modelierung zu tun haben.

**Comment by hirseboy** [comment]
gibts eigentlich bereits im property mode unter Raumeigenschaften

**Comment by Labauke** [comment]
Soll Dirk nochmal sagen was er da wollte @Arombolosh

**Comment by hirseboy** [comment]
Bug: When already asigned surface to room is added to room, all other surfaces are skipped
