### ISSUE TITLE
Strg+F

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#575]
Beim Finden von Objekten bitte nicht direkt an das Objekt rangehen. Sondern immer die gesamte BoundingBox aller Objekte im Screen visualisieren.

Würde ich Moritz geben zum programmieren.

**Comment by hirseboy** [comment]
Jo, passt
________________________________________
Von: Arombolosh ***@***.***>
Gesendet: Freitag, 16. Dezember 2022 08:48:05
An: ghorwin/SIM-VICUS
Cc: Hirth, Stephan; Assign
Betreff: [ghorwin/SIM-VICUS] Strg+F (Issue #575)

Beim Finden von Objekten bitte nicht direkt an das Objekt rangehen. Sondern immer die gesamte BoundingBox aller Objekte im Screen visualisieren.

Würde ich Moritz geben zum programmieren.

**Comment by Labauke** [comment]
Da hat jemand meinen Code für das Finden von Netzwerkobjekten gelöscht!
Bitte in Zukunft auch an die Netzwerke denken und nicht nur an Gebäude!

**Comment by ghorwin** [comment]
Ah, ok, ..."Sondern immer die gesamte BoundingBox aller **ausgewählten** Objekte im Screen visualisieren."... so macht das Sinn. Ist auch schon so implementiert, kann also geschlossen werden.
