### ISSUE TITLE
Namen bei Sprachenwechsel Mist <new zone template>

### ISSUE THREAD

**Issue by TriKat** [ghorwin/SIM-VICUS#585]
Wenn ich ein Zonentemplate im deutschen Modus initialisiere u die Datei danach im englischen Modus einlese steht beim Zonennamen <new zone template>
sicher bei allen anderen datenbanken genauso (materialien, konstruktionen) ... 
Es sollte immer der eingegebene Eigenname angezeigt werden bzw geschaut werden ob in einer anderen sprache ein name hinterlegt ist, der nicht default ist.

**Comment by ghorwin** [comment]
Das ist eigentlich schon implementiert, d.h. der MultiLanguageString kann das:

text.string("de","en") würde einen deutschen Text zurückliefern, wenn vorhanden, sonst den englischen.

Das ist eigentlich auch im Quelltext schon so gemacht (zumindest bei etlichen DB Dialogen). In welchem Dialog genau tritt das Problem auf?

**Comment by Labauke** [comment]
Das war im Zone Properties Widget (in dem TableWidget).
Das Problem ist, dass er den englischen Namen `<new zone template>` gespeichert hat. Wird der automatisch beim Erstellen eines DB Elements gesetzt?

**Comment by ghorwin** [comment]
Ja, passiert analog zu allen anderen DB-Einträgen in:

SVDBZoneTemplateTreeModel.cpp:335:
```c++
c.m_displayName.setEncodedString("en:<new zone template>");
```

Man könnte das auch an die aktuell gewählte Sprache anpassen:

```c++
// determine currently installed locale
c.m_displayName.setEncodedStringIBK::MultiLanguageString::m_language + tr("<new zone template>").toStdString());
```

**Comment by Labauke** [comment]
Das wäre auf jeden Fall sinnvoll. Also die gerade nicht verwendete Sprache wäre dann leer oder? Das heißt bei Sprachwechsel von Deutsch nach Englisch würde ich dann den eingegebenen deutschen Namen angezeigt bekommen.

**Comment by ghorwin** [comment]
Code:

```c++
void LanguageStringEditWidget1::setString(const IBK::MultiLanguageString& str) {
	m_string = str;
	ui->lineEdit->setText(QString::fromStdString(m_string.string(m_currentLang, "en")));
}
```

Also, wenn aktuelle Strache keinen Text hat, wird automatisch Englisch verwendet. Das müsste man ändern, also z.B. in "wenn aktuelle Sprache keinen Text hat, verwende einfach die nächstbeste Sprache, wo es einen Text gibt".

Solange wird nur deutsch und englisch haben, ist das egal. Es wird erst spannend, wenn einer mal Französisch einstellt...

**Comment by ghorwin** [comment]
Was ist denn, wenn man eine französische Version benutzt, aber in `MultiLanguageString::m_language="en"` steht? Dann bekommt man eine französischen Text im englischsprachigen Eingabefeld angezeigt.

Ist denn gesichert, dass `MultiLanguageString::m_language` immer synchron mit der via Qt-Translator geladenen Programmsprache gesetzt wird?
