### ISSUE TITLE
Absturz bei Datenbanken die auf nicht in der Datei enthaltene Elemente referenzieren

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#589]
[Einraummodell_ideal.zip](https://github.com/ghorwin/SIM-VICUS/files/10536609/Einraummodell_ideal.zip)
Fehler ist in den Konstruktionen
da fehlt ein Material in der Projektdatei

Absturz ist nur unter Windows

**Comment by Labauke** [comment]
Kannst du bitte beschreiben was wie und wo abstürzt?

**Comment by hirseboy** [comment]
Nicht reproduzierbar
