### ISSUE TITLE
Ergebnisdarstellung in SIM-VICUS

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#590]
Ziel ist es die NANDRAD Ergebnisse im SIM-VICUS einzulesen und über Falschfarben in der 3d Szene darzustellen. Hier der Entwurf

![Konzept_Results](https://user-images.githubusercontent.com/37376091/217240338-237a165e-cbc5-4a51-aa61-4c72af9d21ba.png)

Meine Idee wäre: man kann einen Ergebnisordner auswählen (wird automatisch entsprechend aktuellem Projekt gesetzt). Dann folgen diese Schritte:

1. Lesen & Prüfen verfügbare Ergebnisse
Es werden verfügbare Ergebnisse in einem TableWidget aufgelistet. Das Lesen der Ergebniswerte passiert ggf. erst wenn man eine konkrete Ergebnisgröße auswählt. (Alternativ auch direkt beim Auswählen des Ordners, aber das könnte dann lange dauern bei vielen Ergebnissen.)
Es wird geprüft ob sich für eine Ergebnisgröße (z.b. "AirTemperature", "SurfaceTemperatureA") alle Ergebnisse (""ConstructionInstance(id=1).SurfaceTemperatureA", ...) im Projekt vorhandenen IDs zuordnen lässt. Also wenn "ConstructionInstance(id=1).SurfaceTemperatureA" gefunden wurde muss auch eine ConstructionInstance mit dieser ID vorhanden sein. Zum Übersetzen DisplayName -> Generischer Name mit id muss natürlich die "objectref_substitutions.txt" gelesen werden. Wenn Prüfung negativ ist, wird der Eintrag im TableWidget rot und ist nicht verfügbar. 

2. Lesen der Ergebniswerte
Wenn die Ergebnisgröße gelesen werden kann, ist sie auswählbar. Durch button oder Doppelklick werden die Werte gelesen. Nach erfolgreichem Lesen wird das durch ein Icon im TableWidget signalisiert. Es kann diese auf die Objekte in der Szene gemappt werden. Die Ergebnisse werden während der Laufzeit gehalten und müssen nicht nach jedem Wechsel nochmal neu gelesen werden.

3. Darstellungseigenschaften
Es werden min/max Wert und eine colormap ausgewählt.
Über den Zeitstrahl wie im PostProc lässt sich die Zeit einstellen bzw. durchlaufen.

**Comment by ghorwin** [comment]
Finde ich gut - man sollte die Ergebnisse einer Berechnungsvariante direkt in der Oberfläche zugeordnet (sofern möglich) zu den sichtbaren Geometrieobjekten sehen können.

Ein Nachprogrammieren des PostProc, sprich Anzeigen von Liniendiagrammen selbst halte ich nicht für sinnvoll.

Für alle Falschfarbendarstellungen muss man Ergebnisdaten (Zeitreihen) geometrischen Objekten zuordnen. Dabei gibt es eine 1-zu-viele Zuordnung, d.h. einem Geometrieelement (Beispiel: Wandfläche oder Netzwerk-Edge) können mehrere Zeitreihen zugeordnet werden (beispielsweise: Temperatur, Wärmestrom, ...).

Die Zuordnung ist durch die Verwendung der Objekt-IDs in den Zeitreihenkennungen eigentlich direkt möglich; bei Modellausgaben muss man ggfs. noch umsortieren/Bezeichner parsen für die Zuordnung. 

Falls man unpassende Projektdateien und Ergebnisdateien mischt (beispielsweise wenn man einen Netzwerkknoten an andere Stelle verschiebt oder eine Wand löscht und woanders eine neue Wand mit gleicher ID einlädt), besteht die Gefahr, dass man falsche Zuordnungen verwendet und die Anzeige dann schlicht falsche Werte anzeigt. Dies sollte man **unbedingt** vermeiden.

Daher würde ich in erster Instanz nur die Anzeige von Ergebnissen passend zum Projekt erlauben.

Workflow:

1. `projekt007_Var_A.vicus`  -> Ergebnisse in `projekt007_Var_A`
2. Variante erstellen -> `projekt007_Var_B.vicus`  -> Ergebnisse in `projekt007_Var_B`

Erfordert etwas Disziplin beim Anwender, aber bei Gutachten/Berechnungen ist es immer sinnvoll, wenn man Ergebnisse später nochmal reproduzieren kann und daher die _exakt_ verwendeten Eingabedaten nochmal vorliegen hat.

Damit entfällt die Auswahl des Ergebnisverzeichnis - entweder es gibt Daten im automatisch generierten Verzeichnis oder nicht.


Für die Falschfarbendarstellung von Ergebnissen bräuchte man nun eine Liste von Ansichtsdefinitionen, zum Beispiel:

- Raumlufttemperaturen (alle Innenwandflächen werden entsprechend der Zonentemperatur eingefärbt)
   * entweder Momentanwert (abhängig vom aktuell gewählten Zeitpunkt)
   * oder Minimalwert
   * oder Maximalwert
- Wärmeverluststrom (alle Außenoberflächen werden entsprechend des Wärmestroms (Gesamt-/nur Wärmetransmission) eingefärbt)
   * Moment oder Min oder Max

Für jede Ansicht (und damit Variable) braucht man (wie von Hauke unter 3. aufgelistet):

- Auswahl: Colormap (Wert -> Farbe-Abbildung) analog wie im PostProc
- Auswahl: Zeitpunkt (nur für Momentananzeige)
- Auswahl: Momentan/Min/Max

Die Aktualisierung der Ergebnisse würde ich automatisieren, d.h. wenn man im Auswertungsmodus der Oberfläche ist, werden Ergebnisdateien in regelmäßigen Intervallen geprüft (alle 30 Sekunden?) und wenn Zeitstempel seit letzter Prüfung geändert, werden die entsprechenden Ergebnisdaten neu gelesen (wie Auto-Update-Funktion beim PostProc).

**Comment by Labauke** [comment]
@ghorwin Den Results Pfad habe ich jetzt mal editierbar gelassen. Eine Anwendung könnte die Co-Simulation sein, wo die Ergebnisse im MasterSim slaves Pfad gespeichert sind.
Der ist aber defaultmäßig gesetzt und als normaler Nutzer wird einen das auch nicht interessieren...
