### ISSUE TITLE
Programmabsturtz beim Öffnen der Komponenten-Datenbank

### ISSUE THREAD

**Issue by thespookyabyss** [ghorwin/SIM-VICUS#593]
Die Konstruktionen-Datenbank kann ich ohne Probleme öffnen.
Wenn ich aber über den Reiter "Datenbanken" direkt auf die Komponenten-Datenbank zugreifen will stürtzt das Programm ab.

Im rechten Menü wo ich dem Model die Komponenten zuweise gibt es ein ähnliches Problem, solange in der Liste die Komponente aufgeführt ist kann ich diese auch zuweisen (also solange ein Bauteil dem diese Komponente zugewiesen wurde sichtbar ist), möchte ich jetzt einem Bauteil eine Komponente zuweisen die nicht in der Liste aufgeführt ist drücke ich auf den Button "Komponente zuweisen...", danach stürtzt das Programm wieder ab.

Tschau

**Comment by Labauke** [comment]
Bitte nochmal live zeigen kann ich nicht nachvollziehen

**Comment by ghorwin** [comment]
Hi, 

welche Programmversion wird verwendet? Ich schau mir das mal an...

**Comment by thespookyabyss** [comment]
Moin,


hab die Version v0.9.1 auf meinem Desktop-PC installiert, am 14.02.23 von der GitHub-Seite herunter geladen.


Auf meinem Laptop habe ich v0.9.2 da tritt das Problem nicht auf.


Dirk Weiß sagte mir, das Problem sei möglicher Weise schon bekannt.


Tschau


________________________________
Von: Andreas Nicolai ***@***.***>
Gesendet: Samstag, 25. Februar 2023 16:12:33
An: ghorwin/SIM-VICUS
Cc: Wild, Rene; Author
Betreff: Re: [ghorwin/SIM-VICUS] Programmabsturtz beim Öffnen der Komponenten-Datenbank (Issue #593)


Hi,

welche Programmversion wird verwendet? Ich schau mir das mal an...

**Comment by ghorwin** [comment]
Ja, scheint in der aktuellen Version behoben zu sein. Bitte einfach auf die neueste Version aktualisieren und falls es nochmal auftritt, das Ticket wieder öffnen.
