### ISSUE TITLE
Datenbankelemente Umschaltung zwischen UserDB ist möglich wenn kein Projekt geöffnet ist

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#599]
Wenn man SIM-VICUS startet und kein Projekt läd dann sind die Buttons für die Umschaltung von User-DB und Projekt-DB aktiv.
Diese müssten dann ausgeschalten sein. Es gibt ja keine geladene Projektdatei wo er es hinspeichern könnte.

Daher wenn kein Projekt geladen wurde sollten diese Buttons immer inaktiv sein.

**Comment by ghorwin** [comment]
Buttons sind jetzt unsichtbar, wenn kein Projekt geladen ist.
