### ISSUE TITLE
Randbedingungs DB überarbeiten

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#608]
1. Außenbedingung (nur Wärmeleitung): alpha=25 W/m2K
2. Außenbedingung (Wärmeleitung + Kurzwellig): alpha=25 W/m2K, a=0,6
3. Außenbedingung (Wärmeleitung + Kurzwellig + Langwellig): alpha=17 W/m2K, a=0,6, e=0,9
4. Innenbedingung (nur Wärmeleitung): alpha=8 W/m2K
5. Innenbedingung (nur Wärmeleitung + Langwellige Strahlung): alpha=2,5 W/m2K, e=0,9
6. DIN Norm Bedingungen...

Also, immer wenn Langwellig eingeschaltet, dann wird der effektive alpha-Wert reduziert (sonst ist der Strahlungsaufschlag ja schon drin).

**Comment by Labauke** [comment]
sind als built in DB elemente eingebaut
