### ISSUE TITLE
Implement support for pre-computed shading

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#61]
Verschattungsfaktoren werden mit dem Preprozessing vorbereitet und der NANDRAD-Simulation übergeben. Dabei gibt es zwei Varianten:

1. LinearSpline-Daten, welche in `WindowShading` referenziert werden (entweder inline oder als TSV-Dateien mit `path/to/file.tsv?<colindex>` Syntax). Implementierung dafür existiert bereits in `NANDRAD::LinearSplineParameter`

2. zentrale Binärdatei, referenziert in `Location`, mit Zuordnung der Spalten via ID des EmbeddedObject.

**Comment by Arombolosh** [comment]
Zuerst nach linear Spline Para suchen
Wenn leer -> aus Location Loads Model zugreifen (Binärdatei)

**Comment by Arombolosh** [comment]
externe Verschattung wird vom loads model automatisch berechnet
Funktion qSWRad liefert automatisch reduzierte Direktstrahlung abh. von Fenster/KonstruktionsId (ein ID-Space)
Verschattungswerte stehen in einer Binärdatei vom Location Obj referenziert.
