### ISSUE TITLE
Drehung der Szene fehlerhaft bei Erreichen der Ränder

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#614]
Im Linux 22.04 wird beim Drehmodus wenn die Maus die Ränder erreicht das Modell in Lichtgeschwindigkeit rotiert.

**Comment by hirseboy** [comment]
Liegt an Wayland --> keine Ahnung warum; unter X.org keine Probleme...

Wayland ist buggy

**Comment by ghorwin** [comment]
Nur unter 22.04, ich teste das gerade... muss an einem Windowmanager-Event liegen oder sowas

**Comment by ghorwin** [comment]
Reproduzierbare beim "Panning", Wayland, Multi-Screen-Konfiguration:

```
Resetting mousepos to right side of window.
Entering panning mode
newLocalMousePos= QPoint(50,548) , mapToGlobal(newLocalMousePos)= QPoint(2341,609)
QCursor::pos()= QPoint(3121,609)
QCursor::setPos(mapToGlobal(newLocalMousePos));
QRect(1920,0 1920x1080)
QCursor::pos()= QPoint(2341,609)
SceneView::mouseMoveEvent(), QCursor::pos()= QPoint(2341,609)
SceneView::processInput(), QCursor::pos()= QPoint(2341,609)
SceneView::mouseMoveEvent(), QCursor::pos()= QPoint(3124,609)
SceneView::processInput(), QCursor::pos()= QPoint(3124,609)
```

Das Umsetzen des Cursors funktioniert, aber der SceneView bekommt kurz darauf vom WindowManager erneut die alte Cursor-Position. Warum und woher? Keine Ahnung...

**Comment by ghorwin** [comment]
https://discourse.gnome.org/t/pointer-warping-on-wayland/9197
