### ISSUE TITLE
U-Value calculation of windows should include both frame and glazing system

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#619]
see Window::calculateUValue()

**Comment by ghorwin** [comment]
function is only used in DB dialog, export code in ProjectGenerator does compute frame factor correctly.

TODO : move function to class VICUS::Window and review implementation.

**Comment by hirseboy** [comment]
Der U-Wert kann nur mit Rahmen berechnet werden, wenn man diesen anteilig festlegt. Bei konstanter Rahmenbreite ist dieser abhängig vom konkreten Fenster.

Wie soll das gemacht werden?

**Comment by ghorwin** [comment]
Dafür brauchen wir einen geometrischen Window-Designer oder ein parametrische Geometriemodell. Würde das im windowDB Dialog einbauen.

**Comment by hirseboy** [comment]
Naja, das Problem ist, dass die Geometrie der Fenster an der Geometrie der Sub-Surfaces hängt. Und diese kannst du auch nicht in einem Window-Designer festlegen. Oder sehe Ich da etwas falsch?

**Comment by michaldengusiak** [comment]
Are you planning to continue working on this project?

**Comment by hirseboy** [comment]
Hi Michal,
SIM-VICUS is no longer maintained and is receiving a commercial brother called VICUS Buildings / Districts.

**Comment by ghorwin** [comment]
So, in a nutshell, yes - this feature is being implemented (right now) and will be part of the commercial release.
