### ISSUE TITLE
Re-enable output grid editing

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#620]
Der Code in `SVOutputGridEditDialog::on_tableWidget_cellChanged()` ist auskommentiert.. bitte bei Gelegenheit reparieren oder zumindest ein TODO eintragen, dass man das in der TODO-Liste sieht.

**Comment by Labauke** [comment]
das TableWidget wird immer geparst, der slot wird nicht benötigt, habe ich entfernt
