### ISSUE TITLE
Fix Maus-Panning (Regressionsbug durch Einführung der Leertaste-Beschleunigung)

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#623]
Erwartetes Verhalten:

- beim Panning mit der Maus _ohne_ Drücken der Leer-/Shifttaste bleibt der angeklickte Punkt unter dem Mauscursor

- aktuelles Verhalten: Wenn man die Leertaste gedrückt hält, bleibt der angeklickte Punkt unter der Maustaste

Das bitte zurückändern - Leertaste sollte beim Panning keine Funktion haben

**Comment by hirseboy** [comment]
Ich habe das extra geändert, da beim panning, wenn man nah am Gebäude ist und kein Bauteil erwischt, ins nirgendwo verschwindet. Und das passiert super oft, weil der Pickpoint am Ende der Gridebene ist. 

Aus meiner Sicht würde ich das mit dem Pickpoint unter Mauszeiger nur bei Pickpoints mit einer geringen Distanz machen. 
Und so funktioniert das auch derzeit.

**Comment by ghorwin** [comment]
Ok, da müsste ich mir die Logik nochmal anschauen. Hab auch das Problem noch nicht ganze verstanden.

_"man nah am Gebäude ist und kein Bauteil erwischt"_ klingt auch irgendwie nach einem Bug beim Picking-Algorithmus - oder der Mindestabstand beim Standard-Klick-Punkt ist schlicht schlecht.

Wie kann ich das genau nachvollziehen?

**Comment by hirseboy** [comment]
https://user-images.githubusercontent.com/58851829/226402625-65929122-9cef-4c2a-a693-ea4c6ed1b9b7.mp4

Erstes: So funktioniert es gerade (also mit Dämpfung)
Zweites: Altes verhalten, pick-point immer unter mauszeiger

**Comment by ghorwin** [comment]
Ok, ist wie vermutet: kein PickPoint gefunden -> Schnittpunkt fälschlicherweise auf Nearplane gesetzt -> damit sehr nervöses Verschieben.

Fehlerbehebung: Fallbehandlung einbauen wenn kein Schnittpunkt gefunden, bzw. Schnittpunkt zu dicht -> dann Schnittpunkt künstlich x m nach hinten verlegen.

**Comment by ghorwin** [comment]
Passt so, eventuell sollte man eine "Vogelperspektive" erkennen und hier das "Damping" automatisch ausschalten (bspw. wenn Camera-z > 50 m).
