### ISSUE TITLE
Ctrl+A Fehler beim LineEdit

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#625]
Bei der Raumerstellung klickt man in das LineEdit zur Eingabe der Raumhöhe.
Fokus ist im Lineedit. Nach Ctrl+A um den Text schnell zu markieren wird die Zonenerstellung abgebrochen.

Das Ctrl+A muss prüfen ob ein Fokus im LineEdit vorliegt. Falls Ja gilt dies fürs Lineedit.

Ebenso hats bei der Zonenerstellung alles weg man man ausversehen Ctrl+A bei der Zonenerstellung drückt.
Da sollte das unterbunden werden.

**Comment by ghorwin** [comment]
Liegt am globalen "Ctrl+A" -> Selection Bug, dies führt zu einen Undo-Action und einen ViewState update. Muss man Top-Level in `SVDebugApplication::notify()` abfangen
