### ISSUE TITLE
Automatisches speichern + Dialog Wiederherstellung bei Crash

### ISSUE THREAD

**Issue by hirseboy** [ghorwin/SIM-VICUS#627]
SIM-VICUS sollte in regelmäßigen Abständen (10 Min) back-ups der Projektdatei erzeugen und speichern (als *.bak zum Beispiel). Sollte SIM-VICUS abstürzen, merkt es sich die letzte bearbeitete Datei, erkennt ein back-up und fragt, ob dieses wiederhergestellt werden soll.

**Comment by Labauke** [comment]
Ich würde es sogar öfter speichern, jede Minute?

Vorschlag:
- Das Projekt wird regelmäßig als "*.vicus.bak" oder "*.vicus-bak" gespeichert, im aktuellen Verzeichnis oder im Nutzerverzeichnis?
- Beim Schließen des Projekts durch den Nutzer wird diese Datei gelöscht. Egal ob er auf "Save" oder "Discard" klickt.
- Beim Programmstart wird nach der Datei gesucht. Wenn diese gefunden wird, kommt ein Dialog der fragt ob das Projekt wiederhergetsellt werden soll.

**Comment by Labauke** [comment]
Am sinnvollsten wird die Backup-Datei im Nutzerverzeichnis gespeichert. Sobald man das Programm startet und irgendeine ".bak" datei gefnden wird kommt der Dialog zum Wiederherstellen.

**Comment by hirseboy** [comment]
Alle 5 Minuten sollte reichen...

Ansonsten finde ich deine Vorschläge gut!

**Comment by hirseboy** [comment]
Hab' schon einen konkreten Plan. Implementiere das die Tage mal.

**Comment by ghorwin** [comment]
UH OH... ich sehe die Finsterniss am Horizont. Wenn man als Entwickler anfängt, einen Programmcrash "einzuplanen" und mit Backups abzusichern, dann ist aus meiner Sicht das Ende einer qualitativ hochwertigen Software in Sicht. Das Ziel muss eigentlich immer sein, jedwede Crashs bereits bei der Entwicklung des Codes zu vermeiden und falls einer auftritt, diesen zu reparieren.

Klar, eine Backup-Datei kann bei einer Beta-Version (mit der bereits produktiv gearbeitet wird) Arbeitszeit und Frust sparen, aber führt unweigerlich zum Status-Quo: _"ein paar Crashes sind doch ok, wir haben ja ein Backup..."_  Hatten wir alles schon in DELPHIN 4 (und in diversen kommerziellen Tools), will ich für SIM-VICUS definitiv nicht! Auch führt das dazu, dass Anwender einfach das Backup Laden und sich nicht mehr die Mühe machen, einen Crash zu berichten... damit bleibt das Problem länger bestehen.

Außerdem bedenkt, dass in Zukunft die Projektdateien eventuell größer werden könnten, und alle 5 Minuten ein Backup schreiben (vor allem bei Arbeit auf Netzlaufwerken) nervig sein kann. Also muss das auf jeden Fall deaktivierbar sein (Settings).

Aber noch mal mein Appel: bitte versucht bereits beim Schreiben des Quelltextes jedwede Crash-Möglichkeiten auszuschließen und arbeitet mit ASSERTS, damit man bei Auslösen einer Ausnahme immer noch ausreichend Info für die Fehlerbehebung bekommt.

Konkret heißt das auch: macht bitte Code-Reviews bei Merge-Request akribisch und hinterfragt Annahmen. Ein Merge/Pull-Request heißt nicht nur, Compilierfähigkeit herstellen!

**Comment by ghorwin** [comment]
@Labauke: generieren eines eindeutigen Pfades beachten, beispiel:

```
D:\Projekte\Haus-Var1\Haus.vicus
D:\Projekte\Haus-Var2\Haus.vicus
```

da sollten separate Backupdateien erstellt werden
