### ISSUE TITLE
Do heat transfer coefficients defined for constructions apply for embedded windows as well?

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#63]
Construction instances have heat transfer coefficients for the inside/outside, the latter possibly depending on wind velocity.

Embedded objects (windows) only have a U-value (ThermalTransmittance). Should the properties from the construction be applied to windows as well, and if yes, how?

**Comment by hirseboy** [comment]
I think the convection should be specified inside the construction instance whereas the radiation is specified inside the (detailed) window since its a property of the glass itself.

**first** possibility:
It could be parameterized inside the embedded object tag similiarily as it is done for the interfaceA and B?
e.g.
```
<EmbeddedObject id="1000" displayName="Window 7.2">
		<IBK:Parameter name="Area" unit="m2">5.04</IBK:Parameter>
		<IBK:Parameter name="HeatTransferCoefficientInside" unit="W/m2K">2.5</IBK:Parameter>
		<IBK:Parameter name="HeatTransferCoefficientOutside" unit="W/m2K">8</IBK:Parameter>				
		<Window glazingSystemID="10000" />
</EmbeddedObject>
```
**second** possibility:
Could be done also inside the interfaces. 
```
<InterfaceA id="5" zoneId="1">
	<!--Interface to 'TF07_1'-->
	<InterfaceHeatConduction modelType="Constant">
		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">2.5</IBK:Parameter>
	</InterfaceHeatConduction>
	<InterfaceSolarAbsorption modelType="Constant">
		<IBK:Parameter name="AbsorptionCoefficient" unit="---">0</IBK:Parameter>
	</InterfaceSolarAbsorption>
	<InterfaceLongWaveEmission modelType="Constant">
		<IBK:Parameter name="Emissivity" unit="---">0</IBK:Parameter>
	</InterfaceLongWaveEmission>
	<InterfaceWindowConvection modelType="Constant">
		<IBK:Parameter name="HeatTransferCoefficient" unit="W/m2K">0</IBK:Parameter>
	</InterfaceWindowConvection >
</InterfaceA>
```

What do you think?

**Comment by ghorwin** [comment]
Ok, let's define these rules:

- Window/Frame/Divider need heat transfer coefficients on both sides
- transfer coefficients can be taken from construction instance, if parametrized (must be present in any case for heat conduction flux to be calculated - heat conduction through windows without parameter block for heat conduction of construction is forbidden)
- transfer coefficients can be taken from EmbeddedObjectWindow, if window should have different values (due to roughness etc.); However, than the alpha values for the glass also apply to frame and divider

**Comment by hirseboy** [comment]
Okay, seems reasonable!
