### ISSUE TITLE
Thumbnailpfad ist nicht eindeutig

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#633]
Wenn ein Projekt im 
OrdnerA/Var0.vicus 
heißt und ein zweites Projekt
OrdnerB/Var0.vicus
dann wird immer das falsche Bild bei einem Projekt dargestellt.

Es darf nicht nur anhand des Porjektnames das Bild gemerkt werden sondern anhand des gesamten Projekt-FilePath.

**Comment by ghorwin** [comment]
Wird aktuell bereits so gemacht: `SVMainWindow::saveThumbNail()`

```c++
	QString thumbName = prjFinfo.fileName() + "_" + prjFinfo.dir().dirName();
	QString thumbPath = QtExt::Directories::userDataDir()  + "/thumbs/" + thumbName + ".png";
 ```
Die Frage ist, warum wird das falsche Bild angezeigt?
