### ISSUE TITLE
Review/Redesign autosave

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#634]
- timer nicht in dialog -> Aufgabe des MainWindow (läuft im MainWindow-Master-Thread)
- Usability-Fragen + Design
- wie viele Autosaves braucht man wirklich?
- kein Dialog-Singleton (Lebenszeitkontrolle) -> gleiches Implementierungsschema wie bei anderen Dialogen (vereinfacht Wartung)

**Comment by Labauke** [comment]
Die Datenbanken werden im Moment nicht gespeichert. Es gab gerade das problem, das nach einem harten Absturz viele angelegte Datenbankelemente nicht mehr da waren, trotz auto-save Funktion.

Spricht was dagegen beim autosave die `writeDatabases()` Funktion aufzurufen?
