### ISSUE TITLE
AutoSave - Funktionalität klären bei mehreren geöffneten Instanzen

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#637]
Wenn mehrer Instancen von SIM-VICUS offen sind kommt das Autosave mit diesen nicht zurecht.
Bitte hier mal Tests durchführen und das ganze validieren.

**Comment by ghorwin** [comment]
Bitte mal auf der Diskussionsseite beschreiben, wie das erwartete Verhalten aussieht:

- 2 Instanzen mit _unterschiedlichen_ Projekten -> geht mit der neuen Implementierung von gestern, mit der alten von Freitag gab's hier Datenverlust
- 2 Instanzen mit dem _gleichen_ Projekt.... das ist schlicht Quatsch, da würden die sich ja gegenseitig auch beim normalen "Save" die Daten überschreiben
-
