### ISSUE TITLE
Update QtExt validating line edit

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#641]
im randbedingungsdialog beim umschalten von "aktiver zone" auf "zone mit temperaturvorgabe" wird das line edit nicht korrekt grau/schwarz angezeigt

ist ein update problem

**Comment by Labauke** [comment]
repaint() reicht, hab ich schon probiert. Ich würde das in der QtExt::ValidatingLineEdit::setEnabled einbauen

**Comment by ghorwin** [comment]
👍🏼  Jo, machmal
