### ISSUE TITLE
Vorberechnung von Sichtfaktoren vor jeder Simulation durchführen

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#645]
Ob die berechneten Sichtfaktoren zur aktuellen Geometrie passen, lässt sich praktisch schlecht prüfen. Außerdem ist es schwer zu wissen, dass man das überhaupt machen muss -> schlechte usability
Deshalb:
Bei Simulationsstart sollte geprüft werden ob irgendwo innere langwellige Strahlung verwendet wird.
Wenn nicht: Sichtfaktoren löschen (vermeidet Fehler)
Wenn ja: View3d ausführen

**Comment by hirseboy** [comment]
Already implemented
