### ISSUE TITLE
Bug: SmartClipping funktioniert nicht (Exception)

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#654]
Bei Ausführen des Smart-Clipping gibt es 2 Probleme:

```
Surface 'Zone 2 | Floor' is beeing clipped by surface 'Zone 1 | Ceiling'
Surface 'Zone 2 | Ceiling' is beeing clipped by surface 'Roof | Floor'
Surface 'Roof | Floor' is beeing clipped by surface 'Zone 2 | Ceiling'
Roof                 Floor (2)             Zone 2               Ceiling (2)
Zone 2               Floor                 Zone 1               Ceiling
Subsurface component instance #116 references an invalid/unknown subsurface #115.
IBK::Exception caught.
```

1. Zuweisungsproblem (Exception) --> Nachbearbeitung notwendig
2. Surface Connection view wird nach "Apply to building" nicht aktualisiert und "set modified" nicht korrekt ausgeführt (Projekt erscheint nach Anwendung immer noch unverändert). Letzteres wahrscheinlich durch die Exception bedingt.

Nach Auftreten der Exception ist ein "Undo" nicht möglich, da jedes Mal erneut die Exception kommt  --> Datenverlust.

Beispielprojekt im Anhang...
[EFH.zip](https://github.com/ghorwin/SIM-VICUS/files/12160493/EFH.zip)

**Comment by hirseboy** [comment]
:(

**Comment by hirseboy** [comment]
Komisch, da ist ein mapping falsch. Ich schaus mir an

**Comment by hirseboy** [comment]
Das EFH hat in der Geschossdecke ein Fenster (Also falsch modelliert). Und das bereitet dem Clipper derzeit noch Probleme, da das Fenster gelöscht wird, aber die Subsurface-Component enthalten bleibt.

**Comment by hirseboy** [comment]
08360676
