### ISSUE TITLE
Bug: bei Definition von Ausgaben (GlobalSWRadOnPlane) und mehreren ausgewählten Flächen wird immer "Die Ausgabeliste ist veraltet..." angezeigt

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#656]
Die Fehlermeldung verschwindet nicht bei "Ausgabeliste aktualisieren"

**Comment by ghorwin** [comment]
![Bildschirmfoto vom 2023-07-25 13-58-13](https://github.com/ghorwin/SIM-VICUS/assets/6892676/93d93bec-1f17-470b-94d4-741e094cb9aa)

**Comment by Labauke** [comment]
nicht nachvollziehbar, musst du mal ein Beispiel zeigen
