### ISSUE TITLE
Bug Kopieren von Geschossen/Gebäuden

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#661]
Beim Koopieren von Gebäuden oder Geschossen kommt nach der Kopie anschließend immer folgende Meldung:
Unfortunately the project contains 2 component instances with the same id #2232 but different connected surfaces.

Hier werden die "Component Instances" wahrscheinlich falsch belegt. Die sind dann doppelt da.

**Comment by ghorwin** [comment]
Beispielprojekt?

**Comment by Labauke** [comment]
Ist erledigt soweit ich das sehe?
