### ISSUE TITLE
Mausrad

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#662]
Bitte wieder das Verlangsamen beim Heranzommen an Items einstellen. Ich rase jetzt ständig komplett durch das Gebäude.

**Comment by ghorwin** [comment]
Geht die Verlangsamungstaste nicht mehr, oder soll es auch ohne Drücken der Verlangsamungstaste beim Reinzommen eine automatische Verlangsamung geben, wenn das nächste Objekt in der Maus-Sicht-Linie dichter als Abstand x dran ist?
