### ISSUE TITLE
geojson import Übergabestationen

### ISSUE THREAD

**Issue by hygeo** [ghorwin/SIM-VICUS#668]
Beim Import von Übergabestationen aus GIS wäre es hilfreich, wenn man nur eine geojson Datei importieren könnte, in deren Attributtabelle Name und individuelle Anschlussleistung für jede einzelne Übergabestation eingetragen sind. Bei Netzen mit vielen verschiedenen Gebäudetypen ist es sonst sehr aufwändig für jeden Gebäudetyp eine einzelne geojson Datei anzulegen und einzeln zu importieren.

**Comment by Labauke** [comment]
Der Hinweis kam schon öfter und tatsächlich geht das schon, nur nicht dokumentiert. 
Mit dem geoJSON Attribut `MaxHeatingDemand` kann man die Anschlussleistung in kW angeben :)

**Comment by hygeo** [comment]
Das ist ja super. Kann man den Namen auch direkt in der Attributtabelle festlegen?
