### ISSUE TITLE
Distribution of solar radiation loads in zones

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#67]
We need to define how we parametrize the distribution options for solar radiation in zones.

a. globally (simulation parameter)
b. individually per zone

My preference is (a).

We should have a factor for splitting total solar radiation gains into "fraction to room air balance" and "fraction to wall surfaces".

Options for distributing solar loads to walls:

1. globally; area-weighted distribution
2. zone-specific view-factor based:
    a) for all windows the same distribution factors (one per wall surface, all adding up to 100%)
    b) individually for each window 

2b) requires much more effort in implementation with potentially little gain in accuracy (--> later, if needed).

IMHO best compromise for now is to use the THERAKLES model:
- global factor for splitting radiation loads into zonal and wall-surface loads + area-weighted distribution of solar loads onto wall surfaces

**Comment by Arombolosh** [comment]
There is a third way. Distribution of the radiation loads between air nodes and surfaces. Furthermore, the surfaces are divided into 3 categories:
Roof/ceiling
Walls
Floor
A factor is set for each category. All three factors add up to 1. 
This allows a large part of the radiation to be sent to the ground. (That's where it usually falls down)

Would be 1 + 3 factors.

Later a suitable distribution to all surfaces should be installed with pre-calculated radiation factors. This can be done with "View3D".

Translated with www.DeepL.com/Translator (free version)

**Comment by ghorwin** [comment]
Parameters added:

```
SimulationParameter::P_RadiationLoadFractionZone
SimulationParameter::P_RadiationLoadFractionFloor
SimulationParameter::P_RadiationLoadFractionCeiling
SimulationParameter::P_RadiationLoadFractionWalls
```

Enumeration type ```SimulationParameter::swrad_distribution_t``` defines which distribution method to use.

For type ```SimulationParameter::SWR_SurfaceTypeFactor``` we need some property in Interface that identifies this surface as "floor" or "ceiling" or "wall".

**Comment by ghorwin** [comment]
Definition: all construction instances, that have an interface to a given zone, will receive their fraction of the radiation loads imposed to this zone. It is not necessary to have other interface boundary condition parameters defined. Adsorption coefficient is ignore in the area-weighted solar radiation load distribution model.

**Comment by ghorwin** [comment]
Refactoring needed: move all radiation distribution parameters to a separate model object, which can be instantiated during simulation per zone and will provide checked/fixed distribution parameters to room balance model and construction balance model.
