### ISSUE TITLE
Lokales Koordinatensystem sollte immer sichtbar sein

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#673]
Ich kann das lokale Koordinatensystem im Moment irgendwo absetzen, dann verschwindet es aber wieder.
Entweder ich sollte keine Möglichkeit haben das zu tun (Button deaktiviert) wenn keine Fläche gewählt ist. Oder es sollte immer möglich sein das lok. Koordinatensystem abzusetzen, auch wenn keine Fläche gewählt ist.

**Comment by ghorwin** [comment]
Das ist ein grundsätzliches Problem der Benutzerführung. Das lokale Koordinatensystem wird nur benötigt für:

- Neukonstruktion
- Transformation existierender Geometrie

Letzteres verlangt eine ausgewählte Geometrie. Ob und wie man ein abgesetztes/verschobenes Koordinatensystem für "später" aufbewahren kann ("Speichern von Ort und Ausrichtung"), wäre ein neues Feature.

Das lokale Koordinatensystem einzublenden, ohne eine dazu passende Aktion zu haben, fände ich nicht gut.

**Comment by ghorwin** [comment]
Lösungsansatz: LKS immer einblenden, wenn benötigt, sonst nie. Die Operationen zum Platzieren/Ausrichten des LKS sollten gesperrt sein, wenn aktuell kein LKS-Sichtbar-Modus an ist.
