### ISSUE TITLE
Falsche z Position beim Abklicken von Drawings

### ISSUE THREAD

**Issue by Labauke** [ghorwin/SIM-VICUS#681]
Tritt bei mir bei einem großen DXF Plan mit vielen Elementen auf:
Wenn ich Rohre zeichne durch snappen des Drawings, bekomme ich teilweise z Positionen von +3cm, da das sicher die richtige gezeichnete Position der Linie im Drawing ist.

Könnte beim Zeichnen von Zonen ebenso passieren.

Lösung: beim Snappen eines Drawings als z-Koordinate die des origins des Drawings nehmen? Oder die des eigentlichen Elements, also der Drawing::PolylIne statt der PlaneGeometrie?

**Comment by hirseboy** [comment]
Fixes with commit ...
