### ISSUE TITLE
Improve object translation operations

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/SIM-VICUS#87]
Improve object translation handling:

- switch spinbox with validating line edit
- remove radiobuttons
- add three distinct buttons: absolute, relative global, relative local
- think of "copy" operation: either also three buttons, or modifier key when pressing the button, or checkbox?

**Comment by hirseboy** [comment]
Three distinct buttons are not possilbe since I'd also like to set for example if translation and "absolute" is toggled the center of the local coordinate system to the xyz coordinates. So that the user gets an better impression where he can translate the objects. 
Same for scaling and rotating

**Comment by hirseboy** [comment]
I will make an proposition what we can do else to get away those radio buttons
