### ISSUE TITLE
[Feature] View Normals for each point

### ISSUE THREAD

**Issue by Arombolosh** [ghorwin/SIM-VICUS#95]
Ein Anzeigemodus für die Normalen wird benötigt.
Jede sichtbare Fläche stellt an jedem Punkt ihrer Polyline einen Normalenvektor dar. Damit würde ein Rechteck vier Normalenvektoren einer Länge ((1 m) erstellen. Alle Vektoren wären parallel.
Dieser Modus müsste zuschaltbar sein oder im Oberflächenkonzept ausgewählt werden können.
Ein Quader mit sechs Flächen stellt dann 24 Normalen dar, wobei es 8 Ursprungspunkte gibt und in jedem 3 Normalen beginnen würden.

**Comment by ghorwin** [comment]
Wir bräuchten noch eine Konvention, wie mit (Innen-)Oberflächen umgegangen wird, die eine Komponente mit gegenüberliegender (unsichtbarer) Außenwand haben. Hier könnte der Modellierer vermuten, die Eigenschaften (und damit Normalenvektoren) einer Außenwand zu sehen und würde sich dann wundern, warum Ausrichtung, Neigung und Normalenvektor der Innenoberfläche entsprechen (dabei wäre das vollkommen korrekt - es wird nur dargestellt und kann nur ausgewählt werden, was sichtbar ist - Außenwandoberflächen sind nicht sichtbar).
